### ISSUE TITLE
How to de-duplication of insert

### ISSUE THREAD

**Issue by tonouchi510** [googleapis/nodejs-bigquery#1002]
I want to insert a de-duplicated record by the method described in the URL below.
with node-js, how can I implement this?

https://cloud.google.com/bigquery/streaming-data-into-bigquery#dataconsistency

**Comment by steffnay** [comment]
De-duplication is handled with the use of insertIds, which are created in the `table.insert()` method by default. https://github.com/googleapis/nodejs-bigquery/blob/46c9b3960e55c729df17d84dfec424dab706d1d7/src/table.ts#L2119
