### ISSUE TITLE
Cannot set a HTTP proxy for only this library

### ISSUE THREAD

**Issue by chanind** [googleapis/nodejs-bigquery#1021]
There's no option to set a http proxy when using this library. It appears that the `teeny-request` library does support this, but there's no option which can be passed to bigquery that can set default options for `teeny-request`, such as the [proxy option](https://github.com/googleapis/teeny-request/blob/main/src/agents.ts#L42).

It seems the only way to set a HTTP proxy is to set an ENV var globally, but that sets the proxy for every request for everything globally, not just for this lib. I need a way to set a HTTP proxy for only this library, as different URLs on the backend need to be routed via different HTTP proxies.

**Comment by loferris** [comment]
We don't currently support HTTP proxy management in the library itself to allow flexibility for end-users in setting up their own configurations.
