### ISSUE TITLE
BigQuery Feature: Support key less authentication

### ISSUE THREAD

**Issue by samuellundberg** [googleapis/nodejs-bigquery#1027]
We are using Workload Identity Federation for an key less authentication to a GCP Service Account using ExternalAccountClient from 'google-auth-library' . 

All provided samples on authenticating to BigQuery include properties from a key file or path to a key file, which we do not have in our key less solution. 

We have seen the possibility to provide an [Oauth token](https://googleapis.dev/nodejs/bigquery/latest/global.html#BigQueryOptions) in the Big Query options. But when we try to provide a token we get "Error: Could not load the default credentials."

So we would like an example of how authenticate to BigQuery using an Oauth token.

**Comment by loferris** [comment]
I've changed priority level on this, and happy to re-engage when we have clarification!
