### ISSUE TITLE
Cross Project Support

### ISSUE THREAD

**Issue by satrox28** [googleapis/nodejs-bigquery#1030]
Hi, 

We have the dataset in a Project A and would like to run the Bigquery job from Project B. I already shared the Project A dataset to Project B's service account with Data Viewer access. I tested with bq command line and it works as expected. But when I try to run the job using this node module am getting error.
```
User does not have bigquery.jobs.create permission in project A.
```
Is there any workaround to specify the job execution Project ID?.

**Comment by steffnay** [comment]
This is a feature I am currently working on.

**Comment by satrox28** [comment]
Hi @steffnay , do you have any update on this issue?.

**Comment by steffnay** [comment]
@satrox28 I opened https://github.com/googleapis/nodejs-common/pull/722 which will allow me to implement this if approved.

**Comment by satrox28** [comment]
@steffnay thank you so much for taking time to work on it.

**Comment by satrox28** [comment]
Hi @steffnay I can see the above project PR is merged. May I know, when can we expect the change to be implemented on this nodejs-bigquery module?.

**Comment by satrox28** [comment]
Hi @steffnay Do you have any update on this request?.
