### ISSUE TITLE
Bigquery createQueryStream broken in 5.9.1+ for large query after set options update

### ISSUE THREAD

**Issue by mbyrne00** [googleapis/nodejs-bigquery#1043]
#### Environment details

  - OS: Any (macOS, debian nodejs container)
  - Node.js version: 14
  - npm version: 8
  - `@google-cloud/bigquery` version: 5.9.1+

#### Steps to reproduce

Query using `createQueryStream` and pass a `Query` object containing
 - `query: ` a large SQL string
 - `params:` an object of params

Server replies with `400 Bad Request` without many details.

**Root Cause**
The issue was introduced in PR #999 and specifically in this commit: https://github.com/googleapis/nodejs-bigquery/pull/999/commits/48d9a1527d2a921382a9efc40a20e2fbd4c1460a

In line `2011` the _whole_ query object is used as `options` which is not correct. This should be de-structured to _exclude_ the `query` and `params` properties. I am not 100% sure what happens at the server side but I'm guessing the size of the request becomes too large when you pass the complete `query` object _as well as_ the `query` and `params` properties contained within the `options`.

In the old version ...

```
    queryAsStream_(query, optionsOrCallback, cb) {
        let options = typeof optionsOrCallback === 'object' ? optionsOrCallback : {};
        const callback = typeof optionsOrCallback === 'function' ? optionsOrCallback : cb;
        options = query.job
            ? extend(query, options)
            : extend(options, { autoPaginate: false });
        if (query.job) {
            query.job.getQueryResults(options, callback);
            return;
        }
        this.query(query, options, callback);
    }
 ```

In our case we are hitting the line `this.query(query, options, callback)` and in the old version the `query` param had our original query, the `options` param had `{autoPaginate: false}` and the callback was passed.

In the `5.9.1+` version when we call `this.query(query, options, callback)`  the `query` param contains the original query object, the `options` param contains too much `{autoPaginate: false, query: 'MY LONG SQL QUERY', params: {allMyParams: 'vals'} }` ... hence you see the problem

This is a breaking change that is preventing us from upgrading beyond `5.9.0`

I can confirm that this issue does not occur when I supply a `Query` object containing one of our smaller SQL strings for the `query` property, hence why I think the `400 Bad Request` from the server is due to request size.

**Comment by steffnay** [comment]
@mbyrne00 Thank you for bringing this case to my attention. I'm working on a fix now.

**Comment by mbyrne00** [comment]
Hey @steffnay - thanks for looking into this ... I added some comments to the commit. Hope they help.

**Comment by mbyrne00** [comment]
Hi @steffnay - did you have a chance to look at my comments on the commits yet? Would love to get this fix in a release so we can upgrade again if possible. The code update was mutating a supplied object - some simple fix suggestions

**Comment by steffnay** [comment]
@mbyrne00 No, can you link to where you commented, please?

**Comment by mbyrne00** [comment]
Hey @steffnay - my comments are at the bottom of this page: https://github.com/googleapis/nodejs-bigquery/pull/1045. Here's a ![Screenshot](https://user-images.githubusercontent.com/5687982/144933759-f9fc485a-a160-4b37-9ac2-b2f022ae4347.png)

Mutating parameters is an obscure bug waiting to happen. For example if someone used this lib like so they would get unexpected results (I wouldn't call it this way but someone could rightly do so).

```
import { BigQuery } from "@google-cloud/bigquery";

const bigQuery = new BigQuery();
const options = {
  query: "SELECT * FROM person WHERE age = @ageParam",
  params: {
    ageParam: 18
  },
  maxResults: 10
};

const results1 = bigQuery.createQueryStream(options);
// ... do something with results1
// BAD: unknown to us options has been mutated and has maxResults stripped out

options.ageParam = 21;
const results2 = bigQuery.createQueryStream(options);
// ... <unexpected> ... results2 can won't be limited to maxResults of 10

```

**Comment by steffnay** [comment]
@mbyrne00 Thanks, I think I couldn't see them because they're pending. I am not observing the behavior you described. When running your sample code, the `options.maxResults` value persists in the second `bigquery.createQueryStream` call.

**Comment by mbyrne00** [comment]
Hey @steffnay - no probs, sorry. I see you've used that convention elsewhere too. I had troubles finding the `cqs-update` branch from your forked repo to look much further, so I'd say to just merge it all and I'm sure it's fine. I'll pull from `main` and if I can prove anything I'll file a separate issue.
