### ISSUE TITLE
table.getRows(); return type missing totalRows in typescript

### ISSUE THREAD

**Issue by belivo** [googleapis/nodejs-bigquery#1046]
The return type of getRows is the following:
RowsResponse = PagedResponse<RowMetadata, GetRowsOptions, bigquery.ITableDataList | bigquery.ITable>;

The intersection of _bigquery.ITableDataList | bigquery.ITable_ does not contain totalRows. I am not sure if this is intended. The value is there but not accessible from the type.

#### Environment details

  - OS: linux
  - Node.js version: v14.18.1
  - npm version: 6.14.15
  - `@google-cloud/bigquery` version: 5.9.2

#### Steps to reproduce

  1. Run a simple getRows and access the  in typescript and see that it's posing an error unless you cast to any beforehand.

`const [rows, , tableData] = await cachedTabled.getRows(getRowsOptions);`
`return { rows, totalRows: (<any>tableData).totalRows}; // for some reason the totalRows is obfuscated`

Thanks!

**Comment by tuphamdev96** [comment]
It still not working
Please check again
