### ISSUE TITLE
Allow for setting custom metadata when creating an extractjob

### ISSUE THREAD

**Issue by PaulRudin** [googleapis/nodejs-bigquery#1049]
As far as I can see there's no mechanism for setting custom metadata on the blob(s) created by an extract job. It would be useful to be able to do this. 

Of course you can set the metadata after the extract job has completed, but for some use cases this doesn't help - e.g. if you have events triggered by the creation of the blob.

Calling .setMetadata on the blob object prior to creating the extract job fails because it requires the blob to exist.

**Comment by steffnay** [comment]
Can you provide a code example of what you're requesting? It's possible to add custom properties to the job object locally, but you're correct that there's no way to set persistent metadata on the job before it has completed on the backend.
