### ISSUE TITLE
Load CSV data from local file (invalid datetime format)

### ISSUE THREAD

**Issue by anggidast** [googleapis/nodejs-bigquery#1060]
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 14.16.1
  - npm version: 7.24.1
  - `@google-cloud/bigquery` version: 5.9.2

I tried to use load local file (csv) refer to https://github.com/googleapis/nodejs-bigquery/blob/main/samples/loadLocalFile.js
when the data type is STRING, everything is load normally
but when I try to load with datetime value in my file (I already create new column with DATETIME data type) the error with message ` "Error while reading data, error message: Could not parse 'date' as DATETIME for field date (position 2) starting at location 0  with message 'Invalid datetime string \"date\"'"` appear.
I have following the datetime data type format refer to https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv, but the same error always appear. 
Examples value I use to try:
  1. 2021-01-10 00:00:00
  2. 2021-01-10 00:00:00.000000
  3. 2021-01-10T00:00:00
  4. 2021-01-10T00:00:00.000000
  5. 2021-01-10T00:00:00.00Z
  6. 2021-01-10 00:00:00.00Z

Can you tell me how can I load csv with datetime value properly?

Thanks!

**Comment by steffnay** [comment]
I think the issue you are encountering stems from having column names in first row of your CSV data. If it is the case that you have your column names in the file, please try adding the `skipLeadingRows` option.

Example:
```
    const [job] = await bigquery
      .dataset(datasetId)
      .table(tableId)
      .load(filename, {skipLeadingRows: 1});
```
