### ISSUE TITLE
Docs: createQueryJob no longer appears after release 5.9.1

### ISSUE THREAD

**Issue by Pokom** [googleapis/nodejs-bigquery#1068]
There does not appear to be a problem with the client library, the problem is with the documentation that's generated. In version 5.9.1 there existed documentation for [BigQuery.createQueryJob](https://googleapis.dev/nodejs/bigquery/5.9.1/BigQuery.html#createQueryJob). Starting in release[ 5.9.2](https://googleapis.dev/nodejs/bigquery/5.9.2/BigQuery.html#createQueryJob) this does not exist. It looks like the DocTags used were changed in release [5.9.2](https://github.com/googleapis/nodejs-bigquery/pull/1040/files#diff-24cffb127c4ad45cba6b82e80eeb02fbee9d3f78675f70b9a8f8be7a7bb13076R1358-R1359) that may have caused the documentation to no longer be generated.

This caused a bit of a panic for us and made us think `BiqQuery.createQueryJob` was removed in a minor patch 😅

**Comment by meredithslota** [comment]
Thank you for filing this issue! It looks like that change was made to support better comments here: https://cloud.google.com/nodejs/docs/reference/bigquery/latest/bigquery/dataset#methods but had unintended consequences for the existing docs!

**Comment by loferris** [comment]
We're in the process of moving our documentation to `cloud.google.com` (see why [here](https://cloud.google.com/blog/topics/developers-practitioners/productivity-unlocked-new-cloud-sdk-reference-docs)), and soon the `googleapis.dev` site will automatically redirect to the new site - there are some incompatibilities in TSDoc format for both site generators, which has unfortunately led to some differences in docs support on the two different sites, which you noted!
