### ISSUE TITLE
Expose authClient in BigQuery constructor

### ISSUE THREAD

**Issue by ellasev** [googleapis/nodejs-bigquery#1072]
**Is your feature request related to a problem? Please describe.**
I've been trying to authenticate with a service account impersonating another service account. The way to do it according to documentation (and the code of class 'Service') is to construct your own GoogleAuth and pass it to the relevant client using the authClient parameter. 
using the clientOptions available from BigQueryOptions, doesn't work because Service constructor ignores it. 

 **Describe the solution you'd like**
adding the authClient to BigQueryOptions solves this issue and gives the programmer full control

 **Describe alternatives you've considered**
* Editing the service code to use the parameters sent from clientOptions
* Not using the BigQuery API lib and using REST API instead.

**Comment by steffnay** [comment]
@ellasev  Is what you are requesting something other than the [`authClient` parameter from `GoogleAuthOptions`](https://github.com/googleapis/nodejs-bigquery/blob/6cbe7da9e8ffe369a2e1b17c8456f38d4290d2d5/src/bigquery.ts#L172)?

**Comment by ellasev** [comment]
Yes, amazing!
It looks like it is a new change from 2 weeks ago.

Thank you

**Comment by ellasev** [comment]
Hi Steffany,
I've tried Using this with the GCP Bigquery client library and I'm
afraid it might not be working, or that I don't know how to use it.

This is a code example:

const authClient = new GoogleAuth({ keyFile: './key.json' });
const client = new BigQuery({
projectId: projectIdentifier,
authClient: authClient,
});

The authClient expects a JSONClient.
When I try sending authClient.getClient() (and validating its not of type
Compute), It can't authenticate with the error:
*UNAUTHENTICATED: Request had invalid authentication credentials. Expected
OAuth 2 access token, login cookie or other valid authentication credential*

Can you please help me figure this out? Thank you.
