### ISSUE TITLE
BIgquery connection pool config

### ISSUE THREAD

**Issue by rohitguptap** [googleapis/nodejs-bigquery#1080]
I'm trying to find details reg connection pool using node js-bigquery client but could not find much info online. 
Could someone share how to configure custom connection pool and also recommendations around this?

**Comment by loferris** [comment]
Hi @rohitguptap, 

The main page that discusses [managing connections](https://cloud.google.com/bigquery/docs/working-with-connections#java) in BQ goes over some of the permissions and basics; however, there aren't examples in NodeJS. The equivalent NodeJS library logic for managing connections is in [the BQ Connection library](https://github.com/googleapis/google-cloud-node/tree/main/packages/google-cloud-bigquery-connection) - you may want to checkout some of the generated samples. The `ConnectionClient` does manage multiple connections. This is where I'd start.
