### ISSUE TITLE
`jobs.IListParams.stateFilter` has wrong type

### ISSUE THREAD

**Issue by isamert** [googleapis/nodejs-bigquery#1089]
`stateFilter` accepts an array (and it's documented that way) but the type definition does not account for this, it only expects a single string.

I am specifically talking about this line: https://github.com/googleapis/nodejs-bigquery/blob/16d2a505400564cb49210d25f52fccfdaef42dd5/src/types.d.ts#L3568

Also here is the documentation that says it accepts an array: https://github.com/googleapis/nodejs-bigquery/blob/701ead4b3611aa31135baa5dfe9f7b7423ad4f2f/src/bigquery.ts#L1710

Right now I can workaround this by passing the array with `as any`.

**Comment by steffnay** [comment]
Thank you for reporting this. I'm looking into where this type discrepancy is originating.
