### ISSUE TITLE
`Job#getQueryResultsStream` fails when passed a `startIndex`

### ISSUE THREAD

**Issue by felix-d** [googleapis/nodejs-bigquery#1099]
#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/bigquery` version: latest

#### Steps to reproduce

  1. Pass `startIndex` to `Job#getQueryResultsStream`
  2. First request to populate the stream is successful and starts at the correct index. 
  3. Second request fails with `When using a page token, you cannot specify an arbitrary startIndex`

It seems this is simply because `startIndex` should be used on the first fetch, and then discarded once page tokens can be used for the next query.

**Comment by steffnay** [comment]
Can you provide the code you're running that produces this error?

**Comment by felix-d** [comment]
Sure!  You can reproduce by simply creating a BigQuery job stream with `startIndex`. It will work for the first request and start at the right `startIndex`,  then throw if there's a second page to be fetched in the result set because the library also forwards `pageToken` in the second request and the server doesn't accept both. 

```typescript
const job = new BigQuery(...).createJob(...);
const stream = job.getQueryResultsStream({ startIndex: 2000 });

for await (const chunk of stream) { // throws on the second page
  // ...
}
```

Since the library forwards the `pageToken` cursor parameter on the second request, `startIndex` becomes obsolete. Therefore, if we use a `pageToken` from a server response, we can simply discard `startIndex`.

**Comment by felix-d** [comment]
Hey @steffnay, any progress on this? We currently have to run a fork and would like to get back on HEAD at some point :)
