### ISSUE TITLE
Types for getDatasets methods missing projectId parameter

### ISSUE THREAD

**Issue by MasterOdin** [googleapis/nodejs-bigquery#1130]
When using TS and passing in a `projectId` to the `getDatasets` or `getDatasetsStream` functions, I get a type error about `projectId` not being found in `GetDatasetsOptions`, however I do get back the datasets for the project I specify. It would be nice for this to be not a TS error. Not sure if there's anything more involved here than adding `projectId?: string` to [`bigquery.datasets.IListParams`](https://github.com/googleapis/nodejs-bigquery/blob/main/src/types.d.ts#L4213)?

#### Environment details

  - OS: macOS 12.4
  - Node.js version: 16.15.0
  - npm version: 8.5.5
  - `@google-cloud/bigquery` version: 6.0.0

#### Steps to reproduce

```typescript
import { BigQuery } from '@google-cloud/bigquery';
const client = new BigQuery(/* credentials */);
const [datasets] = client.getDatasets({ projectId: 'bigquery-public-data' });
```

**Comment by loferris** [comment]
Hi @MasterOdin, the BigQuery client passes its `projectId` with the request object, and calls to the `/dataset` endpoint are appended. There is not a JSON equivalent to a `projectId` in the [`Dataset`](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets) object; therefore, I would not add `projectId?` to the `GetDatasetOptions` type interface. Could you elaborate on why this decoupling doesn't work for your use-case?

**Comment by MasterOdin** [comment]
My use case is that I'm fetching schema information across multiple projects concurrently. I'd like to avoid having to pay a penalty of constructing multiple BQ clients that only differ from each other based on `projectId`. As it turns out, passing `projectId` to `getDatasets` function works perfectly for this, just that it's a type error, as well as that we have to pass `projectId` in subsequent functions as shown in #1133

**Comment by alvarowolfx** [comment]
https://github.com/googleapis/nodejs-bigquery/pull/1230 solves this issue.
