### ISSUE TITLE
API methods use overall connection project instead of object's project

### ISSUE THREAD

**Issue by MasterOdin** [googleapis/nodejs-bigquery#1133]
#### Environment details

  - OS: macOS 12.4
  - Node.js version: Node 16.15
  - npm version: 8.5.5
  - `@google-cloud/bigquery` version: 6.0.0

#### Steps to reproduce

```javascript
import { BigQuery, Dataset, Routine, Table } from '@google-cloud/bigquery';
import fs from 'fs';
import path from 'path';

const credentials = JSON.parse(fs.readFileSync(path.join(__dirname, 'credentials.json'), { encoding: 'utf-8' }));

const conn = new BigQuery({
  credentials,
  projectId: 'foo'
});

(async () => {
  const [datasets] = await conn.getDatasets({ projectId: 'bigquery-public-data' });
  const dataset = datasets[0];
  console.log(dataset);
  const [tables] = await dataset.getTables();
  console.log(tables[0]);
})()
  .then(() => {
    process.exit();
  })
  .catch((err) => {
    console.error(err);
  });
```

This will throw an error when I run `getTables` with message `ApiError: Not found: Dataset foo:austin_311`. To get this to work, I need to pass `projectId` to every method call, be it for fetching tables, routines, metadata, etc. This was surprising to me and coworkers where we had assumed that the methods would use the object's `projectId` versus the overall client. The console log on the dataset gives me:
```
Dataset {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  metadata: {
    kind: 'bigquery#dataset',
    id: 'bigquery-public-data:austin_311',
    datasetReference: { datasetId: 'austin_311', projectId: 'bigquery-public-data' },
    location: 'US'
  },
  baseUrl: '/datasets',
  parent: BigQuery {
    baseUrl: 'https://bigquery.googleapis.com/bigquery/v2',
    apiEndpoint: 'https://bigquery.googleapis.com',
    timeout: undefined,
    globalInterceptors: [],
    interceptors: [ [Object] ],
    packageJson: {
      name: '@google-cloud/bigquery',
      description: 'Google BigQuery Client Library for Node.js',
      version: '6.0.0',
      license: 'Apache-2.0',
      author: 'Google LLC',
      engines: [Object],
      repository: 'googleapis/nodejs-bigquery',
      main: './build/src/index.js',
      types: './build/src/index.d.ts',
      files: [Array],
      keywords: [Array],
      scripts: [Object],
      dependencies: [Object],
      devDependencies: [Object]
    },
    projectId: 'foo',
    projectIdRequired: true,
    providedUserAgent: undefined,
    makeAuthenticatedRequest: [Function: makeAuthenticatedRequest] {
      getCredentials: [Function: bound getCredentials],
      authClient: [GoogleAuth]
    },
    authClient: GoogleAuth {
      checkIsGCE: undefined,
      jsonContent: [Object],
      cachedCredential: [JWT],
      _cachedProjectId: 'sql-app-146706',
      keyFilename: undefined,
      scopes: [Array],
      clientOptions: undefined
    },
    getCredentials: [Function: bound getCredentials],
    location: undefined,
    createQueryStream: [Function (anonymous)],
    getDatasetsStream: [Function (anonymous)],
    getJobsStream: [Function (anonymous)]
  },
  id: 'austin_311',
  createMethod: [Function: createMethod],
  methods: {
    create: true,
    exists: true,
    get: true,
    getMetadata: true,
    setMetadata: true
  },
  interceptors: [ { request: [Function: request] } ],
  pollIntervalMs: undefined,
  projectId: undefined,
  location: 'US',
  bigQuery: BigQuery {
    baseUrl: 'https://bigquery.googleapis.com/bigquery/v2',
    apiEndpoint: 'https://bigquery.googleapis.com',
    timeout: undefined,
    globalInterceptors: [],
    interceptors: [ [Object] ],
    packageJson: {
      name: '@google-cloud/bigquery',
      description: 'Google BigQuery Client Library for Node.js',
      version: '6.0.0',
      license: 'Apache-2.0',
      author: 'Google LLC',
      engines: [Object],
      repository: 'googleapis/nodejs-bigquery',
      main: './build/src/index.js',
      types: './build/src/index.d.ts',
      files: [Array],
      keywords: [Array],
      scripts: [Object],
      dependencies: [Object],
      devDependencies: [Object]
    },
    projectId: 'foo',
    projectIdRequired: true,
    providedUserAgent: undefined,
    makeAuthenticatedRequest: [Function: makeAuthenticatedRequest] {
      getCredentials: [Function: bound getCredentials],
      authClient: [GoogleAuth]
    },
    authClient: GoogleAuth {
      checkIsGCE: undefined,
      jsonContent: [Object],
      cachedCredential: [JWT],
      _cachedProjectId: 'foo',
      keyFilename: undefined,
      scopes: [Array],
      clientOptions: undefined
    },
    getCredentials: [Function: bound getCredentials],
    location: undefined,
    createQueryStream: [Function (anonymous)],
    getDatasetsStream: [Function (anonymous)],
    getJobsStream: [Function (anonymous)]
  },
  getModelsStream: [Function (anonymous)],
  getRoutinesStream: [Function (anonymous)],
  getTablesStream: [Function (anonymous)],
  [Symbol(kCapture)]: false
}
```

So the correct projectId is recorded as part of `dataset.metadata.id` and in `dataset.metadata.datasetReference.projectId`, but I'm guessing that that for the API calls, it uses `dataset.bigQuery.projectId` or something which is different.

**Comment by loferris** [comment]
Hi @MasterOdin - A clarification: You say that you need to pass in the `projectId` but the value you're passing in [`getDataset()`](https://github.com/googleapis/nodejs-bigquery/blob/3bda1dad3c5c27a9bf1443bc4b8ceb0884edbc8c/src/bigquery.ts#L1711) and the value you're highlighting the DatasetReference object are the `datasetId`, not the `projectId`. I'd love some clarity as to where you're having to pass `projectId` as a parameter to client methods. Thanks!

**Comment by MasterOdin** [comment]
I'm not sure you read my code sample correctly? I am very much passing `projectId` to the `getDataset` method in my example:

```
const [datasets] = await conn.getDatasets({ projectId: 'bigquery-public-data' });
```

The problem is that for each dataset that is returned, for any client method I run on that dataset (e.g. `getTables`), it will disregard the `projectId` that's associated with that dataset, rather using the `projectId` I set on my connection object.

For my above example, if I wanted to get all tables for this dataset in a different project than my connection, I would need to do the following:
```
const [datasets] = await conn.getDatasets({ projectId: 'bigquery-public-data' });
const dataset = datasets[0];
const [tables] = await dataset.getTables({ projectId: 'bigquery-public-data' });
```

This is true then for the API methods for the objects in `tables`, and really any client API I can get to from my initial `getDatasets` call.

**Comment by loferris** [comment]
Thanks for following up! I looked into this more and here's my explanation: you can in fact pass in projectId, as you've noted, which then overrides the projectId in the request object for that particular call. Because the code is in NodeJS not TypeScript, this comes up as a type error, but still works. I'm writing a quick sample to test what happens when you create a dataset that points to a different project than the client, which may provide a quick fix.

However, I do think this has the potential to be a smoother process, and I'm going to look into updating the method. I'm changing this from a bug to a feature request, and will combine it with the other issue.

**Comment by MasterOdin** [comment]
For a further example, I've got something like the following in my code (though wrapped better using `Promise.all` for better concurrency):

```js
const projectId = 'bigquery-public-data';
const client = new BigQuery({ credentials, projectId: 'foo' });
const [datasets] = await client.getDatasets({ projectId });
for (const dataset of datasets) {
  const [tables] = await dataset.getTables({ projectId });
  for (const table of tables) {
    await table.getMetadata({ projectId });
    /* do something with table */
  }
}
```

So the initial `getDatasets` call I'd expect to pass in `projectId` as I'm looking to get datasets that's from a `projectId` that's different from the client.

For the subsequent calls to `dataset.getTables` and `table.getMetadata` I was surprised to find that I needed to pass `projectId` in, as my expectation was that `dataset.getTables` would use the `projectId:datasetId` as set in the `dataset.metadata` object, and that `table.getMetadata` would use the `projectId:datasetId:tableId` from `table.metadata` regardless of how it matched up against the client's `projectId`. That was how I originally wrote the above code (omitting `projectId` from all calls after `getDatasets`, but that gave me the error in my original post about a "dataset not found" which was somewhat confusing to debug initially.

From my perspective, `dataset.getTables` has decoupled the `projectId` reference from the dataset itself, and so the call is some mix of properties set on the overall client and the dataset, even though all the info could just come from the dataset object itself.  It's a similar story for the `Table` object.

**Comment by loferris** [comment]
Hi @MasterOdin I agree with your assessment that the current library operates such that the `get[Resource]` calls will default to the BigQuery client's projectId unless a different one is passed in with options for dataset, table, etc.

A fairly straightforward way people have handled this is authenticating with a service account that has permissions on more than one project. If this is passed into the client as [a credential object](https://cloud.google.com/bigquery/docs/use-service-accounts), methods in the client instance should be able to access what the service account can access.

This is less relevant in the case of multitenancy with externally hosted data. In that case there are [other approaches ](https://cloud.google.com/bigquery/docs/best-practices-for-multi-tenant-workloads-on-bigquery)through GCP to help coordinate access and data isolation (particularly federated workloads). If you use Dataflow and are open to Typescript, you can take advantage of the BigQuery I/O Connector in the Apache Beam [Typescript SDK](https://github.com/apache/beam/tree/master/sdks/typescript/src/apache_beam/io). We have a [guide for Java](https://cloud.google.com/dataflow/docs/guides/write-to-bigquery), but not for Node.

If that is more your use-case, I'd like to know if about blockers using that TypeScript BQ I/O connector. There are some ways to optimize I/O experience in our own SDK (and we've done this in Java, Go, etc), but so far we haven't had many requests for the same in NodeJS

**Comment by MasterOdin** [comment]
> A fairly straightforward way people have handled this is authenticating with a service account that has permissions on more than one project. If this is passed into the client as [a credential object](https://cloud.google.com/bigquery/docs/use-service-accounts), methods in the client instance should be able to access what the service account can access.

We have a setup already that allows us to select stuff from other projects, and is not really related to this issue? The issue remains that fetching schema objects of a dataset from a project that is different from the one used in the client constructor requires passing a `projectId`, as the get methods ignore the project of the dataset, even though I'm call functions off that dataset, which is what's confusing.

> This is less relevant in the case of multitenancy with externally hosted data. In that case there are [other approaches ](https://cloud.google.com/bigquery/docs/best-practices-for-multi-tenant-workloads-on-bigquery)through GCP to help coordinate access and data isolation (particularly federated workloads). If you use Dataflow and are open to Typescript, you can take advantage of the BigQuery I/O Connector in the Apache Beam [Typescript SDK](https://github.com/apache/beam/tree/master/sdks/typescript/src/apache_beam/io?rgh-link-date=2023-09-18T23%3A16%3A42Z). We have a [guide for Java](https://cloud.google.com/dataflow/docs/guides/write-to-bigquery), but not for Node.
>
> If that is more your use-case, I'd like to know if about blockers using that TypeScript BQ I/O connector. There are some ways to optimize I/O experience in our own SDK (and we've done this in Java, Go, etc), but so far we haven't had many requests for the same in NodeJS

I'm not sure how this is relevant, unless your saying that this SDK will always have this bug and that I'd be better off finding an alternative library to fit my needs.

**Comment by loferris** [comment]
> > A fairly straightforward way people have handled this is authenticating with a service account that has permissions on more than one project. If this is passed into the client as [a credential object](https://cloud.google.com/bigquery/docs/use-service-accounts), methods in the client instance should be able to access what the service account can access.
> 
> We have a setup already that allows us to select stuff from other projects, and is not really related to this issue? The issue remains that fetching schema objects of a dataset from a project that is different from the one used in the client constructor requires passing a `projectId`, as the get methods ignore the project of the dataset, even though I'm call functions off that dataset, which is what's confusing.
> 
> > This is less relevant in the case of multitenancy with externally hosted data. In that case there are [other approaches ](https://cloud.google.com/bigquery/docs/best-practices-for-multi-tenant-workloads-on-bigquery)through GCP to help coordinate access and data isolation (particularly federated workloads). If you use Dataflow and are open to Typescript, you can take advantage of the BigQuery I/O Connector in the Apache Beam [Typescript SDK](https://github.com/apache/beam/tree/master/sdks/typescript/src/apache_beam/io?rgh-link-date=2023-09-18T23%3A16%3A42Z). We have a [guide for Java](https://cloud.google.com/dataflow/docs/guides/write-to-bigquery), but not for Node.
> > If that is more your use-case, I'd like to know if about blockers using that TypeScript BQ I/O connector. There are some ways to optimize I/O experience in our own SDK (and we've done this in Java, Go, etc), but so far we haven't had many requests for the same in NodeJS
> 
> I'm not sure how this is relevant, unless your saying that this SDK will always have this bug and that I'd be better off finding an alternative library to fit my needs.

Thanks for getting back to me - sorry for the misunderstanding! I definitely think this behavior should be addressed, and I appreciate the clarification. I'll be looking into this feature request further to see what the timeline might be for a fix.
