### ISSUE TITLE
Exporting Null Values from BigQuery using Nodejs

### ISSUE THREAD

**Issue by mayanksharma1202** [googleapis/nodejs-bigquery#1134]
Hi Team,

While using exporting bq data to json file using nodejs  I am unable to get null values from bq in json file. All fields whose values are null does get exported.

I am using this link for code -https://cloud.google.com/bigquery/docs/exporting-data#exporting_table_data

Is it possible to get this feature with enable and disable option for extracting null values?

There are many systems which are not able to handle missing key:value while importing using json format.

It will really help!!

**Comment by alvarowolfx** [comment]
@mayanksharma1202 that's a limitation on the BigQuery backend size. nothing that we can do to improve that on the client library side.
