### ISSUE TITLE
Authenticate using an `access_token`

### ISSUE THREAD

**Issue by varun-dc** [googleapis/nodejs-bigquery#1147]
I'm trying to use an `access_token` which I get from the `OAuth2Client` (google-auth-library). But I'm not seeing any way to initializing or providing `BigQuery` with this token.

There's a few older issues discussing `access_token`s but in the current version of the library I'm not seeing any way of achieving this. Was this feature removed? Can we add it back?

The older issues that mention `access_token`:
- https://github.com/googleapis/nodejs-bigquery/issues/68
- https://github.com/googleapis/nodejs-common/issues/11

If I can be of any more help or you need any additional details, let me know.

**Comment by danielbankhead** [comment]
Related/dependency: https://github.com/googleapis/google-auth-library-nodejs/issues/677

**Comment by alvarowolfx** [comment]
This is now supported by google-auth-library-nodejs v9.1.0 per https://github.com/googleapis/google-auth-library-nodejs/pull/1652

**Comment by arno-fukuda** [comment]
can someone provide a code snippet of how this should work now for BigQuery client?

**Comment by alvarowolfx** [comment]
@arno-fukuda you can create a `OAuth2Client` passing the `access_token`, which is now possible on the `google-auth-library-nodejs` v9.1.0 per https://github.com/googleapis/google-auth-library-nodejs/pull/1652. That `OAuth2Client` can be passed when creating a `BigQuery` client with the `authClient` parameter.

Here an example:
```
const {OAuth2Client} = require('google-auth-library');
const {BigQuery} = require('@google-cloud/bigquery');

const authClient = new OAuth2Client({
  credentials: {
    access_token: 'YOUR_ACCESS_TOKEN'
  }
});
const bigqueryClient = new BigQuery({
  authClient,
});
```

**Comment by arno-fukuda** [comment]
@alvarowolfx , thank you for clarifying!

That definitely works.

The confusion arose in belief we could now use the `access_token` directly with `BigQuery` without having to initialize a new `authClient`.

**Comment by aliciazavala** [comment]
@alvarowolfx  Hello, I'm following this auth flow, but I keep getting this error `User does not have bigquery.jobs.create permission in project`, but I'm using the access_token,  what could be causing this?
