### ISSUE TITLE
Set GoggleApplicationsCredentials without using a file path

### ISSUE THREAD

**Issue by Ignastyyy** [googleapis/nodejs-bigquery#1175]
I have a node.js document running on my local computer doing exactly what I need using  the google-cloud/bigquery package following [google's documentation](https://cloud.google.com/bigquery/docs/quickstarts/quickstart-client-libraries). 

However, I am doing a mobile app build in a expo managed project is this compatible?  I am struggeling to add the JSON file containg the credentials of the google applicaction credentials withous using the powershell command wirtten down on the google documentation. 

Does anybody know how to set the environment with out using the file path on the command? 
Thank you very much

**Comment by loferris** [comment]
Hi @Ignastyyy, when attempting to authenticate, does using the default app credentials method not work as well? Here's a page that links to the two options for using service accounts in BQ: [https://cloud.google.com/bigquery/docs/authentication](Intro to authentication). Using the default app credentials method is the more current, preferred method.
[https://cloud.google.com/docs/authentication/provide-credentials-adc](Setting up App Default Credentials (ADC))
[https://cloud.google.com/docs/authentication/client-libraries](Authenticating with ADC via client libraries)
