### ISSUE TITLE
BigQuery results empty on serverless environment

### ISSUE THREAD

**Issue by sakarui** [googleapis/nodejs-bigquery#1177]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-bigquery/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Ubuntu 22.04
  - Node.js version: 16
  - npm version: 9.2.0
  - `@google-cloud/bigquery` version: 6.0.3

#### Steps to reproduce

Below is part of code
```
import { BigQuery } from '@google-cloud/bigquery';

const BQ = new BigQuery({projectId: process.env.PROJECT_ID});

const [job] = await BQ.createQueryJob({
    query,
    location: 'asia-northeast1'
});
let jobResult = await job.getQueryResults();
console.log(jobResult);
```
It shows `[ [ row data, ... ] ]` in local machine
However, in cloud function environment, it shows `[ [ ] ]`
There is no error occurs, just return empty result.

  1. Write nodejs cloud pub-sub triggered function with querying data from bigQuery
  2. In local machine, it returns data properly. However, it returns empty data on cloud function environment

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sakarui** [comment]
@loferris Please refer this report I written detailed information on IssueTracker.
https://issuetracker.google.com/issues/265062900

**Comment by alvarowolfx** [comment]
Following thread on this issue, sounds like it was not possible to reproduce the issue: https://issuetracker.google.com/issues/265334763
