### ISSUE TITLE
createLoadJob - Write_Truncate

### ISSUE THREAD

**Issue by ashishtilara** [googleapis/nodejs-bigquery#118]
Hi,

How do I achieve following in nodejs sdk

```
bq --location=[LOCATION] load --replace [DATASET].[TABLE] [PATH_TO_SOURCE] [SCHEMA]
```
Is filepath option allowed in `createJob(configuration.load.sourceUri[])`?
#### Environment details

  - OS: MacOS 10.12.6
  - Node.js version: 10.0.0
  - npm version: 6.1.0
  - `@google-cloud/bigquery` version: 1.3.0

I cannot find any relevant documentation for this.

**Comment by stephenplusplus** [comment]
Sorry in advance that I'm about to throw a bunch of links at you, but I think these are what you're looking for. If not, please let me know!

Here are the method docs: https://cloud.google.com/nodejs/docs/reference/bigquery/1.3.x/Table#load. The `table.load` method accepts the raw `configuration.load` format specified here: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load

Here's a sample that shows loading from a local file: https://cloud.google.com/bigquery/docs/loading-data-local#loading_data_from_a_local_data_source_using_the_api

**Comment by ashishtilara** [comment]
Thank you @stephenplusplus , does sourceUris accept local files or does it need to be in the cloud store?

My use case is, reload the table data from local csv with 
```
'createDisposition': 'CREATE_IF_NEEDED',
'writeDisposition': 'WRITE_TRUNCATE',
```

Using local file path in `sourceUris` throws `Source URI must be a Google Cloud Storage location: /tmp/data.csv`

**Comment by tswast** [comment]
The final link has an example of loading a local file. https://cloud.google.com/bigquery/docs/loading-data-local#bigquery-import-file-nodejs

```
// Imports the Google Cloud client library
const BigQuery = require('@google-cloud/bigquery');

/**
 * TODO(developer): Uncomment the following lines before running the sample.
 */
// const projectId = "your-project-id";
// const filename = "/path/to/file.csv";
// const datasetId = "my_dataset";
// const tableId = "my_table";

// Creates a client
const bigquery = new BigQuery({
  projectId: projectId,
});

// Loads data from a local file into the table
bigquery
  .dataset(datasetId)
  .table(tableId)
  .load(filename)
  .then(results => {
    const job = results[0];

    // load() waits for the job to finish
    assert.equal(job.status.state, 'DONE');
    console.log(`Job ${job.id} completed.`);

    // Check the job's status for errors
    const errors = job.status.errors;
    if (errors && errors.length > 0) {
      throw errors;
    }
  })
  .catch(err => {
    console.error('ERROR:', err);
  });
```

Instead of just a filename, you'll also want to pass in a "metadata" parameter to the load method https://cloud.google.com/nodejs/docs/reference/bigquery/1.3.x/Table#load

**Comment by ashishtilara** [comment]
@tswast I did checked that example but the example doesn't show how to pass in 

```
'createDisposition': 'CREATE_IF_NEEDED',
'writeDisposition': 'WRITE_TRUNCATE',
```

**Comment by tswast** [comment]
The Parquet sample shows how to pass in a metadata object to `load()`.

https://github.com/googleapis/nodejs-bigquery/blob/c40d2770ddd043641a53a6f45bb264bc250dd52c/samples/tables.js#L244-L307

**Comment by callmehiphop** [comment]
Going to close this out since there hasn't been any activity in quite some time and I believe the original question has been answered. Please let me know if this is incorrect and I'll happily re-open!
