### ISSUE TITLE
What does <REDACTED> means.

### ISSUE THREAD

**Issue by shubhamraka08** [googleapis/nodejs-bigquery#1182]
When I am trying to perform a select query from cloud functions without passing any credentials while initializing BigQuey I get the results. But in Big query Dashboard. I see REDACTED and when I click on that it shows an invalid job id so I am not sure why this is happening and what it actually means
Attaching
<img width="1328" alt="Screenshot 2023-02-03 at 3 20 52 PM" src="https://user-images.githubusercontent.com/36004142/216569471-59082d40-ac7b-4ff6-bfad-b0b2ab898a64.png">
 screenshots for a better understanding

**Comment by meredithslota** [comment]
https://cloud.google.com/bigquery/docs/managing-jobs#required_permissions_2 describes this as WAI: 

To list the jobs in a project, you need the `bigquery.jobs.list` IAM permission. The `bigquery.jobs.list` permission lets you list all the jobs in a project. However, the details are redacted for jobs submitted by the other users. You can see full details only for jobs that you create.
