### ISSUE TITLE
Big Query initialization using project ID and options.

### ISSUE THREAD

**Issue by tyrone-statsig** [googleapis/nodejs-bigquery#1195]
Hello!

I'm setting up. a BigQuery client using the docs I found here 
https://github.com/googleapis/nodejs-bigquery/blame/6438df629e9adb707338bd53959c7c10e0ae2936/samples/clientJSONCredentials.js#L23

and https://cloud.google.com/bigquery/docs/authentication/service-account-file#node.js.

![image](https://user-images.githubusercontent.com/114100859/225788976-812cb93b-c6ff-4c7e-9a67-e9e1e91bebb3.png)

I've had a docker file run a npm build command that builds the following code 
![image](https://user-images.githubusercontent.com/114100859/225789296-e84083ac-6ede-43dc-884e-56bb6320bba2.png).

I get a compile error about BigQueryOptions not having a projectId parameter. I'm confused because the docs for  BigQueryOptions https://cloud.google.com/nodejs/docs/reference/bigquery/latest/bigquery/bigqueryoptions don't support projectId but the links above set it up in a way that does provide a projectId?

If there's any clarification on this, it'd be much appreciated! :) thank you!

**Comment by alvarowolfx** [comment]
Hey @tyrone-statsig, can you give more information on which version of the package are you using and facing issues ? I tested here and the attribute exists to pass `projectId` as a parameter to the client. This can be tracked here:

* `BigQueryOptions extends GoogleAuthOptions`: https://github.com/googleapis/nodejs-bigquery/blob/7f413344ef10b23d487fbb05bf16965c7973034d/src/bigquery.ts#L187
* `export {GoogleAuthOptions} from 'google-auth-library'`: https://github.com/googleapis/nodejs-common/blob/89890df3d8e7fb0b48548b85f4b46188ef4993c4/src/index.ts#L15
* `projectId` as part of `GoogleAuthOptions`: https://github.com/googleapis/google-auth-library-nodejs/blob/070ec96b78dc26791bacb452ebef13d0a5ae6b18/src/auth/googleauth.ts#L123

**Comment by alvarowolfx** [comment]
Closing as was not possible to reproduce here. Feel free to reopen if the issue persist.
