### ISSUE TITLE
Add `JWTInput` as a valid type of the options for `BigQuery` constructor

### ISSUE THREAD

**Issue by IvanaGyro** [googleapis/nodejs-bigquery#1199]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
client library

2) Did someone already solve this?
No

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Windows WSL (Ubuntu 22.04)
  - Node.js version: 18.15.0
  - npm version: yarn v1.22.19
  - `@google-cloud/bigquery` version: 6.2.0

#### Steps to reproduce

In the example of user auth, [an object passed to BigQuery's constructor is not defined](https://github.com/googleapis/nodejs-bigquery/blob/71dbed2140893677f7af254f5a7713a7f50bae92/samples/auth-user-sample/authUserFlow.js#L92-L97) in the type definition of this repository. I found there is [a similar type `JWTInput` defined in google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs/blob/f4d933579cb5b9e50adf6e679a73cc78388ad8f8/src/auth/credentials.ts#L69-L79). Can `JWTInput` be added as a member of  [`BigQueryOptions`](https://github.com/googleapis/nodejs-bigquery/blob/71dbed2140893677f7af254f5a7713a7f50bae92/src/bigquery.ts#L187) to make the logic implementation consistent with the type definition?

**Comment by alvarowolfx** [comment]
hey @IvanaGyro, thanks for the report. The `BigQueryOptions` already extends from `GoogleAuthOptions`([ref](https://github.com/googleapis/nodejs-bigquery/blob/71dbed2140893677f7af254f5a7713a7f50bae92/src/bigquery.ts#L187)), which contains the `credentials` attribute of type `JWTInput | ExternalAccountClientOptions` ([ref](https://github.com/googleapis/google-auth-library-nodejs/blob/595979015b0a49b02a3e9dd607ff7f3ca4d5aeff/src/auth/googleauth.ts#L112), so you can use `JWTInput` that way. Also if you want to use `accessTokens` directly, you can use like this:

```
const {OAuth2Client} = require('google-auth-library');
const {BigQuery} = require('@google-cloud/bigquery');

const authClient = new OAuth2Client({
  credentials: {
    access_token: 'YOUR_ACCESS_TOKEN'
  }
});
const bigqueryClient = new BigQuery({
  authClient,
});
```
