### ISSUE TITLE
Consideration of removing an unnecessary dependency.

### ISSUE THREAD

**Issue by SandZn** [googleapis/nodejs-bigquery#1200]
Hi, 

I'm doing research on finding unnecessary dependencies in NodeJs packages. I found that one dependency (readable-stream) is not used in your package. So I modified the package.json file to remove the "readable-stream" dependency and I ran your tests. The result showed that all tests passed, and the test coverage did not change. Would you consider removing this dependency from your package, so that developers do not need to install them when they use your package?

**Comment by meredithslota** [comment]
Hi @SandZn — thanks for filing this! We will look into it.

**Comment by alvarowolfx** [comment]
hey @SandZn thanks for the report, I have opened PR #1213 to remove it and replace it's usage on tests by the native `stream` package.

**Comment by meredithslota** [comment]
@alvarowolfx Just for context, this was added in https://github.com/googleapis/nodejs-bigquery/pull/997
