### ISSUE TITLE
Typescript extending ServiceObject doesn't pass T causing service object methods to return untyped.

### ISSUE THREAD

**Issue by kitsunde** [googleapis/nodejs-bigquery#1206]
Various places that extend ServiceObject https://github.com/googleapis/nodejs-bigquery/blob/main/src/table.ts#L218 does this:

```ts
class Table extends ServiceObject {}
```

It should be

```ts
class Table extends ServiceObject<Table> {}
```

Because right now `dataset.table('foo').get()` isn't typed.

Typescript example of the issue: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMrQG7CQeQEYBWECYAPACrIC8ycIAngHzIDeAUMp8gOYRgAUASgBcycmwC+AbjZtQkWIhTk4eADYoIAD0ggAJgGc0mbBHxESraXPDR4SZADFgWiHpXrNOiPqPooWLiExGTOru6qGsws1mwIAPYgBmDIMPHx1Fa0Rh4aMmnxAHS8YBzIAPTlyAB6APyyCUkpeHBQmTHZTi5uuRAyLVDFfGWVNfVAA

**Comment by loferris** [comment]
Hi @kitsunde, I'm re-labeling this as a feature request. Although I agree we should have stricter typing on `.get()` methods in this library (and thanks so much for catching that!), introducing the direct fix could possibly create breaking changes, and would have to wait for a major version release. Let us know if you have some specific use-cases you're wanting to cover with the solution.
