### ISSUE TITLE
"There are no column descriptions provided for table" when using autodetect, works fine when using GCP Web UI

### ISSUE THREAD

**Issue by andydeforest** [googleapis/nodejs-bigquery#1216]
#### Environment details

  - OS: MacOS Ventura
  - Node.js version: 14.21.3
  - npm version: 6.14.18
  - `@google-cloud/bigquery` version: 6.2.0

Hello,
I am currently working on a script that loads three CSV files into BigQuery. The function executes as such:
```javascript
  async loadCsvFile(
    file: string,
    tableName: string
  ): Promise<void> {
    const options: JobLoadMetadata = {
      sourceFormat: 'CSV',
      skipLeadingRows: 1,
      autodetect: true,
      writeDisposition: 'WRITE_TRUNCATE',
      location: 'US',
    };

    try {
      const table: Table = this.dataset.table(tableName);
      await table.load(file, options);
    } catch (err) {
      console.log(err);
      throw new Error('Could not load data into BigQuery');
    }
  }
```
Two of the CSV files work fine. The third CSV file produces the following error:
```json
    {
      reason: 'invalidQuery',
      location: 'query',
      message: 'There are no column descriptions provided for table Users_0219c66f_07e1_4847_a85c_2604972d3546_source'
    }
```
Initially, I thought it might be a problem with the CSV format. However, when I take the same troublesome CSV file and upload it on the GCP BigQuery Web UI, it loads fine and the schema is detected without issue. Any idea what the issue may be? Thanks!

**Comment by alvarowolfx** [comment]
@andydeforest do you have an example of such csv file that is causing errors ? I tried with some quick samples here and all worked the same way with the client library and Web UI.

**Comment by alvarowolfx** [comment]
Closing was not possible to reproduce. Feel free to reopen if the problem persists.
