### ISSUE TITLE
Are parameters supported for the `ORDER BY` clause?

### ISSUE THREAD

**Issue by gtupak** [googleapis/nodejs-bigquery#1226]
I have an app that contains a table which allows sorting. Thus, I am deciding the sorting column and order programmatically. To illustrate this, I tried the code below and it looks like the `ORDER BY` expression is simply ignored. It doesn't throw an error either.

```js
async function queryParamsNamed() {
    // The SQL query to run
    const sqlQuery = `SELECT word, word_count
          FROM \`bigquery-public-data.samples.shakespeare\`
          WHERE corpus = @corpus
          AND word_count >= @min_word_count
          ORDER BY @sort`;

    const options = {
      query: sqlQuery,
      // Location must match that of the dataset(s) referenced in the query.
      location: 'US',
      params: {corpus: 'romeoandjuliet', min_word_count: 250, sort: 'word_count DESC'},
    };

    // Run the query
    const [rows] = await bigquery.query(options);

    console.log('Rows:');
    rows.forEach(row => console.log(row));
  }
  // [END bigquery_query_params_named]
  queryParamsNamed();
}
```

**Comment by kunallimaye** [comment]
This doesn't seem like a JS library issue, the API doesn't support this either.  The order by parameter is just ignored.

```bash
export PROJECT_ID=[##YOU_PROJECT_ID##]
curl --request POST \
  'https://bigquery.googleapis.com/bigquery/v2/projects/${PROJECT_ID}/queries?key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{"query":"SELECT word, word_count\nFROM `bigquery-public-data.samples.shakespeare`\nWHERE corpus = @corpus\nAND word_count >= @min_word_count\nORDER BY @or_by;","queryParameters":[{"parameterType":{"type":"STRING"},"parameterValue":{"value":"romeoandjuliet"},"name":"corpus"},{"parameterType":{"type":"INT64"},"parameterValue":{"value":"250"},"name":"min_word_count"},{"name":"or_by","parameterType":{"type":"STRING"},"parameterValue":{"value":"word_count DESC"}}],"useLegacySql":false,"parameterMode":"NAMED"}' \
  --compressed

```

**Comment by gtupak** [comment]
Hi, are there any updates on this?

**Comment by alvarowolfx** [comment]
That's a limitation of the GoogleSQL ( the SQL dialect that BigQuery uses ). And it seems to be a limitation of most SQL engines. Out of curiosity I tested here with PostgreSQL and found that is also not supported, and doing some research it seems like is the same with other databases.

My recommendation would be to do a string concat just for the order by parameter. To avoid potential SQL injection issues, would be good to make sure that it only accepts two parameters, a `field` and a `sort` (only `DESC|ASC`).

I'll close as this is not a Node SDK issue.

**Comment by gtupak** [comment]
I see, thank you for checking in. It would be ideal to support this feature though!
