### ISSUE TITLE
Max Query Time, Query Retry, Job Exists?

### ISSUE THREAD

**Issue by rwmia** [googleapis/nodejs-bigquery#1249]
Getting a consistent error: ErrorClass [ApiError]: Already Exists: Job

It appears that a query lasting longer than 2 minutes causes a timeout, which then causes a retry, which then causes duplicate job. I have tried setting timeoutMs with no luck.

```
let options = {
      timeoutMs: 240000,
      maxRetries: 0,
      autoRetry: false
    };
    bigquery.query(query, options, function(err, rows) {
      if (err) {
        callback(err);
      } else {
        callback(null, rows);
      }
    });
```

Is there a hard time limit on query time which causes a retry?

**Comment by loferris** [comment]
Hi @rwmia The default timeout overall is 10,000 ms, but requests can start to timeout after 200,000 ms (see `timeoutMs` in the [`jobs.query` reference page](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query)). If there's some fine-tuning of the retry logic you'd like to see, feel free to open a feature request and we'll take a look!
