### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'insertErrors') thrown when processing errors

### ISSUE THREAD

**Issue by nathantalewis** [googleapis/nodejs-bigquery#1272]
1) Is this a client library issue or a product issue?
A client library issue.

2) Did someone already solve this?
No.

3) Do you have a support contract?
No.

#### Environment details

  - OS: Ubuntu
  - Node.js version: 18.17.1
  - npm version: 9.6.7
  - `@google-cloud/bigquery` version: 7.2.0

#### Steps to reproduce

  1. Use `createInputStream` to create an input stream.
  2. Send rows through the stream until an `TypeError: Cannot read properties of undefined (reading 'insertErrors')` occurs.

**Comment by alvarowolfx** [comment]
Do you have some scenario that this happens ? Would be nice to add some tests to the  PR #1273

**Comment by nathantalewis** [comment]
I didn't dig into it too much to be honest. It seems to happen the most when we have multiple services all inserting to the same table at the same time and is hard to reproduce from just a single machine.

**Comment by nathantalewis** [comment]
Here is the stack trace that we see in the logs:
```
TypeError: Cannot read properties of undefined (reading 'insertErrors')
    at /usr/src/app/node_modules/@google-cloud/bigquery/build/src/rowQueue.js:121:43
    at onAuthenticated (/usr/src/app/node_modules/@google-cloud/common/build/src/util.js:396:25)
    at prepareRequest (/usr/src/app/node_modules/@google-cloud/common/build/src/util.js:452:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```

**Comment by nathantalewis** [comment]
I also see: `request to https://www.googleapis.com/oauth2/v4/token failed, reason: Client network socket disconnected before secure TLS connection was established` on nearby lines, so maybe that's the root error that fails to provide a `resp` object as expected?
