### ISSUE TITLE
PartialFailureError loading from storage lib instead of this lib

### ISSUE THREAD

**Issue by stefandoorn** [googleapis/nodejs-bigquery#1321]
`PartialFailureError` can only be loaded from the 'Storage' package, but the BigQuery API can use it in case of an error. When we want to check for that (see code) below, we also need to add the `@google-cloud/storage` dependency to our project, instead of only the `@google-cloud/bigquery` package.

The BigQuery package does use this error though. I know we can simply check against the string in the error, but this provides us better typing on what's included in the Error itself. 

#### Environment details

  - OS: Mac
  - Node.js version: 20
  - npm version: 10.1
  - `@google-cloud/bigquery` version: v7

#### Steps to reproduce

We have this logic in one of our apps:

```typescript
import {PartialFailureError} from '@google-cloud/storage/build/cjs/src/nodejs-common/util';

function isPartialFailureError(error: unknown): error is PartialFailureError {
    return error instanceof Error && 'PartialFailureError' === error.name;
}

    async send(
        datasetName: string,
        tableName: string,
        row: object,
    ): Promise<void> {
        const table = this.client.dataset(datasetName).table(tableName);

        try {
            await table.insert([row]);
        } catch (error: unknown) {
            if (isPartialFailureError(error)) {
                for (const nestedError of error?.errors || []) {
                    this.logger.error(error, {
                        nestedError: {
                            reason: nestedError.reason,
                            message: nestedError.message,
                        },
                    });
                }
            }

            throw error;
        }
```

I did expect `PartialFailureError` to be either coming from the `common` package directly (which is loaded as a dependency of this lib) or from this lib directly, because BQ can actually use it.

**Comment by alvarowolfx** [comment]
Hey @stefandoorn thanks for the report. 

You can import the `PartialFailureError` from `@google-cloud/common` or from `@google-cloud/bigquery`. We re-export the `common` package from this BigQuery library as can be seen [here](https://github.com/googleapis/nodejs-bigquery/blob/e9f133bec0c1420396ff25d30baf1fba74e1ab04/src/bigquery.ts#L50), [here](https://github.com/googleapis/nodejs-bigquery/blob/e9f133bec0c1420396ff25d30baf1fba74e1ab04/src/bigquery.ts#L24) and [here](https://github.com/googleapis/nodejs-bigquery/blob/e9f133bec0c1420396ff25d30baf1fba74e1ab04/src/index.ts#L28).

```
const {util} = require('@google-cloud/common');
const {PartialFailureError}  = util;
```
or
```
const {BigQuery, common} = require('@google-cloud/bigquery');
const {PartialFailureError} = common.util;
```

I've tested importing the error from both packages and type checking works.

**Comment by stefandoorn** [comment]
Ahhh - it seems that from `7.3` this is available (I think)! That's nice - thanks!
