### ISSUE TITLE
Table extract to gcs and keep the kmsKeyName

### ISSUE THREAD

**Issue by gustavosizilio** [googleapis/nodejs-bigquery#1325]
Hello, I am using the extract function to export a table from Google BigQuery to a CSV file in Google Cloud Storage. For that, the lib requires me to create a File reference just as you can see In my example below. It works just fine, the extraction and the file creation are just like expected. However, the file reference we pass in contains a kms configuration that is not applied. 

In other words, we make sure to setup the kmsKeyName before but when we retrieve the resulting file this is not applied anymore. Does anyone can give me a tip regarding this?

```javascript
async exportExportTableToCloudStorage(
    companyTenantId: string,
    dataExportReportId: number,
    file: File,
  ) {
    await this.getClientInstance()
      .dataset(companyTenantId)
      .table(this.getTmpExportTableName(dataExportReportId))
      .extract(file, {
        destinationFormat: 'CSV',
      });
  }
```

**Comment by alvarowolfx** [comment]
hey @gustavosizilio thanks for the question. I checked here and KMS configuration is not support for Extract jobs, only Query/Copy/Load jobs. The `kmsKeyName` attribute on the `File` interface is used for Load jobs.

References:
* BQ CLI extract doesn't have KMS option: https://cloud.google.com/bigquery/docs/reference/bq-cli-reference#bq_extract
* Extract Job Configuration on the API: https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfigurationextract
