### ISSUE TITLE
DML API to merge statement

### ISSUE THREAD

**Issue by ceifa** [googleapis/nodejs-bigquery#1386]
**Is your feature request related to a problem? Please describe.**

We have the insert API but not the merge or update API

 **Describe the solution you'd like**

A function just like the insert, but to merge

**Comment by alvarowolfx** [comment]
The BigQuery Storage Write API provide a way for doing updates/upsert/merge in a Change Data Capture scenario. You can check the documentation for it here:
* https://cloud.google.com/bigquery/docs/change-data-capture

The BigQuery Storage Write API exists on a separated client from this one - https://github.com/googleapis/nodejs-bigquery-storage. There is not samples yet for doing Change Data Capture, but I'll file an issue to work on that.

Aside from that, there are no plans to add MERGE/UPSERT/UPDATE API on BigQuery, so the only other way of using that is via SQL statements.
