### ISSUE TITLE
Is it possible to create a dataset with cross-region replication option ?

### ISSUE THREAD

**Issue by 3150** [googleapis/nodejs-bigquery#1397]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
  - Create a dataset with cross-region replication
- What code you've already tried
  - Read code around createDataset
- Any error messages you're getting

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi. I know cross region replication is now on Preview stage and I can create a dataset with cross region replication statement like below. Is it possible to create a dataset with cross-region replication by nodejs bq library ? I would like to create a dataset that has cross-region replicated datasets with createDataset API. 
```
ALTER SCHEMA `xxxx`
ADD REPLICA `xxxx`
OPTIONS(location='asia-northeast1');
```

I could not find such option with the code below. 
https://github.com/googleapis/nodejs-bigquery/blob/daa64e87d70828b315f75c3adcccc14f13ced8a2/samples/createDataset.js#L32

[desired example]
```
    const options = {
      location: 'US',
      replications: [
        {region: 'asia-northeast1', datasetName: 'replicated_dataset_jp'}
      ]
    };

    // Create a new dataset
    const [dataset] = await bigquery.createDataset(datasetId, options);
```

**Comment by alvarowolfx** [comment]
@3150 thanks for reaching out. Unfortunately dataset replication is only available through DDL statements and is not on the roadmap to extend the the dataset API with this option for now.

See: https://cloud.google.com/bigquery/docs/data-replication#replicate_a_dataset
