### ISSUE TITLE
How to set GOOGLE_APPLICATION_CREDENTIALS multiple times?

### ISSUE THREAD

**Issue by richzw** [googleapis/nodejs-bigquery#158]
#### Environment details

  - OS: Mac OS
  - Node.js version: v8.9.1
  - npm version: 5.5.1
  - `@google-cloud/bigquery` version: 1.3.0

#### Steps to reproduce

I have two js file worked for two different google cloud account, namely a.js and b.js. And 

```js
// a.js
process.env.GOOGLE_APPLICATION_CREDENTIALS = path.join(curDir, "../../../../a1_secret.json");

console.log(process.env.GOOGLE_APPLICATION_CREDENTIALS);

const BigQuery = require('@google-cloud/bigquery');
```

```js
// b.js
process.env.GOOGLE_APPLICATION_CREDENTIALS = path.join(curDir, "../../../../b1_secret.json");

console.log(process.env.GOOGLE_APPLICATION_CREDENTIALS);

const BigQuery = require('@google-cloud/bigquery');
```

From the output, it seems `process.env.GOOGLE_APPLICATION_CREDENTIALS` is correctly set, and it could run `a.js`, however, it failed to run in `b.js`. 

Is it the correct way to do it? Or am I missing something?

**Comment by stephenplusplus** [comment]
I don't believe environment variables are meant to be set at runtime within the codebase. What you can do instead is:

```js
// a.js
const BigQuery = require('@google-cloud/bigquery')
const bigQuery = new BigQuery({
  keyFilename: path.join(curDir, "../../../../a1_secret.json")
})
```

```js
// b.js
const BigQuery = require('@google-cloud/bigquery')
const bigQuery = new BigQuery({
  keyFilename: path.join(curDir, "../../../../b1_secret.json")
})
```

Let me know if you have any issues with this approach!

**Comment by tswast** [comment]
Thanks @stephenplusplus. This is correct. We have similar recommendations for other languages at https://cloud.google.com/bigquery/docs/authentication/service-account-file

I'll make sure we're tracking to add a Node.js sample to that page.
