### ISSUE TITLE
Docs suggests Table#import(), but the method wasn't implemented

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-bigquery#165]
copying an internally-reported issue here, 

> https://cloud.google.com/nodejs/docs/reference/bigquery/1.0.x/Table
"it is highly recommended that you load data into BigQuery using Table#import instead."
I don't see import() defined anywhere?

Is this a documentation error, or a missing feature?

**Comment by kinwa91** [comment]
cc @stephenplusplus

**Comment by tswast** [comment]
Probably a typo for load https://cloud.google.com/nodejs/docs/reference/bigquery/1.0.x/Table#load

**Comment by kinwa91** [comment]
There's also a reference to import() here: https://cloud.google.com/functions/docs/tutorials/sendgrid#importing_data_into_bigquery

**Comment by kinwa91** [comment]
Thanks I will refresh the docs.
