### ISSUE TITLE
Enable codecov

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigquery#17]
Hey @alexander-fenster, I think there is something left to do to enable codecov: https://codecov.io/gh/googleapis/nodejs-bigquery/settings

![image](https://user-images.githubusercontent.com/723048/32992434-ac13afda-cd18-11e7-8139-0a9043511ea8.png)

It is able to leave a comment on a PR, but it isn't recognized as a required status check during a PR.

**Comment by alexander-fenster** [comment]
It can only be done by @lukesneeringer .

**Comment by alexander-fenster** [comment]
Codecov is enabled for nodejs-bigquery. Closing the issue.
