### ISSUE TITLE
System tests might be deleting all datasets inside our test project

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-bigquery#176]
https://github.com/googleapis/nodejs-bigquery/blob/960d84e3e320685d3766508e6d8a3988c1b6397e/system-test/bigquery.ts#L1672-L1680

There's no reference to `prefix` option to list datasets:
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/list

And we're suspecting it is causing a test dataset in nodejs-dlp to be deleted, causing its nightly to fail: 
https://github.com/googleapis/nodejs-dlp/issues/52#issuecomment-415837211

**Comment by kinwa91** [comment]
filter with label: https://cloud.google.com/bigquery/docs/labeling-datasets#filtering_datasets_using_labels

**Comment by kinwa91** [comment]
Elevating to p0 since it is blocking other repositories from passing system tests and releasing.

**Comment by stephenplusplus** [comment]
P0PR: https://github.com/googleapis/nodejs-bigquery/pull/177/files
