### ISSUE TITLE
FR: Let clients use encodeValue function

### ISSUE THREAD

**Issue by swftvsn** [googleapis/nodejs-bigquery#19]
I'd really like to do this:

```ts
const bq = BigQuery({ projectId: 'prjctd' })
const table = bq.dataset('dtst').table('tbl')
const valueToInsert = {
  insertId: 'myInsertId',
  json: table.encodeValue_(myItem)
}
```

but currently the function is not visible. I can copy it to my project for sure, but it would be nicer to be able to use it.

**Comment by stephenplusplus** [comment]
That makes sense. @callmehiphop what do you think?

**Comment by stephenplusplus** [comment]
Just to dig deeper and make sure I understand the best way to implement this, what is the value of exposing this function? In the example above, we would do the encode internally, wouldn’t we?

**Comment by swftvsn** [comment]
So much time has passed that I honestly don't remember anymore. From my point of view, as nobody else has requested it, this can be closed && I'll reopen if we bump into situation where we still need this. I'll also make sure to document the motivation better next time ;)

**Comment by tswast** [comment]
Related: https://github.com/googleapis/nodejs-bigquery/issues/328 I suggest that we do this conversion automatically (assuming we don't already).

We do want to take into account the table schema in our conversions as originally proposed. One reason is that with numeric data in JavaScript, it can be ambiguous whether we want to write a FLOAT64, INT64, or NUMERIC value to BigQuery.

**Comment by stephenplusplus** [comment]
I think #328 turned out to be a documentation issue:

> The client already does convert the native types recursively and we have a static method for every special type. 
> - https://github.com/googleapis/nodejs-bigquery/issues/328#issuecomment-460446074

I'm going to close this feature request given the limited use cases, but as always, someone can let us know if that was the wrong choice. @swftvsn thanks for the suggestion and if you have any others in the future as you continue to use the library, please feel free to share!
