### ISSUE TITLE
Fix failing system tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-bigquery#209]
The following tests are failing on master:
   ✓ should get a list of datasets (1395ms)
    1) should allow limiting API calls
    ✓ should return a promise (1243ms)
    2) should allow limiting API calls via promises
    3) should allow for manual pagination in promise mode

**Comment by JustinBeckwith** [comment]
👋 @stephenplusplus @callmehiphop would y'all mind taking a look at these failing tests on master?  #227 is a pretty heavy change, and I don't want to make it without knowing the system tests are passing.

**Comment by stephenplusplus** [comment]
They all pass for me. Is this still an issue after #227 merged?

**Comment by JustinBeckwith** [comment]
At some point this got fixed :)
