### ISSUE TITLE
Feature request: Wildcard query matching no tables should not throw an error

### ISSUE THREAD

**Issue by huysamen** [googleapis/nodejs-bigquery#21]
When executing wildcard queries using `REGEXP_MATCH`, and matching no tables, the library currently throws an exception stating that no tables have been matched.  This does not feel correct, as matching no tables are very often a valid use-case.  Just returning no rows feels much more natural.  Or maybe add a parameter that we can pass in to prevent the exception being thrown.

**Comment by stephenplusplus** [comment]
Thanks for reporting. Could you provide a sample query we could use to reproduce?

**Comment by huysamen** [comment]
Assume `[my_dataset]` dataset does exist, but tables `[my_dataset.unknown_table_1]` and `[my_dataset.unknown_table_2]` does not.

```
SELECT  *
FROM    TABLE_QUERY([my_dataset], 'REGEXP_MATCH(table_id, r"^unknown_(table_1|table_2)")')
WHERE   (
          (
            _PARTITIONTIME BETWEEN USEC_TO_TIMESTAMP(NOW() - (7 * 24 * 60 * 60 * 1000 * 1000))
            AND CURRENT_TIMESTAMP()
          )
          OR _PARTITIONTIME IS NULL
        )
```

**Comment by stephenplusplus** [comment]
Thanks. Could you paste the exact error you are getting as well?

**Comment by stephenplusplus** [comment]
@callmehiphop who is a good BigQuery team member to ping about this? It seems we're just returning the error from the API.

**Comment by stephenplusplus** [comment]
cc @tswast

**Comment by tswast** [comment]
The BigQuery API considers this query to be an invalid query.

```
{
 "kind": "bigquery#job",
 "selfLink": "https://www.googleapis.com/bigquery/v2/projects/my-project/jobs/my-job",
 "configuration": {
  "query": {
   "query": "SELECT  *\nFROM    TABLE_QUERY([flower], 'REGEXP_MATCH(table_id, r\"^unknown_(table_1|table_2)\")')\nWHERE   (\n          (\n            _PARTITIONTIME BETWEEN USEC_TO_TIMESTAMP(NOW() - (7 * 24 * 60 * 60 * 1000 * 1000))\n            AND CURRENT_TIMESTAMP()\n          )\n          OR _PARTITIONTIME IS NULL\n        )"
  }
 },
 "status": {
  "state": "DONE",
  "errorResult": {
   "reason": "invalidQuery",
   "location": "query",
...
}
```

There's not much the client library should do about that. I'd recommend filing an issue at issuetracker.google.com if you don't think BigQuery should consider such a query an error. (I don't offer much hope though, as this query is using legacy SQL syntax and no improvements are being made to the legacy SQL engine.)
