### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by welkie** [googleapis/nodejs-bigquery#210]
I notice that the source code in this repo is TypeScript, but when you install the package through NPM, there are no d.ts files. I was wondering if there's a time frame right now for turning on publishing the types so that TypeScript programs can consume this without creating a stub d.ts file declaring the module (and not benefiting from the types).

**Comment by JustinBeckwith** [comment]
Greetings!  We've done the first steps, but there is a LOT of work to do until we can start publishing types.  Until we have `noImplicitAny` enabled, what's there won't do folks much good sadly.  That having been said...  we are accepting PRs if you want to help make the types better!

**Comment by welkie** [comment]
Gotcha, thanks for the update. :)

**Comment by mattwelke** [comment]
Looks like types are being published now: https://unpkg.com/browse/@google-cloud/bigquery/build/src/

```
bigquery.d.ts | 26 kB | text/plain
bigquery.js | 66.9 kB | application/javascript
...
```
