### ISSUE TITLE
BigQuery client running into DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by holgeradam** [googleapis/nodejs-bigquery#214]
Hey there,

I am running into an issue with the BigQuery client for Node.js. I am trying to read a larger number of rows, convert them and store them elsewhere. I tried using query streams both for table (which has a fixed bug missing a release) and job. Both either result in OOM or DEADLINE_EXCEEDED quickly.

Therefore I switched to a paginated query using this: https://cloud.google.com/nodejs/docs/reference/bigquery/1.3.x/Job#getQueryResults

However after a larger six figure number of rows I still ran into this error message:

{\"stack\":\"Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded\\n    at Object.exports.createStatusError (/usr/src/app/node_modules/grpc/src/common.js:87:15)\\n    at Object.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:1188:28)\\n    at InterceptingListener._callNext (/usr/src/app/node_modules/grpc/src/client_interceptors.js:564:42)\\n    at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:614:8)\\n    at callback (/usr/src/app/node_modules/grpc/src/client_interceptors.js:841:24)\",\"message\":\"4 DEADLINE_EXCEEDED: Deadline Exceeded\",\"code\":4,\"metadata\":{\"_internal_repr\":{}},\"details\":\"Deadline Exceeded\"}

So far I have not been able to find a way to set the deadline myself. Is there any way to get around this issue or set the deadline for the BigQuery client?

Thanks!

#### Environment details

  - OS: Debian
  - Node.js version: 9.11.1
  - npm version: 5
  - `@google-cloud/bigquery` version: 1.3.0

#### Steps to reproduce

  1. Select a large enough table with more than a million rows.
  2. Create a job with a simple query resulting in a million rows.
  3. Process the rows with automatic pagination using node to store them in another DB.
  4. Wait for DEADLINE_EXCEEDED.

**Comment by kinwa91** [comment]
@holgeradam please try upgrading to `@google-cloud/bigquery@2.0.5`. The latest release fixed the [issue](https://github.com/googleapis/nodejs-bigquery/pull/121) which might very well caused the OOM issue.

**Comment by stephenplusplus** [comment]
I think we can assume this one is resolved now, but let me know if closing is a mistake.
