### ISSUE TITLE
Allow running load job to a different project ID

### ISSUE THREAD

**Issue by Ohadbasan** [googleapis/nodejs-bigquery#26]
There could be a need to run a load job to a different projectId than the projectId id of the bigQuery client.
the metadata object defines the destinationTable.projectId which should be used in case it's provided,
if it's not provided - the fallback should be the same as today - the projectId of the instantiated bigQuery client.

Thanks!

**Comment by Ohadbasan** [comment]
Opened a PR for this change
https://github.com/googleapis/nodejs-bigquery/pull/27

**Comment by stephenplusplus** [comment]
Thank you for the PR! I believe we have a line in the code that would allow this already:

https://github.com/googleapis/nodejs-bigquery/blob/7230ee2fbe740ae1eea013ddc3e9f941e12399a2/src/table.js#L1726

So, this already works:

```js
table.startImport(file, {
  destinationTable: {
    projectId: 'test-override'
  }
})
```

I tested against your PR, and found that the new test still passes after removing the changes made to `src/table.js`.

**Comment by Ohadbasan** [comment]
Aha.
My bad then, Thank you!

**Comment by stephenplusplus** [comment]
No problem, thanks for taking the time to help!
