### ISSUE TITLE
Bad type definition in method bigquery.query()?

### ISSUE THREAD

**Issue by fjc2112** [googleapis/nodejs-bigquery#275]
#### Environment details

  - OS: Win 10
  - Node.js version: 8.11.2
  - npm version: 5.6
  - `@google-cloud/storage` version: 2.0.1

#### Steps to reproduce

this is the type definition:

query(query: any, options: any, callback?: any): void;

but in examples uses:

query(options: any) <-- and that works fine, but the compiler throw this error:

error TS2554: Expected 2-3 arguments, but got 1.

95             const [data1] = await this.bq.query(options);

**Comment by kinwa91** [comment]
We've added types overload to reflect the correct signature to the `query` method, so it should work now if you pull in the later versions.
