### ISSUE TITLE
Google Auth - error loading default credentials

### ISSUE THREAD

**Issue by davidericardo** [googleapis/nodejs-bigquery#28]
Hello all, 

I'm trying to use this library but with no luck so far.

I have the service account activated:
[root@localhost credentials]# gcloud auth activate-service-account --key-file=/var/www/xxxx/config/credentials/keyfile-default.json
Activated service account credentials for: [123456-compute@developer.gserviceaccount.com]

And when I try to use the functions insertAll or insert I get the following error:
```
ERROR: Error: **Could not load the default credentials**. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at /var/www/xxxx/node_modules/google-auth-library/lib/auth/googleauth.js:316:21
    at /var/www/xxxx/node_modules/google-auth-library/lib/auth/googleauth.js:346:7
    at Request._callback (/var/www/xxxx/node_modules/google-auth-library/lib/transporters.js:70:30)
    at self.callback (/var/www/xxxx/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/var/www/xxxx/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Here are the two code snippets:
```js
// Imports newest Google BigQuery library
    const BigQuery = require('@ google-cloud/bigquery'); 

    // execute the following command
    //export GOOGLE_APPLICATION_CREDENTIALS=/var/www/xxxx/config/credentials/keyfile-default.json
    const bigquery = BigQuery({
        projectId: projectId
    });

    // The project ID to use
    const projectId = "xxxxx-dev";

    // The ID of the dataset of the table into which data should be inserted
    const datasetId = "xxxx";

    // The ID of the table into which data should be inserted
    const tableId = "yyyyy";
    
    bigquery.tabledata.insertAll({
        //auth: oauth2Client,
        'projectId': projectId,
        'datasetId': datasetId,
        'tableId': tableId,
        'resource': {
            "kind": "bigquery#tableDataInsertAllRequest",
            "rows": rows
        }
    }, function(err, result)
    {
        if (err)
        {
            return console.error(err);
        }
        console.log(result);
    });
```

OR 

```js
bigquery
    .dataset(datasetId)
    .table(tableId)
    .insert(rows)
    .then((insertErrors) => {
        console.log('Inserted:');
        rows.forEach((row) => console.log(row));
        if (insertErrors && insertErrors.length > 0)
        {
            console.log('Insert errors:');
            insertErrors.forEach((err) => console.error(err));
        }
    })
    .catch((err) => {
        console.error('ERROR:', err);
    });
```

#### Environment details

  - OS: CentOS 7 - 64Bits
  - Node.js version: 6.11.0
  - npm version: 3.10.10
  - @google-cloud/bigquery version: 0.9.6

#### Steps to reproduce

  1. Try to use the bigquery.tabledata.insertAll function or bigquery.dataset(datasetId).table(tableId).insert(rows) function

Thanks in advance for your help.
Regards,
DR

**Comment by stephenplusplus** [comment]
Our API doesn't have a `bigquery.tabledata` object. Could that be from https://github.com/google/google-api-nodejs-client?

**Comment by davidericardo** [comment]
Hey @stephenplusplus , thanks for you reply. 

I don't believe it's related to that, because as I mentioned I tried with the other code snippet (also mentioned on of your examples), and I'm getting the same issue: "Error: Could not load the default credentials." --> related to the node module: google-auth-library/lib/auth/googleauth.js

**Comment by stephenplusplus** [comment]
Would you mind updating the example from the post with exact reproduction steps for the `@google-cloud/bigquery` library? I see that I can piece it all together from what you have, but when I do, it works for me, so I assume something is being lost in translation.

**Comment by davidericardo** [comment]
BTW, I was able to move on to the next step doing:

"gcloud auth application-default login" via command line and then go to the provided link and paste the verification code shared. 

However, now I'm getting other error: 
`
ERROR: { PartialFailureError: A failure occurred during this request.
    at /var/www/xxxxx/node_modules/@google-cloud/bigquery/src/table.js:1213:13
    at Object.handleResp (/var/www/xxxxx/node_modules/@google-cloud/common/src/util.js:135:3)
    at /var/www/xxxxx/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/var/www/valeo/node_modules/retry-request/index.js:160:7)
    at Request.self.callback (/var/www/xxxxx/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/xxxxx/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/www/xxxxx/node_modules/request/request.js:1091:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
  errors:
   [ { errors: [Object], row: [Object] },
     { errors: [Object], row: [Object] },
     { errors: [Object], row: [Object] } ],
  response:
   { kind: 'bigquery#tableDataInsertAllResponse',
     insertErrors: [ [Object], [Object], [Object] ] },
  message: 'A failure occurred during this request.' }
`

This is indeed related to the insert function.

**Comment by stephenplusplus** [comment]
You can `console.log` the `errors` array from the error you pasted above for more information about the specific failure.

**Comment by davidericardo** [comment]
Error Array Log:

`
{
  "errors": [
    {
      "errors": [
        {
          "message": "no such field.",
          "reason": "invalid"
        }
      ],
      "row": {
        "value1": "2017-12-07",
        "value2": 1511891495,
        "value3": "4.304467"
      }
    },
    {
      "errors": [
        {
          "message": "no such field.",
          "reason": "invalid"
        }
      ],
      "row": {
        "value1": "2017-12-07",
        "value2": 1511891496,
        "value3": "4.304438"
      }
    },
    {
      "errors": [
        {
          "message": "no such field.",
          "reason": "invalid"
        }
      ],
      "row": {
        "value1": "2017-12-07",
        "value2": 1511891497,
        "value3": "4.304414"
      }
    }
  ],
  "response": {
    "kind": "bigquery#tableDataInsertAllResponse",
    "insertErrors": [
      {
        "index": 0,
        "errors": [
          {
            "reason": "invalid",
            "location": "_doc",
            "debugInfo": "",
            "message": "no such field."
          }
        ]
      },
      {
        "index": 1,
        "errors": [
          {
            "reason": "invalid",
            "location": "_doc",
            "debugInfo": "",
            "message": "no such field."
          }
        ]
      },
      {
        "index": 2,
        "errors": [
          {
            "reason": "invalid",
            "location": "_doc",
            "debugInfo": "",
            "message": "no such field."
          }
        ]
      }
    ]
  },
  "message": "A failure occurred during this request."
}
`

**Comment by stephenplusplus** [comment]
This is an issue with the data you are inserting being invalid with the table. Please post this question over on StackOverflow, as there are a wider array of BigQuery experts who can help there (we can fix the client library bugs, but usage questions are best left to the experts :)) Here are some tags that will help connect you: https://stackoverflow.com/questions/tagged/google-cloud-platform%20node.js%20google-bigquery

Please post a link back here when you make the post.

**Comment by davidericardo** [comment]
It's a big weird issue indeed:

BigQuery does not accept a json like this:
`
[{"key1":"value1","key2":"value"}]
`

It cannot have quotes on the keys :S :
`
[{key1:"value1",key2:"value"}]
`

**Comment by davidericardo** [comment]
However at the end, the issue was related to a specific field :S
Thanks for your help.
