### ISSUE TITLE
@google-cloud/storage should be defined as a normal dependency

### ISSUE THREAD

**Issue by qamil** [googleapis/nodejs-bigquery#287]
Version 2.0.2 has an import of the "@google-cloud/storage" package inside `table.ts`. However it's defined as a `devDependency` instead of a `dependency` in `package.json`. This forces me to introduce this dependency to my own project or it will cause a typescript compile error.

See https://github.com/googleapis/nodejs-bigquery/blob/master/src/table.ts#L36
It was added with this PR https://github.com/googleapis/nodejs-bigquery/pull/246

Thanks!

**Comment by qamil** [comment]
For others running into this, as a work around I switched back to 2.0.1.

**Comment by sduskis** [comment]
@JustinBeckwith, this sounds like a problem for you to solve.
