### ISSUE TITLE
Unable to limit results in versions past 0.9.6

### ISSUE THREAD

**Issue by huysamen** [googleapis/nodejs-bigquery#31]
In versions prior to 0.11.x, limiting results where done by passing in the `maxResults` option.  However, after upgrading to 0.11.x results are no longer being limited (no errors though).  Looking at the example source code, `LIMIT` is now explicitly added to the query, however doing so results in the following error:

`ApiError: Syntax error: Unexpected keyword LIMIT at [1:426] at Object.parseHttpRespBody`

#### Environment details

  - OS: n/a
  - Node.js version: 6.11.1
  - npm version: n/a
  - @google-cloud/bigquery version: 0.11.1

#### Steps to reproduce

  1. Use LIMIT in your query

**Comment by stephenplusplus** [comment]
Hey @huysamen, thanks for reporting. Could you show the query you are executing? We use `LIMIT` in our queries successfully (example from our tests: https://github.com/googleapis/nodejs-bigquery/blob/2f57d383331c946d8bc4b21b29a1443ef81a3963/system-test/bigquery.js#L39)

**Comment by callmehiphop** [comment]
We recently refactored a lot of the job related RPCs to have a high and low level version. Previously we only offered the low level versions, but they have since moved to a new name (`query` -> `startQuery`).

`maxResults` should still work, but your request might need to resemble the following

```js
const query = 'SELECT url FROM `publicdata.samples.github_nested`';
const [rows] = await bigquery.query(query, {maxResults: 10});
```
