### ISSUE TITLE
document maximum key limit on GROUP BY

### ISSUE THREAD

**Issue by xgalen** [googleapis/nodejs-bigquery#310]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 8.9.1
  - npm version: 6.1.0
  - `@google-cloud/bigquery` version: 1.3.0

#### Steps to reproduce

Just create a query with 65 or more fields in the `GROUP BY` clause. It throws an error:

```
Load for X has failed: {"state":"DONE","errorResult":{"reason":"invalidQuery","location":"query","message":"Maximum number of keys in GROUP BY clause is 64, query has 65 GROUP BY keys."},"errors":[{"reason":"invalidQuery","location":"query","message":"Maximum number of keys in GROUP BY clause is 64, query has 65 GROUP BY keys."}]}.
```

I have "googled" the problem but I didn't find nothing, just a SO link but not really helpful: https://stackoverflow.com/questions/31031444/how-to-group-by-more-than-64-keys-in-bigquery

I have looked for something in the docs but nothing about this limitation.

Is there any way to increase the limit,  "overpass" the limitation or any trick to get this working?

Thanks for your help,

Alfredo

**Comment by grant** [comment]
We should probably document this limit (64 fields) and then mark it as WAI. Optionally file a FR in the tracker and link it here.

**Comment by xgalen** [comment]
I found a solution to "solve" the problem. Create a hash field for all the values that I wanted to by in the `group by`, use only that column in the `group by` and use the `min()` function for all the other columns.

But as @grant says, I think it would be useful for other people to at least document this limitation.

Since I solved this in other way and if you do not plan to increase the limit, you can close this issue.

Thanks!

**Comment by shollyman** [comment]
I've created internal issue 137095409 for handling this in the BigQuery query and syntax documentation.  I'm going to go ahead and close this issue in the node library in favor of the internal issue where's more relevant.
