### ISSUE TITLE
bigquery stream (insert) directly into date partition table leaves rows with _PARTITIONTIME column NULL

### ISSUE THREAD

**Issue by garcianavalon** [googleapis/nodejs-bigquery#32]
I'm trying go stream data into partition tables as [documented in the official docs](https://cloud.google.com/bigquery/streaming-data-into-bigquery#streaming_into_partitioned_tables).

When streaming data into a partition using a table decorator (`table_name$YYYYMMDD`) the rows are correctly added and a successful response returned:
```json
[{"kind":"bigquery#tableDataInsertAllResponse"}]
[ [ { "name": "test" } ] ] // table.getRows()
```
If the same operation is performed directly to the table and not a partition (`table_name`) the response is the same and the rows are added from the Node.js API view
```json
[{"kind":"bigquery#tableDataInsertAllResponse"}]
[ [ { "name": "test" }, { "name": "test" } ] ] // table.getRows()
```
But if I use the WebUI I get the following results:
```sql
SELECT * FROM [bicg-mosaic:test_dataset.test_table] 
WHERE _PARTITIONTIME >= "2017-12-12 00:00:00" AND _PARTITIONTIME < "2017-12-13 00:00:00" 
```
1 row

```sql
SELECT * FROM [bicg-mosaic:test_dataset.test_table] 
WHERE IS_NULL(_PARTITIONTIME) 
```
1 row

By the [official docs](https://cloud.google.com/bigquery/streaming-data-into-bigquery#streaming_into_partitioned_tables) I understand that both rows should have the same date in `_PARTITIONTIME`. 

Is this a misunderstanding on how it should work or is it bug in the Node.js library?

#### sample code
```javascript
const table_name = process.env.TABLE || 'test_table'

const table = bigquery.dataset('test_dataset').table(table_name)

const data = [
  {
    name: 'test'
  }
]

table.insert(data, {}).then((response) => {
  console.log(response)
}).then(()=>{
  return table.getRows({})
}).then((response)=> {
  console.log(response)
}).catch((err) => {
  console.error('Error: %o', err)
})
```

#### Environment details

  - OS: macOS
  - Node.js version: v8.9.0
  - npm version: 5.5.1
  - @google-cloud/bigquery version: 0.11.1

#### Steps to reproduce

  1. Execute above code using `TABLE=test_table node index.js`
  2. Execute above code again using `TABLE=test_table\$20171212 node index.js`
  3. Check WebUI to verify results

Many thanks!

**Comment by stephenplusplus** [comment]
> By the official docs I understand that both rows should have the same date in `_PARTITIONTIME`.

I think the docs are saying that `_PARTITIONTIME` only exists when data in inserted into a partition. When the data goes into `test_table`, its value is null.

I have the sense I'm missing the issue you are describing though, so I apologize if I'm off track.
