### ISSUE TITLE
Types (e.g. TableMetadata) disallow valid API usage

### ISSUE THREAD

**Issue by Tyler-Murphy** [googleapis/nodejs-bigquery#332]
#### Environment details

  - OS: OSX 10.13
  - Node.js version: v11.7.0
  - npm version: 6.5.0
  - `@google-cloud/bigquery` version: 2.0.6

#### Steps to reproduce

Write this code:

```ts
dataset.createTable(
      'name'
      {
        view: {
          query: 'any SQL string',
          useLegacySql: false,
        },
      } as TableMetadata,
    )
```

The Typescript compiler will complain and say that `friendlyName` is required, and `view` must be a string. [The types in the API documentation](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource) say that friendlyName is optional, and view is an object with some properties.

I discovered this when updating from v1.3 of the library to v2. I'd expect my existing, working library calls to pass type checking, since everything still works if I disable type checking and run the code.

**Comment by JustinBeckwith** [comment]
Absolutely! We love PRs :)

**Comment by Tyler-Murphy** [comment]
@JustinBeckwith, I'm commenting to make sure my questions aren't lost even though this has been closed.

**Comment by JustinBeckwith** [comment]
No problems!  Apologies for the premature close :) 

> It seems like there are lots of fields missing on lots of types. Is this library intended to implement all features of the BigQuery API?

Yes!  It is intended to do all the things.  Specifics here are super helpful.  Are you concerned with missing typescript interfaces, or missing API endpoint support?

> It also seems like there are some convenience fields, like TableMetadata.view, which can have a type that's disallowed by the API. The library converts them to the format the API expects. How do you decide which fields get this treatment? For me, the library would be easier to use without such conversions, and with complete types that exactly match the API reference.

For that one - I actually don't know!  But the original authors, @stephenplusplus and @callmehiphop probably do :)

**Comment by callmehiphop** [comment]
@JustinBeckwith do we anticipate getting proto files for BQ anytime soon? I can definitely create interfaces for the various types across the client, but if protos are expected soon, it might be better to wait and just generate them.

**Comment by JustinBeckwith** [comment]
I do not believe that's on the horizon, but @tswast and @shollyman will know best.

**Comment by tswast** [comment]
Seth and I have a meeting about this very topic. The answer is probably eventually, but not soon. We do plan to have a subset of protos available sooner, though.

**Comment by JustinBeckwith** [comment]
@callmehiphop you can probably yank any interfaces you need from here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/bigquery/v2.ts

**Comment by callmehiphop** [comment]
@JustinBeckwith woo, thanks for the link, that should save me quite a bit of time.

**Comment by Tyler-Murphy** [comment]
What's the significance of having proto files? I'm not even sure what a proto file is.

> Yes! It is intended to do all the things. Specifics here are super helpful. Are you concerned with missing typescript interfaces, or missing API endpoint support?

I'm only concerned with incomplete/missing typescript types. I haven't had any new, specific issues, despite the types being incomplete. I only know they're incomplete because I considered completing them, and found gaps.

**Comment by tswast** [comment]
> What's the significance of having proto files? I'm not even sure what a proto file is.

You're right that from a developer perspective, proto files aren't relevant.

If you're still curious, proto files (protocol buffers) are how Google defines all of our APIs. You can browse the ones that are public at https://github.com/googleapis/googleapis. The reason they'd be relevant here is that a proto file provides a schema for all the objects in the API, so it could be translated to a typescript schema.
