### ISSUE TITLE
Weird "Invalid project ID ... " error.

### ISSUE THREAD

**Issue by YegorPavlenko** [googleapis/nodejs-bigquery#348]
#### Environment details

  - OS: Ubuntu 16.04.2 LTS, Ubuntu 16.04.4 LTS, Ubuntu 16.04.5 LTS
  - Node.js version: 8.9.4, 8.11.3, 8.15.0
  - npm version: 5.6.0, 6.7.0
  - `@google-cloud/bigquery` version: 2.0.3, 2.0.6
  - pm2 version: 2.10.1, 3.2.9

#### Description
I run node.js via pm2:
 pm2 restart /home/<user>/workspace/pm2.json --env development
with pm2 config in json file:

```json
{
  "apps": [
    {
      "name": "sbapi",
      "cwd": "/home/<user>/workspace/sbapi",
      "script": "./bin/www",
      "instances": 1,
      "min_uptime": "5000",
      "restart_delay": "2000",
      "exec_mode": "fork",
      "env": {
        "NODE_ENV": "development",
        "GOOGLE_APPLICATION_CREDENTIALS": "/home/<user>/workspace/sbapi/config/file_name.json"
      },
      "env_development": {
        "NODE_ENV": "development",
        "GOOGLE_APPLICATION_CREDENTIALS": "/home/<user>/workspace/sbapi/config/file_name.json"
      }
    }
  ]
}
```

in code with async.series I run about 38 tasks. Each send query to BigQuery:

```js
const config = require('../../config/config');
const { BigQuery } = require('@google-cloud/bigquery');
const bigquery = new BigQuery({ projectId: config.get('googleCloud:projectId') });
const dataset = bigquery.dataset(config.get('googleCloud:bqDataset'));
const table = dataset.table(config.get('googleCloud:frontendActivitiesBQTable'));

let query = `SELECT ${queryObj.columns.join()} FROM ${config.get('googleCloud:bqDataset')}.${config.get('googleCloud:frontendActivitiesBQTable')} WHERE ${queryObj.where}`;
      if (queryObj.order) query += ` ORDER BY ${queryObj.order.join()}`;
      query += ` LIMIT 10`;
table.query(query)
```

as I see in console.log() my POST queries have projectId value:

```
{ method: 'POST',
0|sbapi  |   uri: 'https://www.googleapis.com/bigquery/v2/projects/"here I really have real project name"/jobs',
|   json: 
|    { configuration: { query: [Object] },
|      jobReference: 
|       { projectId: 'here I really have real project name',
|         jobId: '26603426-4ce9-41bd-9401-4abe9ac88555' } },
|   headers: 
|    { 'User-Agent': 'gcloud-node-bigquery/2.0.6',
|      'x-goog-api-client': 'gl-node/8.15.0 gccl/2.0.6' } }
```

but after about 10 good requests I get this error:
body.error: { code: 400,
   message: 'Invalid project ID \'\'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.',

```
   errors: 
    [ { message: 'Invalid project ID \'\'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.',
        domain: 'global',
        reason: 'invalid' } ],
   status: 'INVALID_ARGUMENT' }
```

Maybe it's wrong error message.
P.S. It worked a month ago. Also as yurizekb wrote we can't use bigquery normally on our project from now and project on production. It looks like some problems with API.

**Comment by yurizekb** [comment]
The same problem, absolutely accidentally, we can no longer use bigquery normally.
code: 400,
message: 'Invalid project ID ''. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.'

**Comment by wouter** [comment]
I just wanted to add that this is also something we have seen over the last few days: intermittent errors when using [BigQuery#query](https://cloud.google.com/nodejs/docs/reference/bigquery/2.0.x/BigQuery#query) with the same error message as mentioned in the above posts regarding a missing project ID. Usually, but not always, these queries seem to succeed at a later time.

**Comment by YegorPavlenko** [comment]
The same problem have python guy:
https://stackoverflow.com/questions/54591749/bigquery-invalid-project-id-happen-sometimes/54592461

**Comment by yurizekb** [comment]
from https://issuetracker.google.com/issues/124026192

"After adding configuration.query.defaultDataset.projectId field to the JSON in the API explorer the error stopped showing up.
This field is documented as optional (https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.query), yet it seems that some of the BigQuery nodes require it.
Unfortunately the JDBC driver doesn't set this field."

**Comment by JustinBeckwith** [comment]
@callmehiphop do you think this is a backend error?

**Comment by callmehiphop** [comment]
@JustinBeckwith yeah, that is my suspicion. We haven't put out a BQ release in about a month, so it seems likely.

@tswast have you heard any chatter about this?

**Comment by YegorPavlenko** [comment]
Sorry guys, I forgot to add error stack info:
'Error: Invalid project ID \'\'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.\n    at Util.parseHttpRespBody (/<projectPath>/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/build/src/util.js:172:38)\n    at Util.handleResp (/<projectPath>/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/build/src/util.js:116:117)\n    at retryRequest (/<projectPath>/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/build/src/util.js:403:22)\n    at onResponse (/<projectPath>/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:200:7)\n    at /<projectPath>/node_modules/teeny-request/build/src/index.js:222:13\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)'

**Comment by alixhami** [comment]
This is only solves part of the problem, but when you're running queries with a project name that has "invalid characters" like hyphens, make sure you reference the table surrounded by backticks to avoid getting an invalid project ID error:
This: `SELECT thing FROM project-id.dataset_id.table_id`
Needs to be this: `` SELECT thing FROM `project-id.dataset_id.table_id` ``
I usually just include the backticks all the time as a habit.

**Comment by YegorPavlenko** [comment]
> This is only solves part of the problem, but when you're running queries with a project name that has "invalid characters" like hyphens, make sure you reference the table surrounded by backticks to avoid getting an invalid project ID error:
> This: `SELECT thing FROM project-id.dataset_id.table_id`
> Needs to be this: `` SELECT thing FROM `project-id.dataset_id.table_id` ``
> I usually just include the backticks all the time as a habit.

In SELECT I have only dataset_id.table_id (without projectID)

projectID uses in POST URI and body and actually have hyphen. But it worked before and also it works for many requests, but at some moment after around 10 requests response has error. I doubt problem is hyphen and why you think hyphen is "invalid character"?
Also I use client library for Node.JS I don't make request myself but library from google, so if hyphen is "invalid character" then I believe library should convert it.

Anyway thanks for participating. I'll check with hyphen surrounding.

**Comment by YegorPavlenko** [comment]
Fixed.
https://issuetracker.google.com/issues/124102546

**Comment by stephenplusplus** [comment]
That's great! Thank you very much for your help getting this taken care of.

**Comment by zsdyx** [comment]
This is also the case in Python
query = """
            SELECT last_modified_time FROM `@project_id.@dataset_id.INFORMATION_SCHEMA.PARTITIONS`
            WHERE table_name LIKE '@table_name%'
            ORDER BY last_modified_time DESC limit 1
        """
