### ISSUE TITLE
Add destination.expirationTime to Query Job options

### ISSUE THREAD

**Issue by almegeddon** [googleapis/nodejs-bigquery#359]
Writing query results to a destination table via Query Job is great; having to make a separate call to set the expiration time is not ideal.

Query Job options accepts a Table resource for the destination, would it be possible to add expirationTime to said resource?

**Comment by tswast** [comment]
Unfortunately the job resource in the API do es not accept an expiration time. I recommend filing an issue for the API at https://issuetracker.google.com

You may also be interested in the default expiration property on the BigQuery dataset resource.

**Comment by callmehiphop** [comment]
I'm going to close this, but if for whatever reason the API team does not want to move forward with a feature like this, let us know and maybe we can look into adding it as a client feature.
