### ISSUE TITLE
BigQuery Load Job: Authentication Object Not Passed Through .createLoadJobs Properly

### ISSUE THREAD

**Issue by jakexconniff** [googleapis/nodejs-bigquery#361]
#### Environment details

  - OS: Windows 10
  - Node.js version: 8.9.4
  - npm version: 5.8.0
  - `@google-cloud/bigquery` version: 2.0.6

#### Steps to reproduce

  1. Edit service account to have the following permissions:
      - BigQuery Admin
      - Project Owner
      - Custom Role that includes every single BigQuery permission

  2. Download service account, point Google towards said service account through a .env file (and dotenv package), Run the following example code from Google tutorial:

```
require('dotenv').config();
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
const dataset = bigquery.dataset('dataset-name');
const table = dataset.table('table-name');

const callback = (err, job, apiResponse) => {
  // `job` is a Job object that can be used to check the status of the
  // request.
  console.log(err);
  console.log(apiResponse);
};

table.createLoadJob('./data.csv', callback);
```

BigQuery web browser for Job history shows Jobs have completed successfully, but data does not go to table. Skimming through apiResponse, I can see it is pointing towards my dataset and table as expected.

apiResponse gives a self-link, which points towards a page that lists the following error object:
```
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Login Required.",
        "domain": "global",
        "reason": "required",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}
```

Another important thing to note is that with the same credentials, I am able to use other parts of the BigQuery helper library with no issue. In the same file, I am querying another table inside of the same dataset successfully.

It seems that something with the helper library is not passing the authentication token correctly for table.createLoadJob jobs. That, or I am missing something painfully obvious.

**Comment by stephenplusplus** [comment]
Just confirming we will have the same set up, what is in the .env file with regards to the configuration of this library?

**Comment by jakexconniff** [comment]
For sure. The .env file is just the google creds, exactly as below other than the specifics in the path.

```
GOOGLE_APPLICATION_CREDENTIALS='C:/path/to/project/client_secret.json'
```

**Comment by stephenplusplus** [comment]
Thanks! That self-link can't be accessed directly without authentication. You can use the Google API explorer to access the details of that job with authentication: https://developers.google.com/apis-explorer/#search/bigquery%20job%20get/m/bigquery/v2/bigquery.jobs.get

Or, our API can do the same:

```js
job.getMetadata((err, metadata) => {})
```

But, the data not going to the table isn't good. How are you verifying?

**Comment by jakexconniff** [comment]
Verifying if the data is sent to the table? I am using the front-end and doing a SELECT * query on the table and looking at table details > Number of rows.

I followed the link you provided and plugged in some values from the jobs. This does give more information than the self-link, but nothing that gives any indication of a reason for error. (I can create a scrubbed version of this response if you find it will be useful, but most of the information here is intuitive enough for me to make a reasonable assumption that it would not be helpful.)

You mentioned ensuring a similar .env file for replication test purposes. Were you able to follow my replication steps but insert into the table as expected?

**Comment by stephenplusplus** [comment]
Yes, it has worked for me. I've written a test gist. Would you mind giving it a run? https://gist.github.com/stephenplusplus/66844bf76a78b455633e1f86c0b4b7e1
