### ISSUE TITLE
Table.get not respecting autoCreate

### ISSUE THREAD

**Issue by zachberger** [googleapis/nodejs-bigquery#362]
#### Environment details

Google Cloud Function Node 8 Runtime
  - OS: Ubuntu 18.04
  - Node.js version: Node.js 8.15.0
  - npm version: Unknown 
  - `@google-cloud/bigquery` version: ^2.0.6

#### Steps to reproduce

```js
const {BigQuery} = require('@google-cloud/bigquery');
const datasetName = 'Datastore';
const tableName = 'DoesNotExist';
const bigquery = new BigQuery();

const config = {autoCreate: true};
const [dataset] = await bigquery.dataset(datasetName).get(config);
console.log('Successfully retrieved dataset.');
const [table] = await dataset.table(tableName).get(config);
console.log('Successfully retrieved table.');
```

  1. Run the code above with `tableName` set to a table that does not exist in the dataset
  2. An Error is thrown on line 9 with the message: `Not found: Table ${datasetName}.${tableName}`

Since an object is passed in with `autoCreate` set to `true` I would expect the table to be created. I have confirmed that the service account used by the Google Cloud Function has "BigQuery Data Owner" role so it should have the needed privileges to create the table.

**Comment by zachberger** [comment]
Full stacktrace of the error:

```
Error: Not found: Table <Sanitized>
    at Util.parseHttpRespBody (/srv/node_modules/@google-cloud/common/build/src/util.js:172:38)
    at Util.handleResp (/srv/node_modules/@google-cloud/common/build/src/util.js:116:117)
    at retryRequest (/srv/node_modules/@google-cloud/common/build/src/util.js:403:22)
    at onResponse (/srv/node_modules/retry-request/index.js:200:7)
    at /srv/node_modules/teeny-request/build/src/index.js:222:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by zachberger** [comment]
And when the table does exist, it is successfully retrieved and I can then do operations on it.

**Comment by callmehiphop** [comment]
@zachberger thanks for the detailed writeup, I'm able to reproduce but only on GCF.

**Comment by callmehiphop** [comment]
Just a quick update, `autoCreate` does work, however when one calls `get({autoCreate: true})` the `autoCreate` key actually gets deleted from the passed in object, so currently you can't re-use that object.

**Comment by zachberger** [comment]
That is frustrating. API's shouldn't modify data passed to it.

**Comment by zachberger** [comment]
But thank you for finding that, I now have a workaround.

**Comment by callmehiphop** [comment]
@zachberger agreed, I definitely think that's a bug - but I've opened a PR and hopefully we'll get the fix out soon!
