### ISSUE TITLE
BigQuery 3.0.0 - OAuth2 Authentication

### ISSUE THREAD

**Issue by rac0316** [googleapis/nodejs-bigquery#418]
## Blocked
- [ ] https://github.com/googleapis/google-auth-library-nodejs/issues/677

#### Environment details

  - OS: Windows 10
  - Node.js version: 10.15.1
  - npm version: 6.4.1
  - `@google-cloud/bigquery` version: 3.0.0

#### Steps to reproduce

1. Attempting to use an OAuth2 token to authenticate to the BigQuery API version 3.0.0. Successfully can get a valid token using tutorial here: https://github.com/googleapis/google-auth-library-nodejs#oauth2

2. Instantiate BigQuery with token and project param `new BigQuery({ token: validAuthTokenFromAbove, projectId: validProjectId });`

3. Attempt to run a query - this will return a "failed to fetch" error. After digging into the code, it's trying to fall back to Application Default Credentials. It seems the token property is being ignored.

*** If I downgrade BigQuery to v 1.3.0 everything works fine! I'll be using this for now until this gets resolved.

**Comment by stephenplusplus** [comment]
@callmehiphop @rac0316 do we support receiving a `token` option in a constructor?

**Comment by rac0316** [comment]
In version 1.3 it was supported as an optional field. See: https://cloud.google.com/nodejs/docs/reference/bigquery/1.3.x/global#ClientConfig

It seemed to have gotten lost somewhere in the latest releases. I did a little research and it looks like when the `@google-cloud/common` API was upgraded past version 0.17, the token option broke.

BigQuery 1.3 uses `@google-cloud/common` 0.17, which uses this library for authentication in the background: https://github.com/stephenplusplus/google-auto-auth 

BigQuery 3.0 uses  `@google-cloud/common` 0.32, which uses the official google-auth-library: https://github.com/googleapis/google-auth-library-nodejs

**I can verify if you downgrade the `@google-cloud/common` back to 0.17 w/ BigQuery 3.0, the token option works as expected.

**Comment by stephenplusplus** [comment]
Good catch! I opened an issue over on the auth library: https://github.com/googleapis/google-auth-library-nodejs/issues/677.

**Comment by grant** [comment]
This issue is preventing a sample from being created here:
https://cloud.google.com/bigquery/docs/authentication/end-user-installed

**Comment by MartinSahlen** [comment]
Hello, I managed to get over this bug by doing this: https://github.com/googleapis/nodejs-bigquery/issues/68#issuecomment-515673201

**Comment by meredithslota** [comment]
Tagging in @feywind as an FYI.

**Comment by tswast** [comment]
Possibly fixed by https://github.com/googleapis/nodejs-bigquery/pull/566

**Comment by steffnay** [comment]
Fixed by [#566](https://github.com/googleapis/nodejs-bigquery/pull/566)
