### ISSUE TITLE
How do I run queries that depend on UDF?

### ISSUE THREAD

**Issue by ashishtilara** [googleapis/nodejs-bigquery#43]
I don't have steps to reproduce, but as my question suggests, I have a query that depends on UDF. How do I execute that using SDK. There is not one place to find all information/examples.

Appreciate any help.

**Comment by stephenplusplus** [comment]
I don't have much experience with UDFs, but it looks like they are defined within the query:

> UDFs are temporary. This means you can only use them for the current query or command-line session.
> \- https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions

I tested this out, using one of their examples:

```js
const query = `
  CREATE TEMPORARY FUNCTION multiplyInputs(x FLOAT64, y FLOAT64)
  RETURNS FLOAT64
  LANGUAGE js AS """
    return x*y;
  """;
  WITH numbers AS
    (SELECT 1 AS x, 5 as y
    UNION ALL
    SELECT 2 AS x, 10 as y
    UNION ALL
    SELECT 3 as x, 15 as y)
  SELECT x, y, multiplyInputs(x, y) as product
  FROM numbers;`;

bigquery.query(query, function(err, resp) {
  // resp = [
  //   { x: 1, y: 5, product: 5 },
  //   { x: 2, y: 10, product: 20 },
  //   { x: 3, y: 15, product: 45 }
  // ]
});
```

It seemed to have worked as intended. Is this the functionality you were looking for?

**Comment by stephenplusplus** [comment]
I'm going to close, as I believe we found the resolution. If not, just let me know and I will re-open. Thanks!
