### ISSUE TITLE
Parametric Query fails when dealing with repeated records (array of structs)

### ISSUE THREAD

**Issue by salexi** [googleapis/nodejs-bigquery#437]
#### Environment details
 * OS: macOS Mojave (10.14)
 * Node.js version: 11.1.0
 * npm version: 6.9.0
 * `@google-cloud/bigquery` version: 3.0
 
 #### Steps to reproduce
Run a query on a repeated record.
Given the following code: 

```js
class Person {
    [index: string]: any;
    firstName: string;
    lastName: string;

    constructor(firstName, lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
}

const group = [
    new Person('John', 'Doe'),
    new Person('Jane', 'Doe')
]
```

We run an update query: 

```js
const [rows] = await bq.query({
  query: 'UPDATE [table] set group = @group WHERE true',
  params: {
    group: group,
  },
});
```

The query returns an error: 
```
Array cannot have a null element; error in writing field group
```
Upon further inspection, the json generated looks like this:
```js
{
    parameterType: {
        type: 'ARRAY',
        arrayType: {
            type: 'STRUCT',
            structTypes: [
                { name: 'firstName', type: { type: 'STRING' } },
                { name: 'LastName', type: { type: 'STRING' } }
            ]
        }
    },
    parameterValue: {
        arrayValues: [
            { value: { firstName: "John", lastName: "Doe" } },
            { value: { firstName: "Jane", lastName: "Doe" } },
        ]
    }
}
```

While the api expects 
```js
{
    parameterType: {
        type: 'ARRAY',
        arrayType: {
            type: 'STRUCT',
            structTypes: [
                { name: 'firstName', type: { type: 'STRING' } },
                { name: 'LastName', type: { type: 'STRING' } }
            ]
        }
    },
    parameterValue: {
        arrayValues: [
            {
                structValues: {
                    firstName: { value: "John" },
                    lastName: { value: "Doe" }
                }
            },
            {
                structValues: {
                    firstName: { value: "Jane" },
                    lastName: { value: "Doe" }
                }
            },
        ]
    }
}
```
 #### Source of the error

I believe the issue comes from 
https://github.com/googleapis/nodejs-bigquery/blob/0e4aeef5a1ae9ea69e3ecb11318dbe463bfeae70/src/index.ts#L801-L834

More specifically from 
https://github.com/googleapis/nodejs-bigquery/blob/0e4aeef5a1ae9ea69e3ecb11318dbe463bfeae70/src/index.ts#L814-L815

As it seems that getValue()
https://github.com/googleapis/nodejs-bigquery/blob/0e4aeef5a1ae9ea69e3ecb11318dbe463bfeae70/src/index.ts#L837-L839

ignores the type struct

#### A possible fix (tested by me) would be changing this
https://github.com/googleapis/nodejs-bigquery/blob/0e4aeef5a1ae9ea69e3ecb11318dbe463bfeae70/src/index.ts#L811-L817

to: 
```typescript
    if (typeName === 'ARRAY') {
        queryParameter.parameterValue!.arrayValues = (value as Array<{}>).map(
            itemValue => {
                if (is.object(itemValue)) {
                    return BigQuery.valueToQueryParameter_(itemValue).parameterValue;
                } else {
                    const value = getValue(itemValue, parameterType.arrayType!);
                    return { value } as bigquery.IQueryParameterValue;
                }
            });
    }
```

**Comment by salexi** [comment]
That was fast, thanks! I'll be waiting for the release now.
In the meantime i ended up extending BigQuery and overriding the method.

There still is the related issue  #400. Let's how that will get fixed soon too :D

**Comment by callmehiphop** [comment]
@salexi thanks for reporting it! #400 is on my radar but it is a little bit trickier.
