### ISSUE TITLE
Job configuration setting `useAvroLogicalTypes` ignored when creating load job

### ISSUE THREAD

**Issue by ksesong** [googleapis/nodejs-bigquery#459]
I have essentially the same issue as the one described [in this issue](https://issuetracker.google.com/issues/35905894?pli=1#comment38), but reading from the comments, it should be resolved with the job metadata `useAvroLogicalTypes` flag when creating a new job.

The flag is ignored (so it cannot create a table, and if created manually, the `timestamp-millis` logical type field is interpreted as microseconds, same consequences as in the issue linked).

**Comment by callmehiphop** [comment]
Hi @ksesong, can I ask how you're trying to use the `useAvroLogicalTypes`? From what I can tell we do support it via `Table#createLoadJob` and `Table#load`.

```js
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
const dataset = bigquery.dataset('my-dataset');
const table = dataset.table('my-table');

table.load('./myfile', {
  useAvroLogicalTypes: true
}, (err, response) => {
  // should be loaded
});
```

**Comment by ksesong** [comment]
My code looks pretty much the same as yours, so I am confused. Is it related to partitioning/clustering?
```
const [job] = await bigqueryClient
  .dataset(datasetId)
  .table(tableId)
  .createLoadJob(filePath, {
    format: 'AVRO',
    timePartitioning: {
      field: 'date',
    },
    clustering: {
      fields: ['level_id'],
    },
    useAvroLogicalTypes: true,
  });
```

**Comment by callmehiphop** [comment]
@ksesong using an avro file in our [sample directory](https://github.com/googleapis/nodejs-bigquery/blob/master/samples/resources/data.avro), I can confirm that the client loads the data successfully with both the `format` and `useAvroLogicalTypes` fields set. Would you be able to provide us with the exact error you're seeing?

**Comment by ksesong** [comment]
I can confirm that this is indeed working. My `avro` file was malformed and did not include any logical type. Thanks for the help.
