### ISSUE TITLE
Online Documents not following current release

### ISSUE THREAD

**Issue by duanshiqiang** [googleapis/nodejs-bigquery#47]
Online documents https://cloud.google.com/nodejs/docs/reference/bigquery/0.11.x/Table is apparently not talking about the most recent release (0.11.1). It seems to be talking abount master branch.

One obvious mistake is the method name to load data to bigquery table. It was renamed from "import" to "load" (which IMO is really a break change) at commit [536a88dd9](https://github.com/googleapis/nodejs-bigquery/commit/536a88dd954139c7345530039a0eaef204473716) which has not been released but the online documentation is already showing it.

**Comment by stephenplusplus** [comment]
Hmm. That's strange. You're correct, we haven't released that.

@alexander-fenster @jmdobry

**Comment by jmdobry** [comment]
@stephenplusplus @alexander-fenster @lukesneeringer Need to release `0.12.0` asap, this will fix the documentation issue. Otherwise I need to delete  https://cloud.google.com/nodejs/docs/reference/bigquery/latest and we'll be without ref docs for nodejs-bigquery

**Comment by lukesneeringer** [comment]
(I see no green dot by @alexander-fenster's name on Hangouts, so I am assuming he is on vacation today and handling this. Apologies if I in advertently step on toes.)

**Comment by lukesneeringer** [comment]
Releasing 0.12.0; I will close this once the release is on npm.

**Comment by lukesneeringer** [comment]
@google-cloud/bigquery 0.12.0 [is now on npm](https://www.npmjs.com/package/@google-cloud/bigquery).
