### ISSUE TITLE
BigQuery: Verify/implement list options for dataset and job collections

### ISSUE THREAD

**Issue by shollyman** [googleapis/nodejs-bigquery#498]
Verify that "minCreationTime" and "maxCreationTime" filters are available for users of jobs.list.

Verify that label filtering (the "filter" param) is available for users of datasets.list

An example of the implementations in java: googleapis/google-cloud-java#5717

If there are any tests or samples that blindly iterate across the jobs collection, we should add at least a reasonable minCreationTime filter to reduce test times and demonstrate how to limit results to an expected time window.

cc @steffnay

**Comment by callmehiphop** [comment]
@shollyman I can confirm that we support all params for both RPCs.
