### ISSUE TITLE
Unable to LIMIT query using parameter

### ISSUE THREAD

**Issue by huysamen** [googleapis/nodejs-bigquery#50]
Limiting results using an `@parameter` results in the following error:

`ApiError: Syntax error: Unexpected keyword LIMIT at [1:426] at Object.parseHttpRespBody`

Environment details

OS: n/a
Node.js version: 6.11.5
npm version: n/a
 version: 1.0.0
Steps to reproduce

Use `LIMIT @limitVariable` in your query and pass in `limitVariable` in `params: { ... }` option.

**Comment by stephenplusplus** [comment]
Thanks for reporting. @alexander-fenster @callmehiphop -- do we know that this is possible?

Here's the JSON we send to the API:

```js
{
  "useLegacySql": false,
  "query": "SELECT url FROM `publicdata.samples.github_nested` WHERE repository.owner = @owner LIMIT @limit",
  "parameterMode": "named",
  "queryParameters": [
    {
      "parameterType": {
        "type": "STRING"
      },
      "parameterValue": {
        "value": "google"
      },
      "name": "owner"
    },
    {
      "parameterType": {
        "type": "INT64"
      },
      "parameterValue": {
        "value": 1
      },
      "name": "limit"
    }
  ]
}
```

**Comment by callmehiphop** [comment]
Truthfully I'm not sure, I'm going through the documentation to see if its explicitly mentioned anywhere.

**Comment by stephenplusplus** [comment]
@alexander-fenster we could use some input from the BQ team here.

**Comment by callmehiphop** [comment]
So I came across this blurb

> Parameters cannot be used as substitutes for identifiers, column names, table names, or other parts of the query.

Which is pretty vague, but maybe explains this? @tswast any chance you could provide a definitive answer for us here?

**Comment by tswast** [comment]
To make it more precise, refer to the SQL Syntax specification at https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

Only parts of the query labeled as "expression" can be replaced by query parameters.
