### ISSUE TITLE
Is it possible to set Big Query base endpoint?

### ISSUE THREAD

**Issue by aaleksandrov** [googleapis/nodejs-bigquery#503]
Hi
I couldn't find an option to set an endpoint in this library.
We need to do it for integration testing so we can point to localhost. Does this library support this?

**Comment by callmehiphop** [comment]
Hi @aaleksandrov, I believe the following will work

```js
const bq = new BigQuery({apiEndpoint: 'my-endpoint.com'});
```

Let us know if that works!

**Comment by aaleksandrov** [comment]
Oh, thanks! Sorry for such a silly question :)
