### ISSUE TITLE
Broken code examples in BigQuery documentation

### ISSUE THREAD

**Issue by MajorBreakfast** [googleapis/nodejs-bigquery#504]
The documentation under https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html has HTML tags in the code examples (e.g. `<caption>` tags):

```
<caption>Install the client library with <a
href="https://www.npmjs.com/">npm</a>:</caption> npm install --save
```

**Comment by callmehiphop** [comment]
`<caption>` is actually the standard way of applying a caption to a JSDoc example, looks like the current template is borked.

@JustinBeckwith @bcoe are we planning on using the new jsdoc template here? Looks like that will resolve this issue.

**Comment by JustinBeckwith** [comment]
This was an issue both where a.) the previous jsdoc template didn't support captions and b.) somewhere along the line the formatting of the jsdoc comments got broken with newlines. We already updated the template, and b.) is covered in #513

**Comment by MajorBreakfast** [comment]
Thanks for fixing this! 👍
