### ISSUE TITLE
ApiError: Not found: Files

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigquery#52]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2795

<a href="/cvanputten"><img src="https://avatars2.githubusercontent.com/u/35573811?s=88&v=4" height=44 width=44 align=left></a>@cvanputten<br>January 18, 2018 5:18 PM

I am suddenly getting an error from 'google-cloud/bigquery' that can't find a file on gdrive. I am not calling this file in my code and I think it's coming from the @google-cloud node module. Here is the full error:
```
 { ApiError: Not found: Files /gdrive/id/1XehS5UuvCKR3fHGkeoX_7JphVc0TqGsVy6YlGRBTvZU
    at Object.parseHttpRespBody (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:192:30)
    at Object.handleResp (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:132:18)
    at /user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/user_code/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:180:7)
    at Request.self.callback (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  code: 404,
  errors: 
   [ { domain: 'global',
       reason: 'notFound',
       message: 'Not found: Files /gdrive/id/1XehS5UuvCKR3fHGkeoX_7JphVc0TqGsVy6YlGRBTvZU' } ],
  response: undefined,
  message: 'Not found: Files /gdrive/id/1XehS5UuvCKR3fHGkeoX_7JphVc0TqGsVy6YlGRBTvZU' }"  
 timestamp:  "2018-01-18T09:13:17.477Z
```

**Comment by cvanputten** [comment]
I'm calling BigQuery. Successfully in the beginning but not anymore. There is some gdrive doc that can't be found but my query doesn't refer to any table or view that refers to a gdrive doc
Code snippet:

function selectNewFirstTrans(){
	var query = 'SELECT AccountId as Id, First_Trans_Proc__c FROM `payline-data.EMAF.90_day_active_first_trans` LIMIT 1000';
	var options ={
		"kind": "bigquery#queryRequest",
		"query": query,
		"useLegacySql": false
	};

	bq.query(options, function(err, rows) {
		if (!err) {
			console.log(`BigQuery returned no errors and ${rows.length} records`);
			//console.log(rows);
			if (rows.length != 0 || rows.length != undefined){
				updateAccount(rows);
			}
			
		}
		else {
			console.error(err);
		}
	});
}

**Comment by stephenplusplus** [comment]
Could you isolate this down to as small of a sample as possible that can reproduce? Ideally, in a repo on its own that I can clone, install, and run.

**Comment by stephenplusplus** [comment]
I'm going to close since I cannot reproduce without further information.

**Comment by antono** [comment]
This may be related to https://github.com/googleapis/nodejs-bigquery/pull/99

Make sure you shared your doc to service account and added gdrive.readonly scope.
