### ISSUE TITLE
Online documentation not reachable

### ISSUE THREAD

**Issue by masonlouchart** [googleapis/nodejs-bigquery#522]
Is the [online BigQuery NodeJs API reference](https://googleapis.dev/nodejs/bigquery/latest#reference) not reachable or it's only me?

**Comment by masonlouchart** [comment]
I'm seeing this:

<img width="745" alt="Capture d’écran 2019-08-29 à 23 29 35" src="https://user-images.githubusercontent.com/2325091/63949262-13b48600-cab5-11e9-8eba-d37bacae949d.png">


I don't know if there is a firewall. I rent an apartment for a month and the Wi-Fi is provided by the building owner.

**Comment by bcoe** [comment]
if you are visiting:

https://googleapis.dev/nodejs/bigquery/latest#reference

I believe this is most definitely the connection in the apartment you are renting, not a problem with the documentation at large. Are you able to try connecting from your phone, or another connection?

**Comment by masonlouchart** [comment]
Yep. Sorry to have bothered you for nothing.
