### ISSUE TITLE
Reference Table in Another Project

### ISSUE THREAD

**Issue by scottfr** [googleapis/nodejs-bigquery#527]
I would like to stream inserts to a table that is a separate project than my application code. My application project has IAM access to the tables in the project where I would like to do the inserts.

Unfortunately, it does not appear there is anyway to specify a table in a different project. 

The syntax to stream inserts to a table in your current project is:

`bigquery.dataset('warehouse').table('events').insert(insertedRows)`

Would it be possible to add syntax like the following:

`bigquery.project('other-project').dataset('warehouse').table('events').insert(insertedRows)`

**Comment by callmehiphop** [comment]
@scottfr could you just make a separate `bigquery` instance?

```js
const bq = new BigQuery();
const bq2 = new BigQuery({projectId: 'other-project});
```

**Comment by tswast** [comment]
Creating a second instance will retrigger the auth logic, which can take a great deal of time in some environments. I agree that it should be possible to reference resources across projects.

**Comment by callmehiphop** [comment]
@tswast fair enough. Do you think there would be any value in allowing the user to supply a `projectId` at the `dataset()` level or should this option exist only for tables?

**Comment by tswast** [comment]
Definitely some utility in having it at `dataset()` level. For example, if you want to list all the tables in one of our public datasets.

**Comment by stephenplusplus** [comment]
Just for consideration, if we allowed the auth instance to be re-used in Dave's first example, would that work?

And/or, if a user provides a full path name for the dataset or table which includes the project ID, we could do it transparently.

**Comment by steffnay** [comment]
@tswast @stephenplusplus have we decided how to approach this?
