### ISSUE TITLE
delete, create, insert into table  -  silent failure

### ISSUE THREAD

**Issue by leblancmeneses** [googleapis/nodejs-bigquery#53]
- OS: Windows
  - Node.js version: v8.9.4
  - npm version: 5.6.0
  - `@google-cloud/bigquery` version: `"@google-cloud/bigquery": "^1.0.0",`

#### Steps to reproduce

I copied and pasted the sample examples to arrange an etl data refresh process.
Through nodejs bigquery api write a script that does the following with chained promises:

  1. delete xyz table
  2. create xyz table
  3. insert refreshed rows into xyz table using streaming insert api
  4. verify getRows  matches inserted rows.length
     - verification fails.  0 rows were inserted and catch is not executed.

Expected:  Non silent failure or promises to wait till fully complete.

```
const BigQuery = require('@google-cloud/bigquery');
const Papa = require('papaparse');
const path = require('path');
const fs = require('fs');


const projectId = "projectid";
const datasetId = "sqlserver";
const tableId = "xyz";

const bigquery = new BigQuery({
  projectId: projectId,
});

const initBigQueryTable = () => {
  const schema = {
    fields: [{
      "mode": "NULLABLE",
      "name": "EventId",
      "type": "INTEGER"
    }]
  };

  // Delete original table.
  return bigquery
    .dataset(datasetId)
    .table(tableId)
    .delete().then(() => {
      console.log('Deleted:', tableId);
      // Create a new table in the dataset
      return bigquery
        .dataset(datasetId)
        .createTable(tableId, { schema: schema })
        .then(() => {
          console.log('Created:', tableId);
        })
    });
};

const importRows = (toInsertRows) => {

  return bigquery
    .dataset(datasetId)
    .table(tableId)
    .getRows().then(results => {
      const rows = results[0];
      if (rows.length == 0) {
        return bigquery
          .dataset(datasetId)
          .table(tableId)
          .insert(toInsertRows)
          .catch(err => {
            if (err && err.name === 'PartialFailureError') {
              if (err.errors && err.errors.length > 0) {
                console.log('Insert errors:');
                err.errors.forEach(err => console.error(err));
              }
            } else {
              console.error('ERROR:', err);
            }
          });
      } else {
        throw new Error(`new table should have zero rows. Found ${rows.length} expected 0.`);
      }
    }).then(() => {
      return bigquery
        .dataset(datasetId)
        .table(tableId)
        .getRows().then(results => {
          console.log(`Should have inserted ${toInsertRows.length} rows.`);
          const rows = results[0];
          if (rows.length != toInsertRows.length) {
            throw new Error(`rows should match inserted rows. Found ${rows.length} expected ${toInsertRows.length}.`);
          }
        })
    })
};


const csvRows = fs.readFileSync('./xyz.csv', "utf8").trim();
Papa.parse(csvRows, {
  header: true,
  delimiter: ',',
  complete: function (results) {
    if ((results.errors || []).length > 0) {
      console.log('failed', results.errors);
      return;
    }

    initBigQueryTable().then(() => {
      return importRows(results.data);
    }).then(() => {
      console.log('done');
      process.exit(0);
    }).catch(err => {
      console.error('ERROR:', err);
      process.exit(1);
    });
  }
});

```

![webjob-import](https://user-images.githubusercontent.com/730804/35207092-ab63be84-ff06-11e7-9092-9819c36246f0.jpg)

**Comment by leblancmeneses** [comment]
If I remove the table delete promise and just create a new table it works correctly.

Also, the UI has a problem with streaming api rows:
![image](https://user-images.githubusercontent.com/730804/35207366-26b0291e-ff08-11e7-88a0-a5754ad395d0.png)

Preview doesn't work but the data does exist.

So I think the problem is with the delete operation and trying to recreate the same table.

**Comment by stephenplusplus** [comment]
In our test files against the API, we always have a timeout between 2500 - 15000 ms before querying what was just inserted. I'm not sure how to explain the Table creation/deletion having an effect, but I don't think we can do much from our end as the client library as we are limited by the behavior of the BigQuery API.

Regarding the UI, it seems like something in the record must be hard to represent in that UI element. But if you think it's an error, please let that team know through these links: https://cloud.google.com/support/.

Please let me know if I missed the bug here, and there's more for us to do.

**Comment by leblancmeneses** [comment]
I changed my approach to use the jobs api  and to WRITE_TRUNCATE, https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.writeDisposition .

Accomplishes the same goal which is to refresh my data.


```

    await storage
      .bucket(bucketName)
      .upload(filename)
      .then(() => {
        console.log(`${filename} uploaded to ${bucketName}.`);
      });

    let job;
    await bigquery
      .dataset(datasetId)
      .table(tableId)
      .load(storage.bucket(bucketName).file(filename), {
        createDisposition: 'CREATE_NEVER',
        writeDisposition: 'WRITE_TRUNCATE',
        autodetect: true,
        skipLeadingRows: 1
      })
      .then(results => {
        job = results[0];
        console.log(`Job ${job.id} started.`);
    
        // Wait for the job to finish
        return job;
      })
      .then(metadata => {
        // Check the job's status for errors
        const errors = metadata.status.errors;
        if (errors && errors.length > 0) {
          throw errors;
        }
      })
      .then(async () => {
        console.log(`Job ${job.id} completed.`);
      })
      .catch(err => {
        console.error('ERROR:', err);
      });
```

**Comment by JamesMcMahon** [comment]
@marcospgp Hitting a similar issue, did you ever find a workaround?

**Comment by JamesMcMahon** [comment]
@stephenplusplus this seems like a serious issue. Is there known BigQuery issue for this in an external tracker?

**Comment by JamesMcMahon** [comment]
Just for prosperity.

Similar issues on the Python tracker, https://github.com/googleapis/google-cloud-python/issues/3822.

PHP, https://github.com/googleapis/google-cloud-php/issues/871

SO, https://stackoverflow.com/questions/51995740/google-bigquery-streaming-failed-sometimes-if-i-do-delete-table-and-create-table

**Comment by marcospgp** [comment]
@JamesMcMahon My workaround consisted in adding a random string to the table name, for these tables I was generating (and deleting).

I was manipulating the tables in a testing script, so that was why my usecase involved a lot of table deletions.
