### ISSUE TITLE
BigQuery: expose CMEK functionality for ML models

### ISSUE THREAD

**Issue by shollyman** [googleapis/nodejs-bigquery#546]
This request is to expose customer managed encryption key (CMEK) for BigQuery ML models.

It uses the same message (encryptionConfig) as is present on the rest interface
for managed tables, e.g. the expression of a related KMSKeyName.

ML models aren't instantiated via the API directly, but via CREATE MODEL sql query.
The CMEK functionality should be present in the API for other relevant mechanisms,
such as models.get and models.update.

For more information, contact @shollyman.

**Comment by callmehiphop** [comment]
👋 @shollyman I think we already have support for this. Does the following sample meet the expectation?

```js
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
const model = bigquery.dataset('my-dataset').model('my-model');

await model.setMetadata({
  encryptionConfiguration: {
    kmsKeyName: 'my-kms-key'
  }
});
```

**Comment by shollyman** [comment]
Yes, if you've already got the stuff to autogen the reference type representations from discovery running, this may entirely be a no-op for you.  Thanks for checking.

**Comment by callmehiphop** [comment]
Awesome, I'm going to close this out then!
