### ISSUE TITLE
Memory leak with simple inserts

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-bigquery#547]
#### Environment details

  - OS: Darwin Kernel Version 19.0.0: Sat Aug 31 18:49:12 PDT 2019; root:xnu-6153.11.15~8/RELEASE_X86_64 x86_64
  - Node.js version: v10.16.3
  - npm version: v6.11.2
  - `@google-cloud/bigquery` version: v4.2.1

#### Steps to reproduce

Run the following code:

```js
const { BigQuery } = require('@google-cloud/bigquery');

const bigQuery = new BigQuery({ projectId: 'my-project-id' });

const run = async () => {
  while (true) {
    await bigQuery
      .dataset('test')
      .table('test')
      .insert({ property: 'value'.repeat(1024) });
  }
};

run();
```

When attaching an inspector, we can clearly see objects being retained in memory:
<img width="532" alt="Screen Shot 2019-09-21 at 15 34 39" src="https://user-images.githubusercontent.com/10390061/65374083-05a5ef80-dc86-11e9-892f-54b2b137f9cf.png">

Memory usage will grow indefinitely.

**Comment by callmehiphop** [comment]
👋 @merlinnot thanks for reporting! Looks like an issue with one our dependencies, [teeny-request](https://github.com/googleapis/teeny-request). As it is today it creates a new https Agent per request, which appears to be the source of the leak. I'm going to work on a PR to implement agent pooling.

**Comment by callmehiphop** [comment]
Also for a temporary solution, I believe the following should help

```js
const {BigQuery} = require('@google-cloud/bigquery');
const bq = new BigQuery();

bq.interceptors.push({
  request: reqOpts => {
    reqOpts.forever = false;
    return reqOpts;
  }
});
```

**Comment by SaschaHeyer** [comment]
I can confirm the behavior found by @merlinnot. 
Do you have any ETA? This issue cause harmful outtakes in production environments.

**Comment by merlinnot** [comment]
@callmehiphop Do you know if there's a way to add these interceptors using publicly available API? As far as I can see property `interceptors` is private and only accessible within class `Service`.

**Comment by merlinnot** [comment]
I can confirm that setting `reqOpts.forever = false` works as expected. What are the downsides of it? Should it be added to this library itself?

**Comment by callmehiphop** [comment]
@merlinnot actually forever is false by default and truthfully I don't know the specifics on why we enabled it originally. Maybe @stephenplusplus can chime in here?

**Comment by stephenplusplus** [comment]
Looks like it was added to fix this same problem 😆: https://github.com/googleapis/google-cloud-node/issues/1928

**Comment by merlinnot** [comment]
Hmm, Keep-Alive should not cause memory retention from requests that are already processed. If I’m seeing it correctly, `forever` was introduced two years ago and it worked just fine for a long time - the problem started recently.

**Comment by callmehiphop** [comment]
@merlinnot that is correct. We ended up swapping out `request` for a package called [`teeny-request`](https://github.com/googleapis/teeny-request). The underlying issue here is that the `forever` option was implemented incorrectly in teeny-request.

**Comment by callmehiphop** [comment]
@merlinnot we just made a teeny-request release that should fix this. Would you mind deleting any lock files/reinstalling and seeing if the issue is resolved for you?

**Comment by merlinnot** [comment]
I tested it and the memory usage seems stable, at least over a span of an hour. Thank you for a quick resolution.

I'll go ahead and close it, but I think we should make this version of `teeny-request` a minimal version for this library, so other users don't bump into this issue (e.g. when deduplicating etc.)

**Comment by callmehiphop** [comment]
@merlinnot agreed, I'll get a PR out there to do that. Thanks for all your help!
