### ISSUE TITLE
BigQuery client should retry on 502

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-bigquery#55]
See details [here](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/868) - we might need to implement the same behavior for Node.js library, if not already. What is our current behavior for HTTP code 502?

**Comment by stephenplusplus** [comment]
We do! https://github.com/googleapis/nodejs-common/blob/959fcc43122f815aabae39125163d7a8c0a08c06/src/util.js#L288

Given that, I'm going to close, but just re-open if something makes you think we have a bug.
