### ISSUE TITLE
implement: defaultEncryptionConfiguration on datasets

### ISSUE THREAD

**Issue by shollyman** [googleapis/nodejs-bigquery#550]
This feature request is to ensure the client library supports default encryption settings on
BigQuery dataset resources.

On a dataset, defaultEncryptionConfiguration (an instance of EncryptionConfiguration) can 
be used to indicate a default CMEK key that will apply to all new tables or ML models created
within the dataset.  Existing models are not affected, and this can be overridden when a 
(table or model) is created by specifying the settings explicitly.

For libraries that expose underlying discovery types directly, this request may be a no-op.

For more information, please contact @shollyman

**Comment by callmehiphop** [comment]
👋 @shollyman I believe this is a no-op for us, but just to confirm everything looks good, here is a usage example for the requested feature

```js
const {BigQuery} = require('@google-cloud/bigquery');
const bq = new BigQuery();

// when creating a dataset
const [dataset] = await bq.createDataset('my-dataset', {
  defaultEncryptionConfiguration: {
    kmsKeyName: 'my-key'
  }
});

// when updating a dataset
await dataset.setMetadata({
  defaultEncryptionConfiguration: {
    kmsKeyName: 'my-key'
  }
});
```

**Comment by shollyman** [comment]
Thanks for confirming, I'll go ahead and close.
