### ISSUE TITLE
Add option to use environment variable to set baseUrl for BigQuery constructor

### ISSUE THREAD

**Issue by amalhotragannett** [googleapis/nodejs-bigquery#568]
Problem: In order to make testing more efficient we need to create a mock BigQuery server to simulate errors and success. Currently, we creating the BigQuery constructor we can pass in `apiEndpoint` to override the URL. However, when the baseUrl is created it uses the `https` protocol. We want to override the value using environment variables. 

Alternatives Considered: 
`apiEndpoint` to override the endpoint.
Example:
```
const bq = new BigQuery({
      apiEndpoint: 'localhost:9090'
    });
```
This makes sets the `bq.baseUrl='https://localhost:9090'`
Since, the local emulator is running on `http://localhost:9090`. The request are not received due to SSL. 

The emulator is not provided by Google. We are using a custom application which response to a request from BigQuery APIs. 

Expected Behavior:
A configuration through environment variable or an option to override baseUrl.

**Comment by callmehiphop** [comment]
Thanks for opening an issue! I was looking at some of our other client libraries to see if/how we supported specifying protocols elsewhere and it looks like in some cases we offer a `protocol` option.

@alexander-fenster @bcoe what are your feelings on adding support for `protocol` here and allowing users to configure it? I'm not sure if that is the intended use for it elsewhere, since I could only find references to it for grpc fallback code.

**Comment by amalhotragannett** [comment]
@callmehiphop - I was looking into the Google Cloud Storage for the emulator HOST. 
https://github.com/googleapis/nodejs-storage/blob/862fb16db2990c958c0097252a44c775431a7b3f/src/storage.ts#L375-L390

It didn't have protocol support. But it did have a similar environment variable to incorporate the protocols.

**Comment by callmehiphop** [comment]
Interesting, @tswast @shollyman do either of you have any feelings on supporting an environment variable for third party emulators?

**Comment by stephenplusplus** [comment]
Note that there's some oddity in how that is implemented in Storage: https://github.com/googleapis/nodejs-storage/issues/898#issuecomment-547461664

**Comment by amalhotragannett** [comment]
There is a similar implementation with the [PubSub package](https://github.com/googleapis/nodejs-pubsub/blob/1749b626e6bff5fefd1b1b8c673c480a10be9cf9/src/pubsub.ts#L524-L546) as well.

**Comment by shollyman** [comment]
I absolutely support overriding the endpoint.  We allow users to drop from https to http protocol if they want when doing this in other languages, so I'd expect the same thing to possible here but there may be nuance I'm missing.

I think it's odd to have first party support for specifying an emulator when no such beast really exists.  The other products that have such support also provide the emulator, though fidelity levels vary.  Efforts like https://github.com/google/zetasql will make building things like this more possible in the future.
