### ISSUE TITLE
Add support for BigQuery customer-managed encryption keys

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigquery#58]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2801

<a href="/choenden"><img src="https://avatars2.githubusercontent.com/u/5809974?s=88&v=4" height=44 width=44 align=left></a>@choenden<br>February 6, 2018 4:33 PM

BigQuery customer-managed encryption keys allow users to specify a Cloud KMS key to protect their BigQuery table.

API:
Jobs: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs
In a job, there is a destinationEncryptionConfiguration field, which indicates which Cloud KMS key should be used for the destination.

Tables: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables
In a table, there is a encryptionConfiguration field, which indicates which Cloud KMS key protects (or should protect in case of CreateTable) a BigQuery table.

These are the main APIs that are required for day-to-day interaction.
With lower priority, support for getServiceAccount would also be nice: https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/getServiceAccount
Note that unlike the other methods mentioned above, this would generally only be called once and the resulting value (the email address) does not change - so it can easily also be called from UI/API/CLI without much hindrance (hence lower priority).

**Comment by choenden** [comment]
Actually, upon trying the client libraries, it looks like the encryption configuration can be set directly as part of the json object and changes for this are not required.

**Comment by stephenplusplus** [comment]
Oh, great!
