### ISSUE TITLE
table.load() is not a function

### ISSUE THREAD

**Issue by kendavie** [googleapis/nodejs-bigquery#59]
Using Cloud functions to trigger the creation of a new JSON file to be ingested into BigQuery. The below function is triggered when files is uploaded. 

```js
function insertGCS(datasetId, tableId, bucketName, filename, projectId) { 
const BigQuery = require('@google-cloud/bigquery');
const bigquery = new BigQuery()
const dataset = bigquery.dataset(datasetId);
const table = dataset.table(tableId);

var metadata = {
            sourceFormat: "NEWLINE_DELIMITED_JSON",
            autodetect : true,
            schemaUpdateOptions: ["ALLOW_FIELD_ADDITION","ALLOW_FIELD_RELAXATION"],
            createDisposition: "CREATE_IF_NEEDED",
            writeDisposition: "WRITE_APPEND"
  };

var gcs = require('@google-cloud/storage')({
  projectId: projectId
});
var data = gcs.bucket(bucketName).file(filename);
table.load(data, metadata, function(err, apiResponse) {});
}

```
Table reference in documentation (https://cloud.google.com/nodejs/docs/reference/bigquery/1.0.x/Table#load)  states:

`const table = bigquery.table(tableId);` 

which results in bigquery.table() is not a function. When changed to: 

`const table = dataset.table(tableId);` 

executes as expected, however now fails with `table.load()` is not a function.

When printing the table object in the logger i can see that table, only has the following methods:

```
    methods: {
        create: true,
        delete: true,
        exists: true,
        get: true,
        getMetadata: true
    }
```

**Comment by stephenplusplus** [comment]
Table objects are accessed through the Dataset, so your sample code and second example are correct.

What version of `@google-cloud/bigquery` are you using?

**Comment by kendavie** [comment]
package.json includes the following:

```
{
 "dependencies": {
    "@google-cloud/bigquery": "^0.9.0",
    "@google-cloud/storage": "^1.0.0"
  }
}
```

**Comment by stephenplusplus** [comment]
The `load()` function was added in 0.12.0. The docs you are browsing are for an even newer version, 1.0.0. Please check out the release notes and give upgrading a shot :) https://github.com/googleapis/nodejs-bigquery/releases
