### ISSUE TITLE
fs.createReadStream is undefined

### ISSUE THREAD

**Issue by jweil93** [googleapis/nodejs-bigquery#590]
#### Environment details

  - OS: Mac OS Mojave 10.14.6 / Google Chrome 78.0.3904.108
  - Node.js version: v12.13.1
  - npm version: 6.12.1
  - `@google-cloud/bigquery` version: 4.5.0

#### Steps to reproduce
I did something like
`
const {BigQuery} = require('@google-cloud/bigquery');
`
`
const options = //keyFilename ... etc;
`
`
const bigquery = new BigQuery(options);
`
`
...
`
`
const queryOptions = //something;
`
`
const [job] = await bigquery.createQueryJob(queryOptions);
`

And error shows
`
Unhandled Rejection (TypeError): fs.createReadStream is not a function
`

The error is caused by `GoogleAuth.getClient` in `google-auth-library` with
`
const filePath = path.resolve(this.keyFilename);
`
`
const stream = fs.createReadStream(filePath);
`

I tried to print out `typeof fs.createReadStream` in the function and it is `undefined`

I am running a react app initialized by create-react-app on Chrome.
Can someone tell me what I am doing wrong?

**Comment by callmehiphop** [comment]
@jweil93 this module was written to be used in Node.js, so unless you shim the `fs` module for the browser I don't think it is going to work.

**Comment by stephenplusplus** [comment]
@jweil93 unfortunately, our support for web and mobile-based environments is a work in progress. We have an issue tracking the request for web environments here: https://github.com/googleapis/google-cloud-node/issues/2933.
