### ISSUE TITLE
Storage API support

### ISSUE THREAD

**Issue by imathews** [googleapis/nodejs-bigquery#591]
Are there plans to support the BQ Storage API in Node (either via this library or another?) We're particularly interested in the column filtering capabilities, not to mention potential performance gains over the tabledata/list API endpoint.

@tswast I saw your comment on https://github.com/googleapis/nodejs-bigquery/issues/340#issuecomment-474145719 — would be more than happy to chat further about our use case and help with testing, etc.

**Comment by tswast** [comment]
We definitely plan to support the BigQuery Storage API in Node.js. Once the initial generation is done, it'll require some manual work (likely by @steffnay or @callmehiphop) to perform automatic reconnections and helpers for deserializing Avro/Arrow bytes, as we do in the Python client library.

**Comment by callmehiphop** [comment]
Assuming we'd be using gRPC for this, I might suggest creating a separate repo/module for it.

**Comment by meredithslota** [comment]
This is being worked on by @steffnay, no exact ETA yet, but it's in progress. :)

**Comment by steffnay** [comment]
@imathews This is now supported https://github.com/googleapis/python-bigquery-storage

**Comment by tswast** [comment]
Correct link: https://github.com/googleapis/nodejs-bigquery-storage
