### ISSUE TITLE
Labelling BigQuery jobs for other job functions other than createJob

### ISSUE THREAD

**Issue by hrgui** [googleapis/nodejs-bigquery#608]
**Is your feature request related to a problem? Please describe.**
As a developer, I'd like to label jobs so I can track it with an external ID for debugging purposes.

 **Describe the solution you'd like**
https://cloud.google.com/bigquery/docs/adding-labels#job-label
the API already has this via job.insert, would like this to be available in https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html#createQueryJob and the other job functions.

 **Describe alternatives you've considered**
Currently, we can only use createJob. (See https://github.com/googleapis/nodejs-bigquery/issues/608#issuecomment-573211487)

 **Additional context**
https://cloud.google.com/bigquery/docs/adding-labels#job-label

**Comment by callmehiphop** [comment]
We definitely could be doing a better job of supporting labels across the client, however technically it is possible to do via [`BigQuery#createJob`](https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html#createJob).

**Comment by hrgui** [comment]
@callmehiphop that is true - createJob does support that:

```js
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery();

const options = {
  configuration: {
    query: {
      query: "SELECT * FROM my_dataset.my_awesome_table",
    },
    labels: {
      "foo": "bar"
    }
  },
};

(async function() {
  const [job] =  await bigquery.createJob(options);
  console.log('job is done', job.metadata);
})();
```

job.metadata.labels does get applied.

**Comment by shaundowling** [comment]
Is it possible to add labels this way to `createQueryStream`?

**Comment by stephenplusplus** [comment]
Looking at the callstack, it should pass `query` all the way through:

- `bigQuery.createQueryStream()`
  - `bigQuery.query()`
    - `bigQuery.createQueryJob()`
      - `bigQuery.createJob()`

I don't believe there's more we have to do for this issue, but let me know if I'm mistaken.
