### ISSUE TITLE
dryRun option stopped working in 1.0.0

### ISSUE THREAD

**Issue by irri** [googleapis/nodejs-bigquery#62]
For some of my integration tests I utilize the `dryRun` option to make sure my query is syntactically correct while avoiding getting charged for the processing.

Upgrading from 0.9.6 to 1.0.0 gives me an error every time a execute a query with `dryRun` option enabled.

```
bq.query({
      query: queryString,
      useLegacySql: true,
      dryRun: true,
    });
```

testing with querystring: `SELECT * FROM publicdata.samples.natality LIMIT 5;` i get a really weird error:

```
  ErrorClass {
      code: 404,
      errors:
       [ { domain: 'global',
           reason: 'notFound',
           message: 'Not found: Job MY_PROJECT_ID:SOME_UUID' } ],
      response: undefined,
      message: 'Not found: Job MY_PROJECT_ID:SOME_UUID' }
```

with dryRun turned off, it all works as normal.

  - OS: mac
  - Node.js version: 8.9.1
  - npm version: 5.6.0
  - @google-cloud/bigquery version: 1.0.0

**Comment by stephenplusplus** [comment]
@callmehiphop could you do a quick dig into this one? If you don't have the time, please advise what you think might have caused this, and I can try to find a fix.

**Comment by tswast** [comment]
We had this issue in Java, too. https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2479#issuecomment-357113102

**Comment by callmehiphop** [comment]
@stephenplusplus sorry I must have missed this one.

`BigQuery#query` will create a job and then wait for it to be complete (unlike its counterpart `BigQuery#createQueryJob` which returns the job object). Setting `dryRun` to true will result in the backend not creating a Job, so when we attempt to listen for it to complete, we get a 404 because it doesn't actually exist.

My suggestion would be to either try and detect `dryRun` and if present do not listen for the complete event. Or else throw an error instructing users to use `createQueryJob` instead.

**Comment by tswast** [comment]
> My suggestion would be to either try and detect dryRun and if present do not listen for the complete event.

This would be my preference. I think it makes sense as a user to be able to run `query` with a dry run.

When you create a dry run query job, the API returns a resource which is "done" immediately. In Python we have a separate `job.result()` method for waiting to a job to finish. So long as the user avoids running that with a dry run query, everything is fine.

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/2f5ffb9fe13af772f670ea7bedd9722af6b79923/docs/bigquery/snippets.py#L1763-L1789

There are several potential problems with a dry run query.

1. As @callmehiphop has already said, there is no job resource created, so trying to get the job after it is returned will fail.
2. A call to `getQueryResults` will fail for similar reasons.
3. There are no result rows associated with a dry run. Instead, the job resource returned by the insert call is more interesting. It contains statistics such as the predicted bytes processed (corresponds to cost), so we'd want to make sure there's a way to get at that.

**Comment by irri** [comment]
Thanks! :)
