### ISSUE TITLE
Getting an error 'The destination table has no schema.' when using method .insert()

### ISSUE THREAD

**Issue by SilencerWeb** [googleapis/nodejs-bigquery#638]
As I can see in [your example](https://github.com/googleapis/nodejs-bigquery/blob/master/samples/insertRowsAsStream.js#L40), it is not required to pass options to make `.insert()` work. But in my case, I always get this error: `Error: The destination table has no schema.`. Could you, please, tell me why it works like that?

```js
const client = new BigQuery();
const data = [
  { 'name': 'Steve' },
  { 'name': 'John' },
  { 'name': 'Sara' },
  { 'name': 'Michael' },
];

client.dataset('dataset').table('table').insert(data);
```

**Comment by laljikanjareeya** [comment]
I have successfully reproduce the issue.

It is possible to create table with empty `schema` in `bigquery` and later you can add/update the `schema`.
In your case table has been created without/empty `schema`.

You should first create/update `schema` for table and than you can insert the records using above code.

Here is sample for [create table with schema](https://github.com/googleapis/nodejs-bigquery/blob/master/samples/createTable.js) and [update scheme](https://github.com/googleapis/nodejs-bigquery/blob/master/samples/relaxColumn.js).

**Comment by laljikanjareeya** [comment]
@SilencerWeb  Where you able to solve your issue with create/update table schema?

**Comment by SilencerWeb** [comment]
@laljikanjareeya nope. In the end, I went with generating CSV file out of my JSON data and load it into the table using `.load()` method.

Adding a schema to the table wasn't an option for me since objects had too many keys and some of them were auto-generated.

**Comment by armandoborge** [comment]
Updating the schema example fails with this error: 
"Provided Schema does not match Table datasetId.tableId. Field X has changed type from BOOLEAN to INTEGER"
