### ISSUE TITLE
Support access token authentication

### ISSUE THREAD

**Issue by kwent** [googleapis/nodejs-bigquery#68]
Hi,

I did some research about this topic but i did not find clear explanations about all the different authentication methods for `biquery` nodejs client.

In my understanding it's possible to authenticate only via a `service account`. I don't see any option to login with `Oauth` and pass an `access_token` anywhere.

Could you please clarify ? Thanks !

Regards

Edit: Found this related issue: https://github.com/googleapis/nodejs-common/issues/11

**Comment by stephenplusplus** [comment]
Closing as duplicate: https://github.com/googleapis/nodejs-common/issues/11

**Comment by kwent** [comment]
Following https://github.com/googleapis/nodejs-common/issues/11, is anything needs to be updated here ? Maybe some documentation ? Still have no idea how to pass the token here. Thanks !

**Comment by kwent** [comment]
Some guidance would be really helpful :)

**Comment by stephenplusplus** [comment]
Sorry! I have a PR to add docs (#83) and then we have to release (#82), and then it'll work!

If you want to check it out first, you can install from master:

```sh
$ npm install --save googleapis/nodejs-bigquery
```
```js
const BigQuery = require('@google-cloud/bigquery')
const bq = new BigQuery({ token: '...' })
```

**Comment by kwent** [comment]
Hi @stephenplusplus,

I have been playing with `https://developers.google.com/oauthplayground/` successfully with a token generated with scope `https://www.googleapis.com/auth/bigquery`.

Same token used in the library is raising exception below:

```js
{ ApiError
    at Object.parseHttpRespBody (/Users/kwent/Projects/popsql-core/node_modules/@google-cloud/common/src/util.js:193:30)
    at Object.handleResp (/Users/kwent/Projects/popsql-core/node_modules/@google-cloud/common/src/util.js:131:18)
    at /Users/kwent/Projects/popsql-core/node_modules/@google-cloud/common/src/util.js:496:12
    at Request.onResponse [as _callback] (/Users/kwent/Projects/popsql-core/node_modules/retry-request/index.js:195:7)
    at Request.self.callback (/Users/kwent/Projects/popsql-core/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/kwent/Projects/popsql-core/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
  code: 401,
  errors:
   [ { domain: 'global',
       reason: 'required',
       message: 'Login Required',
       locationType: 'header',
       location: 'Authorization' } ],
  response: undefined,
  message: 'Login Required' }
```

Here is my yarn.lock

```
"@google-cloud/bigquery@^1.2.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/@google-cloud/bigquery/-/bigquery-1.2.0.tgz#72bdf192d5376895c3520367719ed2d004545dc7"
  dependencies:
    "@google-cloud/common" "^0.17.0"
    arrify "^1.0.0"
    duplexify "^3.5.0"
    extend "^3.0.1"
    is "^3.0.1"
    stream-events "^1.0.1"
    string-format-obj "^1.0.0"
    uuid "^3.1.0"
```

My code:

```js
BigQuery.request({
  token: "my_token",
  uri: 'https://www.googleapis.com/bigquery/v2/projects',
}, (err, resp) => {
  if (!err) {
    resolve(resp.projects || []);
  } else {
    reject(err);
  }
});
```

The following is raising the same exception as well:

```
const conn = new BigQuery({token: "my_token", project_id: "my_project_Id"})
conn.getDatasets()
.then(([datasets]) => {
  console.log('datasets', datasets);
})
```

Any idea ? Regards

**Comment by kwent** [comment]
Thank you ! I'll try shortly

**Comment by leopragiclevero** [comment]
Hey @kwent and others, 

I am trying to do like this,
`const {BigQuery} = require('@google-cloud/bigquery')
const conn = new BigQuery({token:'my-token', projectId:'project-id'})
conn.getDatasets()
.then(([datasets]) => {
  console.log('datasets', datasets);
})`

Still, I'm getting an error like, 
`1. Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    2. Login Required.`

@kwent  how you managed to use access token with his client?

**Comment by MartinSahlen** [comment]
@leopragiclevero unfortunately this still seems to be broken but I managed to do to it like this:

```  
export type GoogleCredential =
  | OAuth2Client
  | JWT
  | Compute
  | UserRefreshClient
  | undefined;

const credential: GoogleCredential
const client = new BigQuery({
      projectId: 'my-project',
    });
client.authClient.cachedCredential = credential;```

Works for me  :D

**Comment by MartinSahlen** [comment]
In my case I'm using a `UserRefreshClient` and it works as expected.

**Comment by sd0m1n1ck** [comment]
I'll give this a try - Thanks a lot

**Comment by MaksimKiselev** [comment]
I want to add example of creating `UserRefreshClient` because creating it by constructor doesn't work:
```
const credentials = {
  type: 'authorized_user',
  client_id: 'xxx',
  client_secret: 'xxx',
  refresh_token: 'xxx',
}

const refreshClient = new UserRefreshClient()
refreshClient.fromJSON(credentials)

const client = new BigQuery({
  projectId: 'dev-e27b4097'
})
client.authClient.cachedCredential = refreshClient
```

See: https://github.com/googleapis/google-auth-library-nodejs/issues/770
