### ISSUE TITLE
Can't use BigQuery client locally

### ISSUE THREAD

**Issue by vincy261** [googleapis/nodejs-bigquery#682]
After doing all the configuration reported in https://cloud.google.com/bigquery/docs/authentication/service-account-file and verifying that internal library correctly find and parse the json file i get the attached error
![image](https://user-images.githubusercontent.com/16717435/80027761-819a3b80-84e4-11ea-9b4a-48d1869203fa.png)

I've tested the same function trough firebase remotely deployed and everything work.

**Comment by stephenplusplus** [comment]
Could you share the code that's failing?

This works locally for me:

```js
'use strict'

const {BigQuery} = require('@google-cloud/bigquery');

const options = {
  keyFilename: '/Users/stephen/dev/key.json',
  projectId: 'nth-circlet-705',
};

const bigquery = new BigQuery(options);

bigquery.getDatasets(console.log);
```

**Comment by vincy261** [comment]
> Could you share the code that's failing?
> 
> This works locally for me:
> 
> ```js
> 'use strict'
> 
> const {BigQuery} = require('@google-cloud/bigquery');
> 
> const options = {
>   keyFilename: '/Users/stephen/dev/key.json',
>   projectId: 'nth-circlet-705',
> };
> 
> const bigquery = new BigQuery(options);
> 
> bigquery.getDatasets(console.log);
> ```

that's my code:

```ts
import { BigQuery } from '@google-cloud/bigquery'

export async function bigQueryPoc() {

  // tslint:disable-next-line: no-commented-code
  const bqOptions = {
    keyFilename: './key.json',
    projectId: 'demo',
  }
  const bigquery = new BigQuery(bqOptions)
  // Queries the U.S. given names dataset for the state of Texas.

  const query = `SELECT *
  FROM \`firestore_export.demo_changelog\`
  LIMIT 10`

  const options = {
    query,
    // Location must match that of the dataset(s) referenced in the query.
    location: 'US',
  }
  // Run the query as a job
  const [job] = await bigquery.createQueryJob(options)
  console.log(`Job ${job.id} started.`)

  // Wait for the query to finish
  return job.getQueryResults()
}
```

**Comment by stephenplusplus** [comment]
A couple thoughts:

- Could you try running outside of an emulator to see if it works?
- To help me get up and running more quickly, could you provide further instruction on how to replicate your environment? A condensed version of your app that I can clone and easily run to experience the behavior you're seeing.

Thank you!

**Comment by fr-esco** [comment]
Same problem on Windows 10.0.18363.778

**Comment by meredithslota** [comment]
@fr-esco Can you share the code that's failing for you? We still haven't been able to repro this, and have not received additional info yet.
