### ISSUE TITLE
Improve Security: Allow authentication via RAW JSON credentials rather than json file path

### ISSUE THREAD

**Issue by grichmond** [googleapis/nodejs-bigquery#684]
We would like to be able to authenticate our function that uses nodejs via a service account. However, from our investigation, the nodejs library for bigquery only supports specifying a credentials json file path, not the actual json content. This means that we would need to include the json credentials IN the source code - not a great idea for security given that these credentials give access to our entire database. Is there any way to authenticate the nodejs bigquery library without having a physical json file? There are comments about this functionality being lost and I've dug into the code and can't see a way to get past this? It seems like a big security hole.

Ideally, what would be useful is instead of using an environment variable to specify the credentials path, if we could instead pass the actual json for the credentials in here (or pass via the constructor as an alternative), that will allow us to use tools such as AWS secrets to keep the credentials secure. This appears to be an option in the Google Auth library, but it just hasn't been used in the BigQuery client library.

**Comment by stephenplusplus** [comment]
The `credentials` object! As far as I know, that still works. It's been a critical option we've supported since day 1.

```js
new BigQuery({credentials: require('./key.json')})
```

> This appears to be an option in the Google Auth library, but it just hasn't been used in the BigQuery client library.

The auth library receives the input from the BigQuery constructor and determines the correct auth mechanism to use. 'credentials' always wins.

Could you give this a try and report back? Sorry for the trouble.

**Comment by grichmond** [comment]
Hi Stephen, 

Works perfectly, thank you! Can I suggest adding this to the documentation? I searched everywhere and even google cloud support didn't have the answer. As an example, I used this successfully:

new BigQuery({projectId: "yourprojectid",credentials: {yourjsonobject}});
