### ISSUE TITLE
Timeouts on /insertAll and auth token refresh

### ISSUE THREAD

**Issue by dackmin** [googleapis/nodejs-bigquery#696]
Hey guys!

Since we updated `@google-cloud/bigquery` from `v4.1.8` to `v4.7.0` I'm experiencing regular (everyday, around 8:30 AM CET, until 11:00 AM CET) timeouts from BigQuery streaming inserts:

```
Could not refresh access token: network timeout at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery
```

And:

```
Response timeout while trying to fetch https://bigquery.googleapis.com/bigquery/v2/projects/xxxxx/datasets/xxxxx/tables/xxxxx/insertAll (over 60000ms)
```

We don't have any scheduled cron tasks whatsoever, and the only "breaking" change I can notice in `@google-cloud/bigquery` between those two versions is the root url (#531).

Is there any `timeout` option to set the `60000`ms timeout to something smaller for `table.insert()`? I can't seem to find anything in the docs and the only issue from the parent repo is referencing something from `v1` so I assume this is not up-to-date.

I'll try to downgrade to `v4.1.8` to check if the issue still occurs.

#### Environment details

  - OS: App Engine default Node flexible os (debian or cos I presume)
  - Node.js version: 10.18.1
  - npm version: 6.13.4
  - `@google-cloud/bigquery` version: 4.7.0

#### Steps to reproduce

```javascript
await dataset
  .table('table')
  .insert([{ id: 'test', name: 'test' }]);
```

Thanks a lot!

**Comment by dackmin** [comment]
I can confirm the issue is gone with `v4.1.8`. Is there any quota change when streaming requests go to `bigquery.googleapis.com` instead of `www.googleapis.com`?

**Comment by meredithslota** [comment]
`bigquery.googleapis.com` is the correct host - please use that :) If you are still encountering issues please reopen.
