### ISSUE TITLE
Typo in partitioningMetadata Example script

### ISSUE THREAD

**Issue by toninofox** [googleapis/nodejs-bigquery#697]
The parameter used in the example below has the capital S. It should be `expirationMs` as per documentation, otherwise it will be ignored

https://github.com/googleapis/nodejs-bigquery/blob/99aad917629575c9d8d472a0d19e088315542b02/samples/createTablePartitioned.js#L39

**Comment by mattshen** [comment]
Hi there, 

I see GCP official docs still has the typo. 
https://cloud.google.com/bigquery/docs/creating-column-partitions#node.js

How can we get GCP team's attention to fix it. It costs me about 30 mins to figure it out.
