### ISSUE TITLE
bigQuery.createQueryStream with null value crashes the process

### ISSUE THREAD

**Issue by m-ronchi** [googleapis/nodejs-bigquery#707]
**Environment details**
- OS: linux (node:12-alpine Docker image) and osx
- Node.js version: 12.16.3
- npm version: 6.14.4
- @google-cloud/bigquery version: 4.7.0

Steps to reproduce:

```ts
const pipeline = require("util").promisify(require("stream").pipeline);
const bq = new BigQuery({...});
const date = null; // should be a date object, but was null
const query = bq.createQueryStream({
      query: `select *
      from .....
      where _PARTITIONTIME <= @date`,
      params: { date },
    });
await pipeline(query, myWritableStream);
```

note: date being null was unexpected

expected result:
- createQueryStream raises `Error: Type must be provided for null values.`
- error is propagated from createQueryStream to pipeline to my code, where I can `catch` it

actual result:
- error is thrown asynchronously on the nodeJS event loop and the process crashes with uncaught error

**Comment by bcoe** [comment]
@m-ronchi what happens if you were to do this:

```js
const pipeline = require("util").promisify(require("stream").pipeline);
const bq = new BigQuery({...});
const date = null; // should be a date object, but was null
try {
const query = bq.createQueryStream({
      query: `select *
      from .....
      where _PARTITIONTIME <= @date`,
      params: { date },
});
await pipeline(query, myWritableStream);
} catch (err) {
  console.info(err);
}
```

If the error for the statement on the right-hand side of the await isn't caught, then it would bubble as an uncaught exception.

**Comment by m-ronchi** [comment]
hi,
I already catch at an upper level of my code, with logging and reporting. that is not triggered

**Comment by stephenplusplus** [comment]
Ah ha! PR sent to fix this: https://github.com/googleapis/nodejs-paginator/pull/236

Thank you for your patience @m-ronchi.

**Comment by stephenplusplus** [comment]
New installations of @google-cloud/bigquery will receive the fix for this issue. The error should come through as an error event on the stream, so no try/catch should be required. Please let me know if you have any issues after updating.
