### ISSUE TITLE
Unable to run load job to a different project ID when using local file

### ISSUE THREAD

**Issue by bachase** [googleapis/nodejs-bigquery#719]
It appears the approach mentioned in #26 does not work with the current version of the library (4.7.0). That is, the code below does not appear to properly change the `projectId` of the destination table.
```js
table.load('test.csv', {
  destinationTable: {
    projectId: 'test-override'
  }
})
```

Looking at the implementation https://github.com/googleapis/nodejs-bigquery/blob/92599f98bf50b2c0e4daf1082e05454478d3c6bb/src/table.ts#L1376-L1382
it looks like the `extend` is overwriting any user provided metadata around the `destinationTable`. Should that be reversed?

**Comment by vcealicu** [comment]
Yep, this change would fix it. Not really keen on doing a pull request.
