### ISSUE TITLE
Allow to stream compressed data into BigQuery

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigquery#75]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2811

<a href="/xgalen"><img src="https://avatars2.githubusercontent.com/u/1334716?s=88&v=4" height=44 width=44 align=left></a>@xgalen<br>March 20, 2018 3:19 PM

Hi all,

In order to save data transfer (out) costs, we would want to stream the data compressed with gzip.

I have made some tries and it works, requesting directly to the API. Example (omitting values for the sake of simplicity):

```
#!/bin/bash

...

OBJECT="{'kind': 'bigquery#tableDataInsertAllRequest', 'skipInvalidRows': true, 'ignoreUnknownValues': true, 'rows': $ROWS}"

echo $OBJECT | gzip -cf > compressed.gz

curl -v -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: text/plain" \
     -H "Content-Encoding: gzip" \
     --data-binary @compressed.gz \
"https://www.googleapis.com/bigquery/v2/projects/$GOOGLE_CLOUD_PROJECT/datasets/$DATASET_ID/tables/$TABLE_ID/insertAll"
````

But I couldn't find where to set the header to change the content-encoding to gzip. I know it's an option to the responses and to store files ( https://github.com/googleapis/nodejs-bigquery/blob/fbe4f93f9167e904ee9d0beaf27f0d0b9da6d7bb/src/table.js#L728 ) but no for requesting.

Is it possible to add a new setting to allow compress or not? In that case, the responsibility of the compression is for the server, not for this module. I think it would be worth :)

Of course, I could help if needed.

Thanks!

Alfredo

**Comment by stephenplusplus** [comment]
This request makes sense! Here's a quick way you can implement this now for `table.insert()`:

```js
const zlib = require('zlib')

table.interceptors.push({
  request: function(reqOpts) {
    if (reqOpts.uri.indexOf('/insertAll') > -1) {
      const reqBody = new Buffer(JSON.stringify(reqOpts.json))
      const reqBodyGzip = zlib.gzipSync(reqBody)
      reqOpts.headers = reqOpts.headers || {}
      reqOpts.headers['content-encoding'] = 'gzip'
      reqOpts.body = reqBodyGzip
      delete reqOpts.json
    }

    return reqOpts
  }
})
```

For `table.insert()`, `table.createWriteStream()`, and `table.load()`, we have a few options:

- Automatically compress the input
- Accept a flag that instructs us to compress the input
- Accept a flag that instructs us to set the content-encoding, and let the compression be handled by the user

If possible, I would lean towards always compressing, and allowing the user to disable it if they know better (when they don't want the compression for some reason, or they already know they are giving compressed input). That option could be `autoGzip` which would be true by default.

Am I missing any other methods which could use this feature, or reasons this wouldn't be a good idea? 

@callmehiphop @alexander-fenster

**Comment by xgalen** [comment]
I can think two reasons to not enable compression by default:

a) The increment of the CPU's usage.
b) The delay caused by the process (compression by the server and decompression by BigQuery).

But I think for the user is worth the saving he/she could get compressing data.

**Comment by xgalen** [comment]
Are there some news about this? :D

**Comment by stephenplusplus** [comment]
I wouldn't mind hearing input from the other guys, @callmehiphop and @alexander-fenster, on this.

**Comment by callmehiphop** [comment]
I don't have much of an opinion on this, compressing seems like it should be fine. Do we have a timeline on when this API will be converted to gRPC? If that's anywhere on our radar then this might end up being a wasted effort (I think?)

**Comment by xgalen** [comment]
Ping @stephenplusplus

**Comment by stephenplusplus** [comment]
@callmehiphop I don't think BigQuery is available through gRPC, but I could be mistaken. @alexander-fenster comments on that / this issue's proposal?

**Comment by alexander-fenster** [comment]
Contacted the BigQuery team.

**Comment by alexander-fenster** [comment]
Cc: @crwilcox, @jonparrott for awareness as well

**Comment by crwilcox** [comment]
Thanks @alexander-fenster . I would be for adding compression support but leaving it off by default. For certain payloads/scenarios it could be advantageous. Do we have instances already that compress clientside and decompress serverside on other client libs?

**Comment by simllll** [comment]
It's a while, is this feature in the meantime on the roadmap?

**Comment by Martinlcksybo** [comment]
I cant load compressed data into big query using .load function, any suggestions?

**Comment by stephenplusplus** [comment]
> the documentation everywhere says is supported but no example

@Martinlcksybo could you link to the docs that say this?

> It's a while, is this feature in the meantime on the roadmap?

It sounds like we all want the feature, we just haven't implemented it yet. If there is any interest in getting this in, a PR would be very helpful!

**Comment by meredithslota** [comment]
We aren't going to implement this in the clients as a different solution is in the works. Streaming will have an entirely new API.
