### ISSUE TITLE
Make keyfilename authentication more consistent with other Node libraries

### ISSUE THREAD

**Issue by sofisl** [googleapis/nodejs-bigquery#799]
This issue is related to our work in client extensible options. 

Other Node libraries are able to authenticate using just a keyfileName in the constructor of the client. However, it is required to add a project_id variable in the constructor to authenticate, like so:

```
new BigQuery({
    keyFilename: //keyfile
    projectId: 
      process.env.GOOGLE_CLOUD_PROJECT  
  });
```
In order to be more consistent across libraries/requirements, it would be nice if we could get the project id from the keyfile itself, without having to declare it separately.

 I think this work might be similar to this PR: https://github.com/googleapis/nodejs-pubsub/pull/731

**Comment by stephenplusplus** [comment]
> it is required to add a project_id variable in the constructor to authenticate, like so:

Where is it required? We historically haven't ever thrown in a constructor, for example, or required it in any way. If we need a project ID as part of an API request we need to make for the user, our libraries will either:

- use a project ID placeholder token: `{{projectId}}`, then code in "@google-cloud/common" will replace those tokens with the project ID it pulls from the auth library (`google-auth-library`)
- before each API request, we pull the project ID from the auth library before we send the request

In all cases, the auth library is where the project ID detection comes from, following a certain order of preference.

**Comment by sofisl** [comment]
Ah! I'm sorry, it's an important detail to say that this was revoking authentication (```gcloud auth revoke```) and unsetting the gcloud project. We did this in order to test the authentication method of just the keyfilename. 

Steps to reproduce:

1. gcloud auth revoke
2. gcloud config unset project
3. Expect this error: ```Error: Unable to detect a Project Id in the current environment.```

I guess my issue is more directly related to, why can't we get the project ID from the keyfile itself instead of adding it additionally as an environment variable?

**Comment by stephenplusplus** [comment]
Ah, gotcha! That should actually be happening already: https://github.com/googleapis/google-auth-library-nodejs/blob/e11e18cb33eb60a666980d061c54bb8891cdd242/src/auth/googleauth.ts#L176. `getFileProjectId()` will try to read the `keyFilename` JSON file, then get the project ID from it. It looks like this could be a bug over there.

**Comment by bcoe** [comment]
@stephenplusplus @sofisl what's weird, is I think you were noticing the project is appropriately detected in our auto generated libraries? which share the auth library.

@sofisl when we eventually dig into this, we might want to use [npm link](https://docs.npmjs.com/cli/link) to test bigquery and the auth library at the same time.

**Comment by sofisl** [comment]
Closing in lieu of #1084 in google-auth-library-nodejs.
