### ISSUE TITLE
appending data to table deletes labels

### ISSUE THREAD

**Issue by maxwell8888** [googleapis/nodejs-bigquery#805]
#### Environment details

  - OS: MacOS
  - Node.js version: 10
  - npm version: 6.9
  - `@google-cloud/bigquery` version: 4.7

#### Steps to reproduce
Appending data to an existing table with a label, will delete label.

1. Add label to table in BigQuery web UI
2. Append data to table using:
```js
const bigquery = new BigQuery();

const metadata = {
      sourceFormat: "NEWLINE_DELIMITED_JSON",
      autodetect: true,
      writeDisposition: "WRITE_APPEND",
};
const [job] = await bigquery
      .dataset("dataset")
      .table("tablename")
      .load("example.json", metadata);
```

**Comment by laljikanjareeya** [comment]
@maxwell8888  I tried with above given steps and mentioned version, but I could not reproduce it.

**Comment by stephenplusplus** [comment]
I wasn't able to reproduce this either using 4.7 or the latest release. I'm going to close for now, but if the issue still exists, please provide further instruction on how we can more accurately represent your environment in which you're seeing the failure.
