### ISSUE TITLE
Operation works even if  the Private key is different

### ISSUE THREAD

**Issue by Dsiddhesh** [googleapis/nodejs-bigquery#826]
Hi Team,

We are integrating with Big query using Node js and we are initializing BigQuery client inline like below
`const bigqueryClient = new BigQuery({
  projectId: 'bigqueryproject1',
  credentials: {
    client_email: "dev1@account.com",
    private_key: " <-----abcd...------>"
  },
});`
while testing we observed that even if we replace 2-3 characters from Valid key with some other Characters then we don't get any error, functionality works successfully.  If we  alter about 8 characters then we get Base64 related error. Please let us know if this is expected behavior. 
Note : If we change Key format, i.e. removed leading and trailing "----" or add extra characters to the key then we get error.

**Comment by steffnay** [comment]
@bcoe and @JustinBeckwith do you have some ideas about about what's going on here?

**Comment by steffnay** [comment]
@Dsiddhesh there are several characters that can be changed that aren't part of the key, such as comments. Can you provide some specific examples of what was changed or the code you used to modify the key?

**Comment by Dsiddhesh** [comment]
Hi, I tried changing characters inside key (i.e. letters and numbers) e.g. if   some text in key is WU8fhHPSKlJeByqrs9v then i just changed it to WU8fhHPSKlJeByqrs**8e**.

**Comment by steffnay** [comment]
@Dsiddhesh based on the information you've provided, it seems likely that the value of the certificate remains because the characters that have been changed are not part of a significant portion of the signature.

**Comment by Dsiddhesh** [comment]
Ok, I thought there is validation to compare  service account email and key.

**Comment by steffnay** [comment]
@Dsiddhesh There is, but it is likely that each of the characters in the key is not necessarily relevant for the validation. So it appears that there is still enough information remaining in the key to perform the validation, even when you change those characters.

**Comment by stephenplusplus** [comment]
I can imagine it would be quite shocking to feel as though you're tricking authorization so easily. Fortunately, it looks like it's just not an essential part of the key. Thank you for raising your concerns, and please let us know if you notice anything else that doesn't seem right.
