### ISSUE TITLE
Updating expirationTime deletes the Table

### ISSUE THREAD

**Issue by Dsiddhesh** [googleapis/nodejs-bigquery#838]
Hi Team,

We are using Node library for integration. We observed that when we update 'expirationTime' of a Table to value say 10, 30 , 300, 365 or 5000 , the Table gets deleted. On UI when we go to access the Table we see message 'Not found: Table bigqueryproject1-279307:dataset1.testmax1' . 
When we update value of 'expirationTime' to max i.e. '9223372036854775807' we see that Table is retained but we see blank value of 'expirationTime' property.

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce the "expirationTime" not existing:

```js
console.log(await table.exists()); // [true]
await table.setMetadata({expirationTime: '9223372036854775807'});
const [metadata] = await table.getMetadata();
console.log(metadata.expirationTime); // '9223372036854775807'
```

Could you modify this code if I've made a mistake?

> We observed that when we update 'expirationTime' of a Table to value say 10, 30 , 300, 365 or 5000 , the Table gets deleted. 

That appears to be the intended effect, since "expirationTime" is meant to state the time when it expires, and "10" has already passed :)

> **options.expirationTime** The time when this table expires, in milliseconds since the epoch. If not present, the table will persist indefinitely. Expired tables will be deleted and their storage reclaimed.

**Comment by Dsiddhesh** [comment]
Hi @stephenplusplus  could you please try from REST API  
![image](https://user-images.githubusercontent.com/56438009/89810742-2b1c4000-db5b-11ea-985a-f0bf0c1b0409.png)

**Comment by stephenplusplus** [comment]
It actually worked for me there, too. Maybe you could provide more exact steps to reproduce, and we can see where we are going wrong?

**Comment by Dsiddhesh** [comment]
Hi here are exact steps. Create a dataset with 'Default table expiration' as never. Create a Table with in it, check details of Table, ensure 'expiration time' is never,  Now try to update  expiration time of the table using REST API to 25920000000 and then go to Table and we see error that Table has been deleted.

**Comment by meredithslota** [comment]
I might be doing the calculation wrong but I think "25920000000" in milliseconds is sometime in 1970 if we are using the definition above (milliseconds after the epoch). So what I think might be happening is you are updating the expiration time to a time that has already passed so the table expires and is deleted immediately. 

Can you try a larger value here, e.g. using the millisecond time for a few minutes or hours in the future, for testing purposes? I'm using https://www.epochconverter.com/ to get this info. A common error is using seconds instead of milliseconds, in seconds that number is far far in the future.

**Comment by Dsiddhesh** [comment]
Hi, I tried to enter this time but Table got deleted. I assume its valid case that user will update expiry date to 2 years ahead
![image](https://user-images.githubusercontent.com/56438009/89986598-6709ef00-dc9a-11ea-929a-9d477cce82a7.png)

**Comment by stephenplusplus** [comment]
That value is in seconds, and the API needs milliseconds. So simply add "000" to the end, and you're in business!

```js
// Before:
new Date(1610000000)
// Mon Jan 19 1970 10:13:20 GMT-0500 (Eastern Standard Time)

// After:
new Date(1610000000000)
// Thu Jan 07 2021 01:13:20 GMT-0500 (Eastern Standard Time)
```

Let me know if this does not resolve the issue.

**Comment by Dsiddhesh** [comment]
Thanks @stephenplusplus , Its working.
