### ISSUE TITLE
Support List Projects

### ISSUE THREAD

**Issue by kwent** [googleapis/nodejs-bigquery#84]
Hi,

Would be nice if the library could have a method to list the projects. 

- Cf. https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/list

Regards

**Comment by stephenplusplus** [comment]
As a quick workaround:

```js
bigquery.request({
  uri: 'https://www.googleapis.com/bigquery/v2/projects'
}, function(err, resp) {
  if (!err) {
    const projects = resp.projects
  }
});
```

**Comment by callmehiphop** [comment]
BQ team has advised us not to support this, but instead to redirect users to the [resource](https://github.com/googleapis/nodejs-resource) client instead.
