### ISSUE TITLE
Make insertId available to set

### ISSUE THREAD

**Issue by Crispy1975** [googleapis/nodejs-bigquery#840]
When making streaming inserts into BigQuery datasets it would be good to have the option of defining the `insertId` that is available in the API clients to help with reduplication of record inserts.

**Comment by stephenplusplus** [comment]
Hello, @Crispy1975. Which method are you using to perform streaming inserts?

**Comment by Crispy1975** [comment]
Hi @stephenplusplus we are using the `table.insert()` method. Here is a simple example TypeScript class method:
```javascript
async insertRows(tableId: string, writeData: ObjectStringAny, dataset: string, options: ObjectStringAny): Promise<ObjectStringAny> {
    const table = this.client.dataset(dataset).table(tableId);
    const result = await table.insert(writeData, options);
    return result;
}
```
The `writeData` object is an array of objects, but generally only has a single row being written, and options is currently an empty object. The BigQuery client is referenced with `this.client`.

**Comment by Crispy1975** [comment]
Digging into the library code I can see that the automatic creation of the `insertId` can be disabled here: https://github.com/googleapis/nodejs-bigquery/blob/master/src/table.ts#L72

What isn't obvious is how I can go about setting my own `insertId` to aid in streaming buffer deduplication.

**Comment by steffnay** [comment]
We're not going to add this option because we're anticipating a new streaming API that better handles deduplication.
