### ISSUE TITLE
Using Nodelibrary we can load/export data from/to bucket which lies in different region then Dataset

### ISSUE THREAD

**Issue by Dsiddhesh** [googleapis/nodejs-bigquery#842]
Hi Team,

[Documentation ](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage#data-locations) mentions that  If your dataset is in a regional location, your Cloud Storage bucket must be a regional bucket in the same location. For example, if your dataset is in the Tokyo region, your Cloud Storage bucket must be a regional bucket in Tokyo.

We tried this scenario from BigQuery admin UI . Bucket lies in us-east1 (South Carolina)  and Dataset in Tokyo. We got proper error 'Cannot read and write in different locations: source: us-east1, destination: asia-northeast1' . 
But we are able to do the same operation successfully  using node library.  We could see Table and its data content using admin ui.

Similar to this, we could export file from EU region to a bucket in US-east.

**Comment by steffnay** [comment]
@Dsiddhesh please provide an example of the code you are using & its output, including verification of the resources' locations & the success of extract job, eg:

```
const [bucketData] = await storage.bucket(bucketName).getMetadata();
console.log(`Bucket location: ${bucketData.location}`);
const [datasetData] = await bigquery.dataset(datasetId).getMetadata();
console.log(`Dataset location: ${datasetData.location}`);

const [job] = ...your code...
console.log(`Job status: ${Job.status.state}`)
```
