### ISSUE TITLE
Auto-retry job creation occasionally fails if job was created on first request

### ISSUE THREAD

**Issue by BenBirt** [googleapis/nodejs-bigquery#857]
1) Is this a client library issue or a product issue?
It's a client library issue.

2) Did someone already solve this?
No, but someone did solve this in the associated Java client library:
- issue: https://github.com/googleapis/google-cloud-java/issues/2867
- fix: https://github.com/googleapis/google-cloud-java/pull/2887

3) Do you have a support contract?
No

#### Steps to reproduce

1. issue a job create request, leaving the library to choose a random ID, and leaving `autoRetry` on
2. occasionally the request will fail, and thus will be retried,
3. however the job will have actually been created in BigQuery, and the retry will fail with an error: `bigquery error: Already Exists: Job <id>`

The Java client library also had this issue, but was fixed in https://github.com/googleapis/google-cloud-java/pull/2887 by getting the relevant job if job creation failed due to this error (and if the job ID was randomly generated by the client library).

**Comment by meredithslota** [comment]
Added label types based on corresponding Java issue, as best guess. :)

**Comment by stephenplusplus** [comment]
@BenBirt Thanks for the issue. PR sent in #864. Would you mind taking a look?
