### ISSUE TITLE
Support user-provided job ID for all job types

### ISSUE THREAD

**Issue by tswast** [googleapis/nodejs-bigquery#86]
I got the following feedback from a user in the docs. https://cloud.google.com/bigquery/docs/running-jobs

> include a disclaimer here for nodejs ... no matter what we assign to this in a configuration resource object, the returned jobReference.jobId is always one created by the service, not the one supplied.

I believe all other languages have a `jobId` and `jobPrefix` parameter for all job types, which allows using a manually-specified job ID or a prefix for a randomly-generated job ID.

**Comment by callmehiphop** [comment]
We definitely support `jobPrefix` but I don't think we've ever had support for `jobId` (@stephenplusplus  can you confirm?)

**Comment by stephenplusplus** [comment]
No, we haven't. Looks like we need to, though!
