### ISSUE TITLE
Support Job labels

### ISSUE THREAD

**Issue by BenBirt** [googleapis/nodejs-bigquery#863]
**Is your feature request related to a problem? Please describe.**
BQ JobConfiguration API objects have labels (https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfiguration). I'd like to be able to set them using this client library.

 **Describe alternatives you've considered**
I don't think there are alternatives beyond (a) using a different language or (b) issuing raw API requests.

 **Additional context**
I'm happy to contribute this change. As per https://github.com/googleapis/nodejs-bigquery/blob/master/CONTRIBUTING.md I'm filing an issue explaining the change.

I suggest implementing this in much the same way as `dryRun`:
- the `Query` type would have a new field `labels: { [label: string]: string }`: https://github.com/googleapis/nodejs-bigquery/blob/1e56383da5/src/bigquery.ts#L87
- this would be passed through to the final `Job` in exactly the same way as `dryRun`: https://github.com/googleapis/nodejs-bigquery/blob/1e56383da5/src/bigquery.ts#L1254

I'm happy to make this change, as per https://github.com/googleapis/nodejs-bigquery/blob/master/CONTRIBUTING.md are you folks happy with me sending a PR?

**Comment by stephenplusplus** [comment]
@BenBirt thank you very much for the issue and offering your help! A PR would be great!
