### ISSUE TITLE
Error when using the LIKE operator or REGEXP_CONTAINS

### ISSUE THREAD

**Issue by dmarshall83** [googleapis/nodejs-bigquery#875]
When I try to run a query that includes the LIKE operator or using REGEXP_CONTAINS I get an error. Below is some test code that does not work. If I remove the WHERE clause then it works fine. 

```
const options = {
    query: "SELECT * FROM qa_claims.product WHERE product_code LIKE '115%' OR product_code LIKE '116%'",        
    location: "US",
};

const [rows] = await bqclient.query(options);
console.log('rows', rows)
```

I get the following error for that query:

> UnhandledPromiseRejectionWarning: Error: No matching signature for operator LIKE for argument types: STRUCT<product_code STRING>, STRING. Supported signatures: STRING LIKE STRING; BYTES LIKE BYTES at [1:44]

  - OS: Windows 10
  - Node.js version:
  - npm version: v12.18.3
  - `@google-cloud/bigquery` version: ^4.7.0

#### Steps to reproduce

  1. Run a query using the LIKE operator.

**Comment by steffnay** [comment]
The error is saying that the 'product_code' column is a STRUCT type that contains a field named 'product_code', which is type STRING. So the problem with the query is that you cannot use the LIKE operator to compare STRUCT with STRING.

I think this should work: 
```
const options = {
    query: "SELECT * FROM qa_claims.product WHERE product_code.product_code LIKE '115%' OR product_code.product_code LIKE '116%'",        
    location: "US",
};

const [rows] = await bqclient.query(options);
console.log('rows', rows)
```

**Comment by dmarshall83** [comment]
@steffnay Where would it be set up as a STRUCT type if I look at that table it is set up as a string based on the schema

![image](https://user-images.githubusercontent.com/18427473/96039603-ecdf1d80-0e36-11eb-91d2-070b30980c36.png)

I'm sure that I'm misunderstanding something fundamental about how the tables are set up but this is the first time I have run into this issue. Also, that exact same query runs fine if I do it from the query editor in bigquery.

**Comment by steffnay** [comment]
oh, looking at your screen cap, it looks like the name of your table is 'product_code' rather than 'product'.  I am wondering if you are accidentally querying a table called 'product', in which the 'product_code' column is STRUCT, creating this error. Are you intending to be querying the table in the screen cap? If so, the query should be `"SELECT * FROM qa_claims.product_code WHERE product_code LIKE '115%' OR product_code LIKE '116%'"`

**Comment by dmarshall83** [comment]
I understand that I caused some confusion with the code that I put in the request. It should have been "SELECT * FROM qa_claims.product_code WHERE product_code LIKE '115%' OR product_code LIKE '116%'" that was just a typo in my message. I have checked and the SQL that I'm running is "SELECT * FROM qa_claims.product_code WHERE product_code LIKE '115%' OR product_code LIKE '116%'". I'm still getting that issue. I could replace those tables/fields with others and I still get the same issue. I have a series of tables that are just unique values from a much larger table in order to populate some dropdown in an interface.  They all have one column that is the same name as the table name.

**Comment by steffnay** [comment]
@dmarshall83 and you have confirmed that you get the same error with the query this way: `"SELECT * FROM qa_claims.product_code WHERE product_code.product_code LIKE '115%' OR product_code.product_code LIKE '116%'"?

**Comment by dmarshall83** [comment]
Ok I feel really stupid because this worked:
"SELECT * FROM qa_claims.product_code WHERE product_code.product_code LIKE '115%' OR product_code.product_code LIKE '116%'"

However, this one does not: 
"SELECT * FROM qa_claims.product_code WHERE product_code LIKE '115%' OR product_code LIKE '116%'"

I have run other queries without the table name in front of the field, but it does not seem to work now. Thanks for the help, I'm sorry if I wasted your time.

**Comment by steffnay** [comment]
@dmarshall83 No worries! Normally you don't use 'table.column' syntax here, but you do need to if table and column have the same name.
