### ISSUE TITLE
Exception not thrown on syntax error

### ISSUE THREAD

**Issue by jamesholcomb** [googleapis/nodejs-bigquery#887]
#### Environment details

  - OS: MacOS 
  - Node.js version: 12.18
  - npm version: 6.14.4
  - `@google-cloud/bigquery` version: 5.3.0

#### Steps to reproduce

```js
  it("throws on bigquery syntax error", async () => {
    const bq = new BigQuery({ projectId: "REDACTED" })

    const [job] = await bq.createQueryJob({
      query: `DECLARE foo DEFAULT ( SELECT 1 );
      SELECT 1 FROM XYZ`,
      timeoutMs: 5000,
      location: "US"
    })

    const [rows] = await job.getQueryResults()

    assert.strictEqual(rows.length, 0)
  })
```

Expected result:

Invalid value: Table name "XYZ" missing dataset while no default dataset is set in the request. at [2:1]

Actual result
No exception is thrown, rows.length = 0

**Comment by stephenplusplus** [comment]
Thanks for the report. How do you usually make this call when you receive that error? A quick search showed that error reported a table is created: https://copycoding.com/d/bigquery-error-table-name-xyz-missing-dataset-while-no-default-dataset-is-set-in-the-request-at-x-y

**Comment by jamesholcomb** [comment]
Hi the table name is irrelevant. It was a trivial example to show that the sql contains a syntax error but an exception is _not_ thrown.  Taking out the DECLARE will cause an exception...so it may be related to that.

**Comment by stephenplusplus** [comment]
Is everything working as intended then? The example from your first post didn't end up being invalid in terms of syntax, it just didn't return results. When we pop a syntax error in there, it throws as expected.

**Comment by jamesholcomb** [comment]
The example has a syntax error because table XYZ does not exist.

**Comment by stephenplusplus** [comment]
I believe a syntax error is one in the formatting of the query. The `XYZ` error is apparently being processed and the fact that the table does not exist is being ignored by the server. We just pass along what they give us, good or bad. Do you expect an error there based on experience with another library or way of calling the API?

**Comment by jamesholcomb** [comment]
It should generate an error in JS.  Pasting the query into the BigQuery web console generates an error.  Removing the DECLARE statement causes the JS to throw an exception.

![image](https://user-images.githubusercontent.com/362729/98022651-7c8b4280-1dcb-11eb-8004-ad8db3402706.png)

**Comment by ro8inmorgan** [comment]
I actually have a similar problem but not with table name but with an incorrect field name. There's no error thrown, just an empty result. In the Google Console the job did error.

**Comment by steffnay** [comment]
The issue here is that scripting statements like this generate child jobs for each statement. When you call `job.getQueryResults` using the original parent job, what's returned is the result of the last statement that executed. So, in the case of your example, it returns the empty results from the `DECLARE` statement's execution.

To obtain the results of all statements in the script, you must enumerate the child jobs and call `jobs.getQueryResults` on each of them. You can access the list of child jobs by setting the `parentJobId` option in a `bigquery.getJobs` call.

Here is how you would access the error from the `SELECT` statement:

 ```
 const bq = new BigQuery({ projectId: "REDACTED" });

  [job] = await bq.createQueryJob({
    query: 
    `DECLARE foo DEFAULT ( SELECT 1 );
    SELECT 1 FROM XYZ`,
    timeoutMs: 5000,
    location: "US"
  });

  const [rows] = await job.getQueryResults();

  const [childJobs] = await bq.getJobs({parentJobId: job.id});

  for (const job of childJobs) {
    console.log('Job: ', job.id);
    console.log('Error: ', job.metadata.errorResult);
  }

// Output:
//
// Job:  script_job_123...
// Error:  { reason: 'invalid',
//   location: 'xyz',
//   message: 'Table name "xyz" missing dataset while no default dataset is set in the request.' }
//
// Job:  script_job_678...
// Error:  undefined
```

Documentation for this concept is [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting#bigquery_scripting).
