### ISSUE TITLE
Job not found errors as of 5.3.0 -> 5.4.0 upgrade

### ISSUE THREAD

**Issue by BenBirt** [googleapis/nodejs-bigquery#888]
This is a client library issue.

#### Environment details

  - `@google-cloud/bigquery` version: `5.4.0`

#### Steps to reproduce

I can't give concrete steps to reproduce; we're still working on reliable repro instructions, this is more of a heads-up.

In https://github.com/dataform-co/dataform/pull/1076 we upgraded `@google-cloud/bigquery` from `5.3.0` to `5.4.0`, specifically to move past the fix for https://github.com/googleapis/nodejs-bigquery/issues/857.

However, it seems like the code has changed in some way such that `location` is now a required option (see https://github.com/dataform-co/dataform/pull/1079 for a proposed workaround on our end). We saw some of our EU users complain about Job Not Found errors (e.g. https://dataform-users.slack.com/archives/CHMJK8MKM/p1604399268146500). (US users being presumably unaffected because it's the default location.)

**Comment by stephenplusplus** [comment]
Thanks for reporting. I will have a fix shortly.

**Comment by stephenplusplus** [comment]
@BenBirt what API call is returning the error? Any more details about the code and error (exact wording, stacktrace, etc) would be helpful.

**Comment by BenBirt** [comment]
Unfortunately by the time we've logged it we've dropped stacktrace, but the error message form is `Not found: Job <project id>:dataform-<randomly generated id>`.

However, the code must be throwing somewhere inside here: https://github.com/dataform-co/dataform/blob/master/api/dbadapters/bigquery.ts#L431

So it's got to be `createQueryJob` or `getMetadata`.

If it helps, we'll continue to try to repro this ourselves and get you a better stacktrace.

**Comment by Ekrekr** [comment]
I think this is the stack trace you're looking for:

```
Error: Not found: Job dataform-corp:de90b2a0-0dc9-4def-aed9-019ec0672b35\
    at new ApiError (node_modules/@google-cloud/common/build/src/util.js:59:15)\
    at Util.parseHttpRespBody (node_modules/@google-cloud/common/build/src/util.js:194:38)\
    at Util.handleResp (node_modules/@google-cloud/common/build/src/util.js:135:117)\
    at node_modules/@google-cloud/common/build/src/util.js:434:22\
    at onResponse (node_modules/@google-cloud/common/node_modules/retry-request/index.js:206:7)\
    at node_modules/teeny-request/src/index.ts:325:11\
    at processTicksAndRejections (internal/process/task_queues.js:93:5
```

I'll outline more clearly where it's happening in our open source code and the fix for it in a mo

**Comment by Ekrekr** [comment]
We [create a query stream](https://github.com/dataform-co/dataform/blob/95b5176f765a7591ddac5c15d4fbf29a56f73864/api/dbadapters/bigquery.ts#L413) after [creating a client](https://github.com/dataform-co/dataform/blob/95b5176f765a7591ddac5c15d4fbf29a56f73864/api/dbadapters/bigquery.ts#L392).

In 5.3.0 location didn't need to be specified when creating the client, but in 5.4.0 it needs to be specified otherwise running a query stream against a table that isn't in the client-specified warehouse will throw this `Not found` error.

The location functionality was changed [here in `bigquery.ts` in the update from 5.3 to 5.4](https://github.com/googleapis/nodejs-bigquery/pull/864/files#), where location is changed to be (correct me if I'm wrong here) set from the request options, rather than a response from the BQ server. Instead I think location should *only* be limited in the case when the request options specify it.

**Comment by Ekrekr** [comment]
Proposed PR to fix: https://github.com/googleapis/nodejs-bigquery/pull/889

**Comment by stephenplusplus** [comment]
Thank you for digging through that. I have sent #890 with a similar fix, however it relies on what the API used for the job as opposed to the one that the user provided. I'm not sure exactly how the dataform library is handling user-provided "location" options at this time, but that would be good to make sure is coming through to this layer (which I think you're about to do with https://github.com/dataform-co/dataform/pull/1079).

**Comment by stephenplusplus** [comment]
@BenBirt, @Ekrekr -- this fix is out in 5.5.0. Please let me know if there are any more issues!

**Comment by mattshen** [comment]
The error still persists for me. 

here is my code :

```
    const [job] = await bigquery
        .dataset(datasetId)
        .table(tableId)
        .load(storage.bucket('testing-bucket').file('file123.JSONL'), {
            format: 'JSON',
            location: 'australia-southeast1' // i have to specified this, otherwise, API throws error
        });

```

errors: 
```
  errors: [
    {
      message: 'Not found: Job <project>:<job_id>',
      domain: 'global',
      reason: 'notFound'
    }
  ],
```

The job was actually successful, but the API still throws error.

**Comment by JustinBeckwith** [comment]
Greetings.  Please file a new issue!
