### ISSUE TITLE
Load firestore export from GCS is missing from documentation.

### ISSUE THREAD

**Issue by bhaumik55231** [googleapis/nodejs-bigquery#891]
I'm trying to load firestore exports from GCS into Bigquery and having trouble with the schemas, If I do not specify a schema in the nodejs SDK it shows me an error that the **schema is missing**, if I specify **autodetect** it loads the data in a weird manner.

Please see the nodejs code below.

```

  const {BigQuery} = require('@google-cloud/bigquery');
  const {Storage} = require('@google-cloud/storage');
  const storage = new Storage();
  const bigqueryClient = new BigQuery();

  const options = {
  
  }
  const jobConfigurationLoad = {
    load: {sourceFormat: 'DATASTORE_BACKUP'},
    location: 'US',
    writeDisposition: 'WRITE_TRUNCATE'
  };
  
  const [table] = await bigqueryClient
                    .dataset('Connect')
                    .table('participants', options)
                    .load(storage.bucket('connect_firestore_dev_backup')
                    .file(gcsEvent.name), jobConfigurationLoad);
```

It would be helpful if documentation is added on how to import firestore from GCS to Bigquey using nodejs.

**Comment by steffnay** [comment]
I think the issue is arising from the job configuration you are using. There should not be a `load` property.

Please try: 
```
  const jobConfigurationLoad = {
    sourceFormat: 'DATASTORE_BACKUP',
    location: 'US',
    writeDisposition: 'WRITE_TRUNCATE'
  };
  ```
  
   A couple samples incorrectly used a `load` property here, but were updated with #912
