### ISSUE TITLE
table.load() fails to find its own job when location is not specified in v5.x API

### ISSUE THREAD

**Issue by mbyrne00** [googleapis/nodejs-bigquery#896]
#### Environment details

  - OS: appengine-standard environment, local MacOS
  - Node.js version: 12.x, 14.x
  - npm version: 6.13.8
  - `@google-cloud/bigquery` version: 5.x (tested 5.0.0, 5.4.0). Works in v4.x

#### Steps to reproduce

  1. Create a dataset that is not in US (e.g. `australia-southeast-1`)
  2. Use the sample code to perform a load from https://github.com/googleapis/nodejs-bigquery/blob/master/samples/loadJSONFromGCS.js and omit the `location` option in `metadata`.
  3. The following error occurs

```
Error: Not found: Job my-test-project:396748ce-c4ec-449b-975d-1234567abb15
```

As mentioned this was working in v4. Not great if the api can internally create a job and lose track of it. This is not a huge priority because the workaround is to be explicit about specifying the `location`, however this is an undocumented change in v5 that may catch people unaware (I found root cause while documenting this issue).

**Comment by stephenplusplus** [comment]
Thank you for reporting. What was the root cause? Did you find a solution?

**Comment by stephenplusplus** [comment]
Oh, I also just noticed the version you were using. We fixed a bug that sounds like it would fix this one in 5.5.0: https://github.com/googleapis/nodejs-bigquery/pull/890. Could you make sure to try that version?

**Comment by mbyrne00** [comment]
Oh - actually we originally noticed the issue on `5.5.0`, looking through our commit history. Then we tried `5.4.0` and `5.0.0`. The solution/workaround was simply to be explicit with location.

**Comment by mbyrne00** [comment]
Just to be clear, this issue is still happening in `5.5.0`

**Comment by laljikanjareeya** [comment]
@mbyrne00 Thanks for the clarification. There is an issue in job's `getMetadata` where location is not getting updated in query string after creating the Job instance.

**This works fine:**
```ts
const bigquery = new BigQuery();
const job = new Job(bigquery, 'jobId', {
    location: 'australia-southeast1'
});

job.getMetadata((err, metadata, apiResponse) => { });
```

**This is doesn't work**
```ts
const bigquery = new BigQuery();
const job = new Job(bigquery, 'jobId');
job.location = 'australia-southeast1';
job.getMetadata((err, metadata, apiResponse) => { });
```

The linked PR will fix the above issue.
Thanks!!

**Comment by stephenplusplus** [comment]
@laljikanjareeya do we set `job.location` after creating a Job instance in our code somewhere or document that we support that?

**Comment by laljikanjareeya** [comment]
> @laljikanjareeya do we set `job.location` after creating a Job instance in our code somewhere or document that we support that?

Yes we are setting job location at below:
https://github.com/googleapis/nodejs-bigquery/blob/6bac26fefa0ef3fb8326ec129457babd01a6a1f8/src/bigquery.ts#L1550

**Comment by stephenplusplus** [comment]
Thanks!
