### ISSUE TITLE
implement support for Hive partitioning options in BigQuery

### ISSUE THREAD

**Issue by shollyman** [googleapis/nodejs-bigquery#897]
This feature request is to track client implementation of `HivePartitioningOptions` in BigQuery APi, which augments load and external query capabilities by allowing use of the GCS object path to infer additional partitioning columns.

Additional documentation has already been shared out of band with maintainers.

For Node, this may effectively be a no-op as it only augments the configuration object for loads and defining external table definitions.

Internal tracking issue: 142409248

**Comment by steffnay** [comment]
No-op.
