### ISSUE TITLE
Question: table clustering

### ISSUE THREAD

**Issue by russellwheatley** [googleapis/nodejs-bigquery#910]
Hey BigQuery team, I have a question regarding clustering. The API reference suggests that clustering might be possible [here](https://googleapis.dev/nodejs/bigquery/latest/Dataset.html#createTable) as it links to the table resource options. 

Although the `TableMetadata` [type](https://github.com/googleapis/nodejs-bigquery/blob/master/src/table.ts#L128) isn't expecting a clustering option. 

Is there a way to enable clustering via the nodejs client? If not, are there any plans to implement in the future?

**Comment by steffnay** [comment]
`clustering` is a property on `bigquery.ITable` and `TableMetadata` is an intersection type using that, which means `clustering` can be set. So this is currently supported:
```
    const options = {
      schema: {name: 'Name', type: 'STRING'},
      partitioning: 'day',
      clustering: {fields: ['Name']}
    };

    const [table] = await bigquery
      .dataset(datasetId)
      .createTable(tableId, options);
```
