### ISSUE TITLE
SDK Client Reference does not easily expose response types

### ISSUE THREAD

**Issue by bporterfield** [googleapis/nodejs-bigquery#918]
It's sometimes hard to understand what the bigquery client will return. Most calls return a Promise, and documentation often only describes that the calls return a Promise, but don't make clear what the Promise actually provides:

<img width="935" alt="Screen Shot 2021-01-27 at 4 14 20 PM" src="https://user-images.githubusercontent.com/108260/106071172-b8783000-60ba-11eb-8957-b6125dd982ff.png">

It's unclear what type is returned here. However, some function calls do have the Promise type documented:
<img width="833" alt="Screen Shot 2021-01-27 at 4 15 48 PM" src="https://user-images.githubusercontent.com/108260/106071310-f7a68100-60ba-11eb-94bd-9894cf9e4fef.png">

It would be really helpful if all the types were documented. Additionally, some of the return types don't seem to exist in the repo. In this example, this call (according to my IDE) actually returns a `Promise<MetadataResponse>`:

<img width="1359" alt="Screen Shot 2021-01-27 at 4 22 15 PM" src="https://user-images.githubusercontent.com/108260/106071796-d4300600-60bb-11eb-8772-5be235f76d07.png">

But, what is a `MetadataResponse`? It's not something I can find anywhere in this repo, nor can I find any documentation about the structure of this object. Is there somewhere else I should be looking for this documentation?

Thanks!

**Comment by steffnay** [comment]
You are right that our documentation here is unclear. I'm planning to do a major overhaul of the in-line documentation in the library, which is what is used to create the docs pages you referenced and will reference this issue when that PR is opened. For now, though, there is more information about the expected request/response object structures here https://cloud.google.com/bigquery/docs/reference/rest/v2/routines/get
