### ISSUE TITLE
Pagination ?

### ISSUE THREAD

**Issue by walshe** [googleapis/nodejs-bigquery#919]
just looking at the pagination sample: https://github.com/googleapis/nodejs-bigquery/blob/master/samples/queryPagination.js

I don't see how its doing pagination.. isnt it simply getting 100 rows and just outputting it ? where does it get the next page ?

**Comment by meredithslota** [comment]
The Cloud Client Libraries for Node.js automatically paginates by default, so you do not need to implement pagination yourself, for example: https://cloud.google.com/bigquery/docs/paging-results#bigquery_browse_table-nodejs

**Comment by stephenplusplus** [comment]
@walshe [this page](https://cloud.google.com/bigquery/docs/paging-results#bigquery_browse_table-nodejs) shows an example of manual pagination under "Paging through results using the API". The code snippet you linked is under the "Paging through query results" heading, which is confusing.

@meredithslota would a title of "Iterating over query results" or "Printing query results" be more accurate for that section to disassociate from "pagination"?

**Comment by walshe** [comment]
I figured it out. I wanted the chance to be able to make inserts to a separate system in between each page call to BQ. Here is example for anyone:

````
const extractTransformLoad = async (etlSessionId) => {
  log("extracting..");

  const bigqueryClient = new BigQuery();
    
  const query = `SELECT * FROM \`xxxxx\``;
  
  const [job] = await bigqueryClient.createQueryJob(query);

  let loadedCount = 0;

  return new Promise( async(resolve,reject) => {
    const manualPaginationCallback = async (err, rows, nextQuery, apiResponse) => {
    
      await load(etlSessionId, transform(rows));
      loadedCount += rows.length;
  
      if (nextQuery) {
        // More results exist.
        job.getQueryResults(nextQuery, manualPaginationCallback);
      }else{
        resolve(loadedCount)
      }
    }

    await job.getQueryResults({
      autoPaginate : false,
      maxResults : 200
    }, manualPaginationCallback);
    

  })
````

**Comment by BenHewins** [comment]
Couldn't find how to do this documented anywhere other than this thread - I made a varient of @walshe 's solution using iterators and asyn/await instead of callbacks. Useful if you don't want to load the whole result set into memory at once.
```

  private async *QueryBigQuery(): AsyncIterableIterator<unknown> {
    const options: Query = {
      query: 'SELECT * FROM mytable WHERE bar > @foo',
      // Location must match that of the dataset(s) referenced in the query.
      location: 'europe-west2',
      useLegacySql: false,
      // maxResults: 5, Doesn't work for this - use the getQueryResults one instead
      params: { foo: 2 },
    };

    const bqClient = new BigQuery();

    const [job] = await bqClient.createQueryJob(options);

    let pageToken: string | undefined = undefined;

    do {
      const res: QueryRowsResponse = await job.getQueryResults({
        maxResults: 5000,
        pageToken,
      });

      const [rows, _, resultsResponse] = res as QueryRowsResponse; // Not sure why the 'as' is required here

      for (const row of rows) {
        yield row;
      }
      pageToken = resultsResponse?.pageToken;
    } while (pageToken);
  }
```

**Comment by jdleesmiller** [comment]
I think these examples can be simplified somewhat by using the built `nextQuery` result from the manual pagination callback to handle the paging. Here is a helper function that lets one iterate over results with `for await`, only loading `maxResults` results into memory at a time:

```js
/**
 * Helper to page through the results of a query job.
 *
 * Approach based on
 * https://github.com/googleapis/nodejs-bigquery/issues/919#issuecomment-1195345442
 * with some simplifications.
 *
 * @param {import("@google-cloud/bigquery/build/src/types").bigquery.Job} job
 * @param {number} maxResults the size of one page
 */
async function* eachRowOfJobResult(job, maxResults) {
  let rows
  let queryResultsOptions = {
    autoPaginate: false,
    maxResults
  }

  do {
    [rows, queryResultsOptions] = await job.getQueryResults(queryResultsOptions)
    for (const row of rows) yield row
  } while (queryResultsOptions)
}

const query = '...'
const maxResults = 1000
const [job] = await bigquery.createQueryJob({ query, location: 'US' })
for await (const row of eachRowOfJobResult(job, maxResults)) {
  console.log(row)
}
```

**Comment by aryzle** [comment]
hey so back to the original question, where is the automatic pagination? All these examples are manual

FWIW I implemented pagination using LIMIT, OFFSET, any thoughts against this? as opposed to using `queryResultsOptions` and `nextQuery` given back by the query
