### ISSUE TITLE
TypeScript Typings

### ISSUE THREAD

**Issue by urish** [googleapis/nodejs-bigquery#92]
Adding TypeScript typings will make the library easier to consume for TypeScript users, and it will also enable intellisense for JavaScript users (at least in Visual Studio Code).

Basically this means creating a `.d.ts` file with all the function signatures, pointing to it from the `typings` field of your package.json, and publishing it to NPM. I can help and try to work on a PR, if you are interested.

Also, here is a partial typings file I'm currently using for my own project:

```typescript
declare module '@google-cloud/bigquery' {
    interface IInsertResponse {
        kind: 'bigquery#tableDataInsertAllResponse';
        insertErrors?: [{
            'index': number,
            'errors': [{
                'reason': string,
                'location': string,
                'debugInfo': string,
                'message': string,
            }],
        }];
    }

    class Table {
        public insert(rows: any[]): Promise<IInsertResponse[] | null>;
    }

    class Dataset {
        public table(name: string): Table;
    }

    class Bigquery {
        public query(options: { query: string, params?: any[], maxResults?: number }): Promise<[any[]]>;
        public dataset(name: string): Dataset;
    }

    function create(options?: any): Bigquery;

    namespace create {
    }

    export = create;
}
```

**Comment by stephenplusplus** [comment]
cc @JustinBeckwith @ofrobots who have been doing this in nodejs-common.

**Comment by snird** [comment]
This issue is dragged since 2015, back when the code were in the big repo: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/952

**Comment by stephenplusplus** [comment]
I haven't heard anything official, but I believe we're eventually converting all of our library code to TypeScript. Let's keep this issue over there: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/952
