### ISSUE TITLE
Memory leak when calling getDatasets()

### ISSUE THREAD

**Issue by tomdee** [googleapis/nodejs-bigquery#929]
I have a specific use case where I need to be able to create multiple BigQuery clients with different credentials inside a single long running process. This process is currently leaking memory and crashing.

#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: v14.15.1
  - npm version: 6.14.8
  - `@google-cloud/bigquery` version: v5.5.0

#### Steps to reproduce
Run this sample code (after filling in some credentials)

index.js
```
import { BigQuery } from "@google-cloud/bigquery";
import { HeapDiff } from "@airbnb/node-memwatch";

const projectId = "FILL_IN";
const credentials = {  client_email: `FILL_IN`,  private_key: `FILL IN`};

const REPETITIONS = 10;
console.log(`Running ${REPETITIONS} times`);
for (var i = 0; i < REPETITIONS; i++) {
  await doWork();
}

async function doWork() {
  var hd = new HeapDiff();
  const bigQuery = new BigQuery({
    projectId,
    credentials,
  });
  await bigQuery.getDatasets();
  var diff = hd.end();
  console.dir(diff.change.size_bytes);
}
```

package.json
```
{
  "type": "module",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@airbnb/node-memwatch": "^2.0.0",
"@google-cloud/bigquery": "^5.5.0",
  }
}

```

The output indicates that it's leaking around 250KB of RAM on each loop through. There's no global state in this simple repro which is indicating that there's something wrong in `@google-cloud/bigquery`
```
Running 10 times
386247
230904
254784
247664
249704
255697
253655
251649
249272
247224
```

Thanks for creating this library and let me know if there are any more diagnostics that I can provide.

**Comment by steffnay** [comment]
Closing, please re-open if continues to be an issue.
