### ISSUE TITLE
Existing documentation for OAuth2 configuration is out of date

### ISSUE THREAD

**Issue by JamesYeoman** [googleapis/nodejs-bigquery#930]
The instructions provided at https://cloud.google.com/bigquery/docs/authentication/end-user-installed don't work, because the object returned by `authFlow` doesn't conform to the `GoogleAuthOptions` parameter of the BigQuery constructor. After digging around in the code, trying approaches like setting the clientOptions, overriding the auth client after the constructor, and manually creating a server so I can use the web-based flow, I'm still no closer to being able to run queries on behalf of users using their credentials.

#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: 12.8.1
  - npm version: 7.5.2
  - `@google-cloud/bigquery` version: 5.5.0

#### Steps to reproduce

  1. Try to authenticate using the method provided at https://cloud.google.com/bigquery/docs/authentication/end-user-installed

**Comment by meredithslota** [comment]
Hi @JamesYeoman — thanks for the report! Can you provide a little bit more info about the kinds of issues/errors you're encountering? We'll try to repro as well.

**Comment by JamesYeoman** [comment]
Any attempt to get the sdk to use OAuth credentials fails because it tries to then load the Application Default credentials. Service Accounts work fine, but I need to be able to use the SDK with the end-user's credentials (because permissions)

**Comment by JamesYeoman** [comment]
I should probably also point out that I'm using Typescript, so I need to conform to the provided interfaces, even if the underlying JS would accept other data

**Comment by JamesYeoman** [comment]
Upon closer inspection of the auth code, and following the data flow, I've come to the conclusion that the `getClient` function on line 490 of `googleauth.js` in `google-auth-library` is likely the culprit.

If neither `jsonContent` nor `keyFilename` are defined, it falls back to application default credentials, but in order to use `UserRefreshClient` as the auth client, the `clientOptions` field on `GoogleAuthOptions` needs to contain a `type` property with the content `'authorized_user'` (as found in the `_cacheClientFromJSON` function on line 289 of `googleauth.js` in `google-auth-library`.

However, the only way to populate the `jsonContent` field of the `GoogleAuth` class, `fromJSON` needs to be called, and there isn't anywhere in the flow that I've identified that specifies any JSON content. I'm going to try loading the credentials manually after creating the bigquery instance to see if that works, and then I'll report back

**Comment by JamesYeoman** [comment]
So, it's _still_ trying to load the application default credentials. I've created a gist of the updated code (I re-did the functionality of readline-promise because there isn't any type definitions available for it at the moment), so if anyone more familiar with the codebase could take a look to see if anything stands out to them?

https://gist.github.com/JamesYeoman/50a935e7a6245effbe8755ad113dcb9e

**Comment by JamesYeoman** [comment]
Ah, I tried assigning the result of `client.authClient.fromJSON` to the cached credential, and it worked :tada:

Would it be possible to have this added to https://cloud.google.com/bigquery/docs/authentication/end-user-installed as a NodeJS Typescript method?

**Comment by steffnay** [comment]
I think the reason you are encountering this problem is because your `authFlow` function is returning only `credentials` rather than both `projectId` and `credentials`, as shown in the sample code.

```
// sample authUserFlow.js line #99
return {
  projectId,
  credentials,
};
```
```
// your gist line #55
return credentials;
```

I don't think you will need this workaround if you return the object with both fields, as shown in the sample.

**Comment by steffnay** [comment]
Please reopen if initializing client with both `credentials` and `projectId` does not solve the issue.
