### ISSUE TITLE
Newer versions of the library seem to have lost the easy support for loading Datastore/Firestore backups

### ISSUE THREAD

**Issue by ggprod** [googleapis/nodejs-bigquery#933]
In older versions there was an import method on the Table object that could be used for this purpose.  The new methods `load` and `createLoadJob` don't seem to support the DATASTORE_BACKUP format.

Is manually creating a Job the only way to do this via the API now?  Could the `load` and `createLoadJob` methods be updated to support datastore/firestore backups?

**Comment by ggprod** [comment]
seems like the only change would be to add the element `datastore: DATASTORE_BACKUP` (or something like that) to the `FORMATS` array

**Comment by meredithslota** [comment]
I wonder if anything changed on the Datastore/Firestore side that would have caused this accidentally — I don't recall us intentionally removing this, but my memory could be fuzzy too. Thanks for the report, we will dig in. Do you know which of the older version had this? (It would make our investigation faster.)

**Comment by ggprod** [comment]
@meredithslota the code I updated that had this capability was using @google-cloud/bigquery 0.9.6.  Very old I realize (I think circa 2017).  We didn't end up touching this code since as it was simple and worked ok.  I'd like to upgrade it now and have done so using the createJob method but would be nice to have that simpler method back
