### ISSUE TITLE
A method for truncating an existing table

### ISSUE THREAD

**Issue by ggprod** [googleapis/nodejs-bigquery#934]
This is a feature request to add a method for truncating an existing table.  For non-partitioned tables it could just use the `query` method with the TRUNCATE TABLE statement (https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#truncate_table_statement).  For partitioned tables it would need another approach

**Comment by steffnay** [comment]
We currently favor users running the SQL queries using the query method over providing new methods that run SQL queries.
