### ISSUE TITLE
FR: support mutable clustering configuration

### ISSUE THREAD

**Issue by shollyman** [googleapis/nodejs-bigquery#941]
BigQuery service released support [mutable clustering configuration](https://cloud.google.com/bigquery/docs/creating-clustered-tables#modifying-cluster-spec) some time ago, but this hasn't propagated to all clients.

I see for example the stale commentary in [src/types.d.ts](https://github.com/googleapis/nodejs-bigquery/blob/16d2a505400564cb49210d25f52fccfdaef42dd5/src/types.d.ts#L1406) related to clustering.

Library should ensure:

* Clustering configuration can be modified on a managed table via a table update call
* Documentation reflects this capability, and possibly links to the cloud.google.com content above to describe the behavior when clustering is added/changed.
* Stale comments indicating that clustering requires a partitioning config are removed (you can cluster a table without partitioning it)

**Comment by meredithslota** [comment]
I believe this is fixed with the linked PR #989 but assigning to @steffnay to confirm before closing.
