### ISSUE TITLE
table.insert does not return a Promise

### ISSUE THREAD

**Issue by sk-** [googleapis/nodejs-bigquery#948]
`table.insert` does not return a promise or has a dangling one

1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
Node

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: MacOs
  - Node.js version: v14.16.1
  - npm version: 6.14.12
  - `@google-cloud/bigquery` version: 5.5.0

#### Steps to reproduce

1) Call `table.insert` without a callback and wrap it in a try/catch, as in:

```js
try {
  await this.table.insert({...});
} catch (error) {
 ...
}
```

2) If the data has a wrong type, then the call will have an Unhandled rejection.

Below are the errors:
```
Unhandled rejection
Unhandled rejection
PartialFailureError at Table._insert (/workspace/node_modules/@google-cloud/bigquery/build/src/table.js:1611:19)
                               at processTicksAndRejections (internal/process/task_queues.js:97:5)
                               at async Table._insertWithRetry (/workspace/node_modules/@google-cloud/bigquery/build/src/table.js:1548:24)
                               at async Table._insertAndCreateTable (/workspace/node_modules/@google-cloud/bigquery/build/src/table.js:1510:20)
```

**Comment by larssn** [comment]
This might explain why we're seeing data loss when inserting from Cloud Functions. Every day we lose 1-10 rows without errors.

This could be because CF has very strict coding guidelines as in: "_Every promise must be awaited_". If you have a promise running when it gets to EOF, the CPU loses all resources, making the promise not complete.

**Comment by feywind** [comment]
@larssn Thanks for the patch! Hopefully this will clear up the issue for everyone.

**Comment by sk-** [comment]
@feywind Please reopen this and revert the PR. As I pointed out the change does not fix the issue, as the methods were already being promisified.
