### ISSUE TITLE
Table.setMetadata function is duplicated

### ISSUE THREAD

**Issue by tswast** [googleapis/nodejs-bigquery#95]
I received this feedback on a code sample. There are duplicate method definitions for Table.setMetadata.

One refers to Table#update

https://github.com/googleapis/nodejs-bigquery/blob/affdfa65a3297e685c5f00a4c0714d9230e746bc/src/table.js#L1798-L1845

The other refers to Table#patch

https://github.com/googleapis/nodejs-bigquery/blob/affdfa65a3297e685c5f00a4c0714d9230e746bc/src/table.js#L237-L274

I believe only PATCH should be supported as UPDATE can be unsafe (end up modifying / removing unintended properties).

**Comment by stephenplusplus** [comment]
It looks like we are using PATCH. More details in the fix PR: #97
