### ISSUE TITLE
error:  ApiError: Error during request.

### ISSUE THREAD

**Issue by hixus** [googleapis/nodejs-bigquery#96]
#### Environment details

  - OS: OS X high sierra
  - Node.js version: v8.7.0
  - npm version: 5.4.2
  - `@google-cloud/bigquery` version: 1.0.0

#### Steps to reproduce

  1. Create table from csv and schema autodetect enabled
  2. Create a load job without schema autodetect

The documentation https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load says that I can omit the schema if table exists. However if I leave autodetect away then I get this api error. Not sure what the actual reason is as it's just general error.

**Comment by hixus** [comment]
This works
```
const metadata = {
    sourceFormat: 'CSV',
    writeDisposition: 'WRITE_APPEND',
    autodetect: true
  }
  const table = bq.dataset(config.get('gCloud.bigQuery.dataset')).table(folder)
  const file = bucket.file(filePath)
  Bacon.fromNodeCallback(table, 'load', file, metadata).log()
```

This doesn't 
```
const metadata = {
    sourceFormat: 'CSV',
    writeDisposition: 'WRITE_APPEND',
    autodetect: false
  }
  const table = bq.dataset(config.get('gCloud.bigQuery.dataset')).table(folder)
  const file = bucket.file(filePath)
  Bacon.fromNodeCallback(table, 'load', file, metadata).log()
```

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce. Could you create a runnable sample to demonstrate the problem? Or, feel free to correct this one to highlight the problem:

```js
const [dataset] = await bigquery.dataset('stephen_test_dataset').get({autoCreate: true})
const [table] = await dataset.table('stephen_test_table').get({autoCreate: true})

const [bucket] = await storage.bucket('stephen-has-a-new-bucket').get({autoCreate: true})

// kitten-test-data.csv contents: "stephen",3
const [file] = await bucket.upload('./system-test/data/kitten-test-data.csv')

const [firstLoadApiResponse] = await table.load(file, {
  sourceFormat: 'CSV',
  writeDisposition: 'WRITE_APPEND',
  autodetect: true,
})
assert.equal(firstLoadApiResponse.statistics.load.outputRows, 1)

const [secondLoadApiResponse] = await table.load(file, {
  sourceFormat: 'CSV',
  writeDisposition: 'WRITE_APPEND',
  autodetect: false,
})
assert.equal(secondLoadApiResponse.statistics.load.outputRows, 1)
```

**Comment by hixus** [comment]
Sorry my bad. Full error was hidden in my implementation. The reason was that autodetect also detects file delimiter and header rows. Although table schema was correct the default delimiter and header rows where not. I had to define those in options. Working example:
```
await table.load({
    sourceFormat: 'CSV',
    writeDisposition: 'WRITE_APPEND',
    skipLeadingRows: 1,
    fieldDelimiter: '\t',
    autodetect: false
  })
```
