### ISSUE TITLE
EXTERNAL_QUERY sometimes throws with Error: Not found: Connection <connection-name> 

### ISSUE THREAD

**Issue by Portur** [googleapis/nodejs-bigquery#978]
#### Environment details

  - OS: Windows (19 Pro - 19043.1110)
  - Node.js version: 12.21
  - npm version: 6.11.3
  - `@google-cloud/bigquery` version: 5.6.0

#### Steps to reproduce

  1. Use the NodeJS client query using `SELECT * FROM EXTERNAL_QUERY(...`

#### Issue

Hi, I'm running into a presistent but unpredictable issue where quering Bigquery would sometimes throw when querying an external connection.

#### Details

I'm importing old archives from CloudSQL and using a `date` to progressively import segments. This is run in a loop, and each segment is queried. 

```javascript
let import_query = `SELECT * FROM EXTERNAL_QUERY("projects/project-name/locations/eu/connections/connection-name","SELECT * FROM some_function_by_date('2021-07-19');");`
await _BigQuery_.query(import_query);
```

There are a total of about 24 ~ 48 dates and maybe 300k rows in total. The loop starts and the first few run smooth, however at some point an error gets thrown saying the connection does not exist

![image](https://user-images.githubusercontent.com/24350810/126550800-00116039-4e5d-416a-82ab-4d28833c57c8.png)

This happens every time, but at different intervals. Sometimes the first iteration, sometimes the 12th.

_I'm sure the query itself it not the issue but simply added the explanation of dated segments to emphasize multiple external queries being called one after each other._

**Comment by SurferJeffAtGoogle** [comment]
This issue is now OoSLO.

**Comment by Portur** [comment]
What is OoSLO?

**Comment by steffnay** [comment]
@Portur can you confirm that all of the connections were created in the eu? I am wondering if there is some location issue.

**Comment by steffnay** [comment]
Closing. Please reopen with location information, if possible.
